/*
 * tstrans.h — C ABI for ts-transformer (mpeg-ts + KLV + SRT).
 *
 * This file is GENERATED by cbindgen. Do not edit manually.
 * Source of truth: crates/tst-c/src/ (Rust).
 *
 * Copyright (c) 2026 Andrew Klofas. Licensed under MIT OR Apache-2.0.
 */


#ifndef TSTRANS_H
#define TSTRANS_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>

/**
 * Major version (compile-time macro in the generated header).
 */
#define TST_VERSION_MAJOR 0

/**
 * Minor version.
 */
#define TST_VERSION_MINOR 1

/**
 * Patch version.
 */
#define TST_VERSION_PATCH 0

/**
 * Sentinel returned by `tst_mux_config_add_*_stream` on failure.
 * On failure, the last-error is also populated; check
 * `tst_get_last_error()` for the negative `TST_E_*` code.
 */
#define TST_INVALID_STREAM_HANDLE UINT32_MAX

/**
 * Maximum number of per-stream entries in any stats struct exposed at
 * the C ABI. Rarely exceeded — multi-stream `mpegts::mux` caps at
 * 16 video + 16 KLV = 32, leaving 32 slots of headroom for receiver
 * PSI + observed streams.
 */
#define TST_STATS_MAX_STREAMS 64

enum tst_video_codec
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  TST_VIDEO_CODEC_H264 = 0,
  TST_VIDEO_CODEC_H265 = 1,
  TST_VIDEO_CODEC_H266 = 2,
  TST_VIDEO_CODEC_AV1 = 3,
};
#ifndef __cplusplus
typedef int32_t tst_video_codec;
#endif // __cplusplus

typedef enum tst_klv_stream_type {
  TST_KLV_STREAM_TYPE_PRIVATE_DATA = 0,
  TST_KLV_STREAM_TYPE_SYNCHRONOUS_METADATA = 1,
} tst_klv_stream_type;

typedef enum tst_ts_framing_mode {
  TST_TS_FRAMING_MODE_RECOVER = 0,
  TST_TS_FRAMING_MODE_STRICT = 1,
} tst_ts_framing_mode;

typedef enum tst_overflow_policy {
  TST_OVERFLOW_POLICY_DROP_OLDEST = 0,
  TST_OVERFLOW_POLICY_REJECT = 1,
} tst_overflow_policy;

/**
 * Negative codes returned by every fallible tst-c entry point.
 *
 * `Success = 0` is the only non-negative variant. Codes are stable
 * across tst-c versions; new codes append at the end.
 */
enum tst_e
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  TST_E_SUCCESS = 0,
  TST_E_INVALID_CONFIG = -1,
  TST_E_INVALID_NAL = -2,
  TST_E_INVALID_TS = -3,
  TST_E_BUFFER_FULL = -4,
  TST_E_KLV_TOO_LARGE = -5,
  TST_E_TOO_LARGE = -6,
  TST_E_CLOSED = -7,
  TST_E_TRANSPORT = -8,
  TST_E_INVALID_USAGE = -9,
  TST_E_INTERNAL = -10,
  /**
   * Internal panic caught at the FFI boundary; the handle is now in
   * an indeterminate state. Subsequent calls on the same handle will
   * also fail (returning `Closed`). The caller should free the handle.
   */
  TST_E_PANIC_CAUGHT = -11,
  /**
   * Peer disconnected gracefully (received TCP-style FIN / SRT clean close).
   * Distinguished from `Closed` (caller-side cancel/close) so receive loops
   * can branch on the shutdown reason. After this code the handle is dead;
   * subsequent calls return `Closed`.
   */
  TST_E_END_OF_STREAM = -12,
  /**
   * Requested data is not currently available — typically because a
   * `tst_managed_*` handle has no live inner socket (mid-reconnect or
   * after close). Distinct from `InvalidUsage` (which means the handle
   * is in a fundamentally wrong state for the call) — `NotAvailable`
   * is transient and may resolve on the next call.
   *
   * Returned today by the `tst_*_get_socket_stats` family when the
   * inner transport's `socket_stats()` returns `None`.
   */
  TST_E_NOT_AVAILABLE = -13,
};
#ifndef __cplusplus
typedef int32_t tst_e;
#endif // __cplusplus

/**
 * `repr(i32)` discriminator for `TstEvent::kind`. cbindgen emits
 * `#define TST_EVENT_*` blocks.
 */
enum tst_event_kind
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  TST_EVENT_KIND_PROGRAM_MAP = 1,
  TST_EVENT_KIND_SAMPLE = 2,
  TST_EVENT_KIND_METADATA = 3,
  TST_EVENT_KIND_DISCONTINUITY = 4,
  TST_EVENT_KIND_NON_CONFORMANT = 5,
};
#ifndef __cplusplus
typedef int32_t tst_event_kind;
#endif // __cplusplus

/**
 * `repr(i32)` mirror of `tst_core::mpegts::demux::StreamKind`'s
 * discriminator. Variant payloads (codec, declared_link, unknown
 * stream_type) live on the per-event union fields, not on this enum.
 */
enum tst_stream_kind
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  TST_STREAM_KIND_VIDEO = 0,
  TST_STREAM_KIND_AUDIO = 1,
  TST_STREAM_KIND_SUBTITLE = 2,
  TST_STREAM_KIND_KLV_SYNC = 3,
  TST_STREAM_KIND_KLV_ASYNC = 4,
  TST_STREAM_KIND_UNKNOWN = 5,
};
#ifndef __cplusplus
typedef int32_t tst_stream_kind;
#endif // __cplusplus

/**
 * `repr(i32)` mirror of `tst_core::mpegts::demux::MetadataKind`'s
 * discriminator. Variant payload (the KlvSyncAuCell 5 fields) lives
 * on `tst_event_t.u.metadata` fields, zero/false for other kinds.
 */
enum tst_metadata_kind
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  TST_METADATA_KIND_KLV_SYNC_AU_CELL = 0,
  TST_METADATA_KIND_KLV_ASYNC = 1,
  TST_METADATA_KIND_UNKNOWN = 2,
};
#ifndef __cplusplus
typedef int32_t tst_metadata_kind;
#endif // __cplusplus

/**
 * `repr(i32)` mirror of `tst_core::mpegts::demux::DiscontinuityKind`'s
 * discriminator. ContinuityJump's `expected`/`observed` and
 * PesOversize's `pid` live on the union fields.
 */
enum tst_discontinuity_kind
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  TST_DISCONTINUITY_KIND_CONTINUITY_JUMP = 0,
  TST_DISCONTINUITY_KIND_PES_OVERSIZE = 1,
  TST_DISCONTINUITY_KIND_PES_TOTAL_OVERSIZE = 2,
  TST_DISCONTINUITY_KIND_ADAPTATION_FIELD_FLAG = 3,
};
#ifndef __cplusplus
typedef int32_t tst_discontinuity_kind;
#endif // __cplusplus

/**
 * `repr(i32)` mirror of `tst_core::mpegts::demux::NonConformantIssue`'s
 * discriminator. Issue-specific fields live on `tst_event_t.u.nonconformant`
 * (zero/null for variants that don't carry them).
 */
enum tst_nonconformant_code
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  TST_NONCONFORMANT_CODE_STREAM_TYPE_MISMATCH_SYNC_ON_ASYNC_PID = 0,
  TST_NONCONFORMANT_CODE_STREAM_TYPE_MISMATCH_ASYNC_ON_SYNC_PID = 1,
  TST_NONCONFORMANT_CODE_MISSING_METADATA_DESCRIPTOR = 2,
  TST_NONCONFORMANT_CODE_PCR_ANOMALY = 3,
  TST_NONCONFORMANT_CODE_PSI_CHECKSUM_MISMATCH = 4,
  TST_NONCONFORMANT_CODE_PUSI_MID_PES = 5,
  TST_NONCONFORMANT_CODE_PID_REUSED_ACROSS_PROGRAMS = 6,
  TST_NONCONFORMANT_CODE_SUBTITLE_MISSING_DESCRIPTOR = 7,
  TST_NONCONFORMANT_CODE_SUBTITLE_DESCRIPTOR_AMBIGUOUS = 8,
  TST_NONCONFORMANT_CODE_SUBTITLE_DESCRIPTOR_MALFORMED = 9,
  TST_NONCONFORMANT_CODE_AV1_REGISTRATION_MALFORMED = 10,
  TST_NONCONFORMANT_CODE_AV1_OBU_MISSING_SIZE_FIELD = 11,
  TST_NONCONFORMANT_CODE_AV1_TILE_LIST_NOT_ALLOWED = 12,
  TST_NONCONFORMANT_CODE_PSI_OVERLONG_SECTION = 13,
  TST_NONCONFORMANT_CODE_TRANSPORT_ERROR_PACKET = 14,
  TST_NONCONFORMANT_CODE_PSI_CC_DISCONTINUITY = 15,
  TST_NONCONFORMANT_CODE_MULTI_CELL_AU = 16,
  TST_NONCONFORMANT_CODE_PSI_MULTI_SECTION_UNSUPPORTED = 17,
  TST_NONCONFORMANT_CODE_OTHER = 18,
};
#ifndef __cplusplus
typedef int32_t tst_nonconformant_code;
#endif // __cplusplus

/**
 * `repr(i32)` mirror of `tst_core::mpegts::demux::LinkSource`.
 * On `tst_klv_link_t.source` and on synthetic KLV-link inference.
 */
enum tst_link_source
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  TST_LINK_SOURCE_DECLARED = 0,
  TST_LINK_SOURCE_INFERRED = 1,
  TST_LINK_SOURCE_OVERRIDE = 2,
};
#ifndef __cplusplus
typedef int32_t tst_link_source;
#endif // __cplusplus

/**
 * `repr(i32)` mirror of `tst_core::mpegts::demux::StrictMode`.
 *
 * Four-valued enum: `Off=0` (default, lenient), `TimingOnly=1`,
 * `DescriptorsOnly=2`, `Full=3`. cbindgen emits parallel `#define
 * TST_STRICT_MODE_*` blocks for C callers.
 *
 * NOTE: this differs from the receiver-surface design doc §7.1, which
 * originally specified `0=Off, 1=KlvOnly, 2=All`. The actual Rust enum
 * is 4-valued; this mapping is the truth.
 */
enum tst_strict_mode
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  TST_STRICT_MODE_OFF = 0,
  TST_STRICT_MODE_TIMING_ONLY = 1,
  TST_STRICT_MODE_DESCRIPTORS_ONLY = 2,
  TST_STRICT_MODE_FULL = 3,
};
#ifndef __cplusplus
typedef int32_t tst_strict_mode;
#endif // __cplusplus

/**
 * `repr(i32)` mirror of `tst_core::mpegts::demux::AudioCodec`.
 * On `tst_event_t.u.sample.codec` when `stream_kind == TST_STREAM_KIND_AUDIO`,
 * and on `tst_stream_info_t.codec`.
 */
enum tst_audio_codec
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  TST_AUDIO_CODEC_MP2 = 0,
  TST_AUDIO_CODEC_AAC = 1,
  TST_AUDIO_CODEC_AAC_LATM = 2,
  TST_AUDIO_CODEC_AC3 = 3,
};
#ifndef __cplusplus
typedef int32_t tst_audio_codec;
#endif // __cplusplus

/**
 * `repr(i32)` mirror of `tst_core::mpegts::demux::SubtitleCodec`.
 * On `tst_event_t.u.sample.codec` when `stream_kind == TST_STREAM_KIND_SUBTITLE`,
 * and on `tst_stream_info_t.codec`.
 */
enum tst_subtitle_codec
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  TST_SUBTITLE_CODEC_DVB_SUBTITLING = 0,
  TST_SUBTITLE_CODEC_DVB_TELETEXT = 1,
  TST_SUBTITLE_CODEC_CEA708_STANDALONE = 2,
  TST_SUBTITLE_CODEC_WEB_VTT_IN_TS = 3,
};
#ifndef __cplusplus
typedef int32_t tst_subtitle_codec;
#endif // __cplusplus

/**
 * Opaque demux-config builder. Heap-allocated via `_new`, mutated
 * in place via setters, released via `_free`. The receiver clones
 * what it needs at `_open_with_config` time; the caller still owns
 * the builder.
 *
 * Lifecycle mirrors `tst_mux_config_t` from plan #14 exactly.
 */
typedef struct tst_demux_config_t tst_demux_config_t;

typedef struct tst_demux_receiver_t tst_demux_receiver_t;

typedef struct tst_managed_demux_receiver_t tst_managed_demux_receiver_t;

typedef struct tst_managed_mux_sender_t tst_managed_mux_sender_t;

typedef struct tst_managed_raw_receiver_t tst_managed_raw_receiver_t;

typedef struct tst_managed_raw_sender_t tst_managed_raw_sender_t;

typedef struct tst_managed_receiver_t tst_managed_receiver_t;

typedef struct tst_managed_sender_t tst_managed_sender_t;

/**
 * Opaque mux-config builder. Constructed via `tst_mux_config_new`,
 * populated via `tst_mux_config_add_program` + stream-add / descriptor-set
 * entry points, then consumed by `tst_*_open` (which clones the inner).
 * Caller is responsible for calling `tst_mux_config_free`.
 *
 * Unlike the pre-multi-program API, the config starts **empty** — no program
 * is pre-created. The caller must call `tst_mux_config_add_program` at
 * least once before opening a muxer or sender.
 */
typedef struct tst_mux_config_t tst_mux_config_t;

typedef struct tst_mux_sender_t tst_mux_sender_t;

typedef struct tst_muxer_t tst_muxer_t;

typedef struct tst_raw_receiver_t tst_raw_receiver_t;

typedef struct tst_raw_sender_t tst_raw_sender_t;

typedef struct tst_raw_sender_config_t tst_raw_sender_config_t;

typedef struct tst_receiver_t tst_receiver_t;

typedef struct tst_reconnect_policy_t tst_reconnect_policy_t;

typedef struct tst_sender_t tst_sender_t;

typedef struct tst_sender_config_t tst_sender_config_t;

/**
 * Opaque handle returned by `tst_mux_config_add_program`. Used as an
 * argument to subsequent stream-add and config-set entry points to
 * disambiguate which program's streams or descriptors are being modified.
 *
 * The value is a zero-based index into the program list. Programs are
 * numbered in the order they were added. Handles are stable across the
 * config→open boundary — the same index applies after `tst_muxer_open`.
 */
typedef uint32_t tst_program_handle_t;

/**
 * Opaque per-program ordinal for a video elementary stream. Obtained from
 * `tst_mux_config_add_video_stream` at config time and reused with the
 * `_video_to` push siblings on every muxer-owning C variant.
 *
 * Handles are stable across the config→open boundary and across managed
 * reconnects. They encode `(program_index, within_program_index)` as a
 * packed `u32` (bits 4..=7 = program, bits 0..=3 = within). They are NOT
 * interchangeable between muxers.
 */
typedef uint32_t tst_video_stream_handle_t;

/**
 * Opaque per-program ordinal for a KLV elementary stream. Same packed
 * encoding as [`TstVideoStreamHandle`].
 */
typedef uint32_t tst_klv_stream_handle_t;

/**
 * `repr(C)` mirror of `tst_core::mpegts::demux::psi::RawDescriptor`.
 *
 * `data` borrows from the demuxer's per-PMT descriptor list; valid
 * until the next `_recv_event` / `_close` call on this handle. The
 * length byte from the wire is stripped — `data_len` is the body length.
 */
typedef struct tst_descriptor_t {
  uint8_t tag;
  uint8_t _reserved[7];
  const uint8_t *data;
  size_t data_len;
} tst_descriptor_t;

/**
 * Opaque per-program ordinal for an audio elementary stream. Same packed
 * encoding as [`TstVideoStreamHandle`].
 */
typedef uint32_t TstAudioStreamHandle;

/**
 * Opaque per-program ordinal for a subtitle elementary stream. Same packed
 * encoding as [`TstVideoStreamHandle`].
 */
typedef uint32_t TstSubtitleStreamHandle;

/**
 * `repr(C)` mirror of `tst_core::mpegts::demux::StreamInfo`.
 *
 * `stream_kind` is `TST_STREAM_KIND_*` (see `TstStreamKindTag`);
 * `codec` is `TST_VIDEO_CODEC_*` / `TST_AUDIO_CODEC_*` /
 * `TST_SUBTITLE_CODEC_*` keyed by `stream_kind`, or `-1` when
 * `stream_kind` is KlvSync / KlvAsync / Unknown.
 *
 * `raw_descriptors` borrows from the demuxer's per-PMT descriptor
 * list; valid until the next `_recv_event` / `_close` call.
 */
typedef struct tst_stream_info_t {
  uint16_t pid;
  uint8_t stream_type;
  uint8_t _pad;
  int stream_kind;
  int codec;
  uint16_t program_number;
  uint8_t _pad2[6];
  const struct tst_descriptor_t *raw_descriptors;
  size_t descriptor_count;
} tst_stream_info_t;

/**
 * `repr(C)` mirror of `tst_core::mpegts::demux::KlvLink`.
 * `source` is `TST_LINK_SOURCE_*` (see `TstLinkSource`).
 */
typedef struct tst_klv_link_t {
  uint16_t klv_pid;
  uint16_t video_pid;
  int source;
} tst_klv_link_t;

typedef struct TstEventProgramMap {
  uint16_t program_number;
  uint16_t pcr_pid;
  uint8_t _pad[4];
  const struct tst_stream_info_t *streams;
  size_t stream_count;
  const struct tst_klv_link_t *klv_links;
  size_t klv_link_count;
} TstEventProgramMap;

/**
 * `repr(C)` mirror of `tst_core::mpegts::demux::NalUnit`.
 *
 * Three Rust variants (H264 / H265 / H266) collapsed into one C
 * struct; field semantics keyed by the parent `tst_event_t.u.sample.codec`.
 * * H.264: `nal_type` 5-bit; `ref_idc_or_layer_id` is `ref_idc`;
 *   `temporal_id_plus1` is `0` (H.264 has no temporal_id).
 * * H.265 / H.266: `nal_type` 6-bit (H.265) or 5-bit (H.266);
 *   `ref_idc_or_layer_id` is `nuh_layer_id`; `temporal_id_plus1`
 *   is the temporal-id field +1 (per spec).
 *
 * `payload` borrows from the demuxer's NAL-unit Vec; valid until
 * the next `_recv_event` / `_close` call on this handle.
 */
typedef struct tst_nal_t {
  uint8_t nal_type;
  uint8_t ref_idc_or_layer_id;
  uint8_t temporal_id_plus1;
  uint8_t _reserved;
  const uint8_t *payload;
  size_t payload_len;
} tst_nal_t;

/**
 * `repr(C)` mirror of `tst_core::mpegts::demux::Obu`.
 *
 * `has_extension` is 0 or 1; `temporal_id` and `spatial_id` are
 * valid only when `has_extension == 1`. `payload` is the OBU body
 * (header byte + extension byte + LEB128 size already stripped).
 */
typedef struct tst_obu_t {
  uint8_t obu_type;
  uint8_t has_extension;
  uint8_t temporal_id;
  uint8_t spatial_id;
  const uint8_t *payload;
  size_t payload_len;
} tst_obu_t;

typedef struct TstEventSample {
  uint16_t pid;
  uint16_t program_number;
  int stream_kind;
  int64_t pts;
  int64_t dts;
  int codec;
  uint8_t _pad[4];
  const struct tst_nal_t *nals;
  size_t nal_count;
  const struct tst_obu_t *obus;
  size_t obu_count;
  const uint8_t *payload;
  size_t payload_len;
} TstEventSample;

typedef struct TstEventMetadata {
  uint16_t pid;
  uint16_t program_number;
  uint8_t _pad[4];
  int64_t pts;
  int metadata_kind;
  uint8_t _pad2[4];
  const uint8_t *payload;
  size_t payload_len;
  uint8_t metadata_service_id;
  uint8_t sequence_number;
  uint8_t cell_fragment_indication;
  uint8_t decoder_config_flag;
  uint8_t random_access_indicator;
  uint8_t _pad3[3];
} TstEventMetadata;

typedef struct TstEventDiscontinuity {
  uint16_t pid;
  uint8_t _pad[2];
  int discontinuity_kind;
  uint8_t cc_expected;
  uint8_t cc_observed;
  uint8_t _pad2[6];
} TstEventDiscontinuity;

typedef struct TstEventNonConformant {
  uint16_t pid;
  uint8_t _pad[2];
  int issue_code;
  int64_t pcr_delta;
  uint8_t table_id;
  uint8_t last_section_number;
  uint8_t cc_expected;
  uint8_t cc_observed;
  uint8_t _pad2[4];
  size_t observed_len;
  uint8_t obu_type;
  uint8_t _pad3[7];
  const uint16_t *programs;
  const uint8_t *tags;
  size_t tag_count;
  const char *detail;
} TstEventNonConformant;

/**
 * Per-event-kind union body for `TstEvent`. cbindgen emits this as
 * `union { ... } u` on the C side; each kind's fields are a flat
 * nested struct. Fields not relevant to the active `kind` are zero
 * or null after `convert()`.
 */
typedef union TstEventBody {
  struct TstEventProgramMap program_map;
  struct TstEventSample sample;
  struct TstEventMetadata metadata;
  struct TstEventDiscontinuity discontinuity;
  struct TstEventNonConformant nonconformant;
} TstEventBody;

/**
 * Top-level event struct. Caller stack-allocates and passes
 * `&mut TstEvent` to `tst_demux_receiver_recv_event`. After a
 * success return, `kind` selects which `u.*` body is populated;
 * pointer fields on the active body borrow from the receiver's
 * `EventArena` until the next `_recv_event` / `_close` call.
 */
typedef struct tst_event_t {
  int kind;
  uint8_t _pad[4];
  union TstEventBody u;
} tst_event_t;

/**
 * `repr(C)` mirror of `tst_pipeline::DemuxReceiverStats`. Size 48 B.
 *
 * Application-level counters for the demux receive shell. Faithfully
 * mirrors `tst_pipeline::DemuxReceiverStats` — six u64 fields:
 * * `bytes_received` / `packets_received` — application-level totals
 *   from the inner `Receiver` (one 188-byte packet per success).
 * * `program_maps_seen` / `pmt_versions_seen` — PSI topology counters.
 *   `program_maps_seen` increments on every PMT emission; `pmt_versions_seen`
 *   only on a `version_number` bump (PMT churn detector).
 * * `discontinuities` — sum across all PIDs of `DemuxEvent::Discontinuity`
 *   emissions (continuity-counter jumps, PES oversize, etc).
 * * `nonconformant` — sum across all PIDs of `DemuxEvent::NonConformant`
 *   emissions (17 issue variants; see `tst_event_t.u.nonconformant.issue_code`).
 *
 * NOTE: sync-recovery counters (`bytes_skipped_for_sync`, `resync_events`)
 * are deliberately absent — they live only on the inner `Receiver`'s
 * `ReceiverStats` (surfaced via Phase 2's `TstReceiverStats`). Adding
 * them here would mis-label the data source. Consumers needing them
 * run a `tst_receiver_t` instead of a `tst_demux_receiver_t`.
 *
 * The per-PID `BTreeMap<u16, StreamStats>` from `DemuxReceiverStats`
 * is NOT included on this struct; it ships separately via
 * `tst_demux_receiver_get_stream_stats` returning a borrowed
 * `(*const TstStreamStats, size_t)` pair per design §4.5.
 */
typedef struct tst_demux_receiver_stats_t {
  uint64_t bytes_received;
  uint64_t packets_received;
  uint64_t program_maps_seen;
  uint64_t pmt_versions_seen;
  uint64_t discontinuities;
  uint64_t nonconformant;
} tst_demux_receiver_stats_t;

/**
 * `repr(C)` mirror of `tst_core::mpegts::StreamStats`. Size 96 B.
 *
 * Layout (offsets):
 *   0: items (u64, 8 B)
 *   8: bytes (u64, 8 B)
 *  16: discontinuities (u64, 8 B)
 *  24: pid (u16, 2 B)
 *  26: stream_type (u8, 1 B)
 *  27: _pad (3 B, alignment bridge)
 *  30: program_number (u16, 2 B)
 *  32: label ([c_char; 64], 64 B)
 * Total: 96 B — identical to the pre-program_number layout.
 */
typedef struct tst_stream_stats_t {
  uint64_t items;
  uint64_t bytes;
  uint64_t discontinuities;
  uint16_t pid;
  uint8_t stream_type;
  /**
   * Alignment padding bridging stream_type → program_number.
   */
  uint8_t _pad[3];
  /**
   * Program number from the PAT that owns this stream. 0 for PSI PIDs.
   */
  uint16_t program_number;
  /**
   * NUL-terminated UTF-8. `label[0]==0` means None. Truncated at 63
   * bytes (first 63 + NUL).
   */
  char label[64];
} tst_stream_stats_t;

/**
 * `repr(C)` mirror of `tst_pipeline::MuxSenderStats`. Size 6188 B.
 */
typedef struct tst_mux_sender_stats_t {
  uint64_t bytes_sent;
  uint64_t packets_sent;
  uint64_t pending_bytes_queued;
  uint64_t pending_chunks_queued;
  /**
   * Number of programs (PAT entries) in the muxer configuration.
   */
  uint32_t programs_configured;
  uint32_t per_stream_count;
  uint32_t per_stream_truncated;
  struct tst_stream_stats_t per_stream[TST_STATS_MAX_STREAMS];
} tst_mux_sender_stats_t;

/**
 * `repr(C)` mirror of `tst_core::transport::SocketStats`. Size 120 B.
 *
 * Layout (offsets in bytes — verified by the `_TST_SOCKET_STATS_SIZE`
 * const assertion below):
 *   0: rtt_us              (u32, 4 B)
 *   4: send_buffer_packets (u32, 4 B)
 *   8: recv_buffer_packets (u32, 4 B)
 *  12: _pad                (u32, 4 B, alignment bridge to u64 below)
 *  16: send_bandwidth_bps  (u64, 8 B)
 *  24: recv_bandwidth_bps  (u64, 8 B)
 *  32: link_bandwidth_bps  (u64, 8 B)
 *  40: bytes_sent          (u64, 8 B)
 *  48: packets_sent        (u64, 8 B)
 *  56: bytes_received      (u64, 8 B)
 *  64: packets_received    (u64, 8 B)
 *  72: bytes_lost_recv     (u64, 8 B)
 *  80: packets_lost_recv   (u64, 8 B)
 *  88: packets_lost_send   (u64, 8 B)
 *  96: packets_retransmitted (u64, 8 B)
 * 104: packets_dropped_send  (u64, 8 B)
 * 112: packets_dropped_recv  (u64, 8 B)
 * Total: 120 B.
 *
 * All bandwidth fields are bits per second; RTT is microseconds;
 * buffer-depth fields are in packets. See
 * `tst_core::transport::SocketStats` rustdoc for the libsrt source
 * mappings.
 */
typedef struct tst_socket_stats_t {
  uint32_t rtt_us;
  uint32_t send_buffer_packets;
  uint32_t recv_buffer_packets;
  /**
   * Alignment padding bridging the u32 prefix to the u64 tail.
   */
  uint32_t _pad;
  uint64_t send_bandwidth_bps;
  uint64_t recv_bandwidth_bps;
  uint64_t link_bandwidth_bps;
  uint64_t bytes_sent;
  uint64_t packets_sent;
  uint64_t bytes_received;
  uint64_t packets_received;
  uint64_t bytes_lost_recv;
  uint64_t packets_lost_recv;
  uint64_t packets_lost_send;
  uint64_t packets_retransmitted;
  uint64_t packets_dropped_send;
  uint64_t packets_dropped_recv;
} tst_socket_stats_t;

/**
 * `repr(C)` mirror of `tst_core::mpegts::mux::MuxerStats`. Size 6172 B.
 */
typedef struct tst_muxer_stats_t {
  uint64_t ts_packets_emitted;
  uint64_t ts_bytes_emitted;
  /**
   * Number of programs (PAT entries) in this muxer's configuration.
   */
  uint32_t programs_configured;
  uint32_t per_stream_count;
  uint32_t per_stream_truncated;
  struct tst_stream_stats_t per_stream[TST_STATS_MAX_STREAMS];
} tst_muxer_stats_t;

/**
 * `repr(C)` mirror of `tst_pipeline::RawReceiverStats`. Size 16 B.
 */
typedef struct tst_raw_receiver_stats_t {
  uint64_t bytes_received;
  uint64_t packets_received;
} tst_raw_receiver_stats_t;

/**
 * `repr(C)` mirror of `tst_pipeline::RawSenderStats`. Size 16 B.
 */
typedef struct tst_raw_sender_stats_t {
  uint64_t bytes_sent;
  uint64_t packets_sent;
} tst_raw_sender_stats_t;

/**
 * `repr(C)` mirror of `tst_pipeline::ReceiverStats`. Size 32 B.
 *
 * Application-level counters for the TS-aligned receive shell. Mirrors
 * the layout of `tst_pipeline::ReceiverStats`:
 * * `bytes_received` / `packets_received` — application-level totals
 *   (one 188-byte packet per `_recv_packet` success).
 * * `bytes_skipped_for_sync` / `resync_events` — sync-recovery state
 *   from the underlying `tst_pipeline::receiver::sync::Syncer`. Non-zero
 *   `resync_events` indicates the syncer hit HUNT/VERIFY mid-stream
 *   (either initial lock-on or re-lock after corruption).
 */
typedef struct tst_receiver_stats_t {
  uint64_t bytes_received;
  uint64_t bytes_skipped_for_sync;
  uint64_t resync_events;
  uint64_t packets_received;
} tst_receiver_stats_t;

/**
 * Public-ABI mirror of `tst_pipeline::SenderStats`. Same fields,
 * same units. Caller passes a pointer to a stack-allocated struct;
 * `tst_sender_get_stats` fills it in.
 */
typedef struct tst_sender_stats_t {
  uint64_t bytes_pushed;
  uint64_t bytes_skipped_for_sync;
  uint64_t resync_events;
  uint64_t packets_sent;
} tst_sender_stats_t;

/**
 * Sentinel returned by `tst_mux_config_add_program` on failure (null cfg
 * or other hard error). Check `tst_get_last_error()` for the reason.
 */
#define TST_INVALID_PROGRAM_HANDLE UINT32_MAX

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new, empty mux config. No programs are added — call
 * `tst_mux_config_add_program` before using this config to open a muxer
 * or sender. Returns NULL only on allocation failure (OOM).
 */
 struct tst_mux_config_t *tst_mux_config_new(void);

/**
 * Free a mux config previously returned by `tst_mux_config_new`. No-op on
 * NULL. The config must not be used after this call.
 */
 void tst_mux_config_free(struct tst_mux_config_t *p);

/**
 * Begin a new program in this multiplex. Returns a handle used as the
 * `program` argument to subsequent stream-add and descriptor-set entry
 * points. Programs are numbered in insertion order starting at 0.
 *
 * `program_number` is the PAT program_number field (must be > 0 and unique
 * within the config). `pmt_pid` is the PID on which this program's PMT will
 * be carried (must be unique within the config and not collide with any
 * stream PID).
 *
 * Returns `TST_INVALID_PROGRAM_HANDLE` and sets last-error on null `cfg`.
 * Validation (duplicate program_number, colliding PMT PID, etc.) is deferred
 * to `tst_muxer_open` / `tst_*_sender_open` time.
 */

tst_program_handle_t tst_mux_config_add_program(struct tst_mux_config_t *cfg,
                                                uint16_t program_number,
                                                uint16_t pmt_pid);

/**
 * Add a video elementary stream to the specified program and return its
 * handle.
 *
 * The returned `tst_video_stream_handle_t` is stable across the config→open
 * boundary and across managed-sender reconnects. Pass it to
 * `tst_muxer_push_video_to` / `tst_mux_sender_send_video_to` /
 * `tst_managed_mux_sender_send_video_to` to fan out to this specific stream.
 *
 * Returns `TST_INVALID_STREAM_HANDLE` and sets last-error on: null `cfg`,
 * invalid `program` handle, or per-program stream cap exceeded (>16 streams
 * of any kind per program). Hard validation errors surface at `_open` time.
 */

tst_video_stream_handle_t tst_mux_config_add_video_stream(struct tst_mux_config_t *cfg,
                                                          tst_program_handle_t program,
                                                          uint16_t pid,
                                                          tst_video_codec codec);

/**
 * Add a KLV elementary stream to the specified program and return its handle.
 *
 * `stream_type`: `TST_KLV_STREAM_TYPE_PRIVATE_DATA` (0x06, async — no AU
 * cell wrapping) or `TST_KLV_STREAM_TYPE_SYNCHRONOUS_METADATA` (0x15 —
 * the muxer auto-wraps each push in a 5-byte `Metadata_AU_cell` header
 * per ITU-T H.222.0 V9 § 2.12.4.2 before TS-framing; pass raw KLV LS
 * bytes to `push_klv_to`).
 *
 * `carries_pts`: set `true` for synchronous KLV (PTS carried in PES header),
 * `false` for async KLV.
 *
 * Returns `TST_INVALID_STREAM_HANDLE` on error (same conditions as
 * `tst_mux_config_add_video_stream`).
 */

tst_klv_stream_handle_t tst_mux_config_add_klv_stream(struct tst_mux_config_t *cfg,
                                                      tst_program_handle_t program,
                                                      uint16_t pid,
                                                      enum tst_klv_stream_type stream_type,
                                                      bool carries_pts);

/**
 * Pin the PCR PID for the specified program. By default the muxer uses the
 * first video stream's PID (or first KLV PID for KLV-only programs).
 *
 * Returns 0 on success, or a negative `TST_E_*` code on null pointer or
 * invalid program handle.
 */

int tst_mux_config_set_pcr_pid(struct tst_mux_config_t *cfg,
                               tst_program_handle_t program,
                               uint16_t pid);

/**
 * Set the PCR re-emission interval for this mux config (applies to all
 * programs). Default is 40 ms. Must be in range 1..=100.
 */
 int tst_mux_config_set_pcr_interval_ms(struct tst_mux_config_t *p, uint32_t ms);

/**
 * Set the PAT/PMT re-emission interval for this mux config. Default 100 ms.
 * Must be >= 10.
 */
 int tst_mux_config_set_psi_interval_ms(struct tst_mux_config_t *p, uint32_t ms);

/**
 * Set the TS-packet output buffer capacity. Default 10000 (~1.88 MB).
 * Must be >= 10.
 */
 int tst_mux_config_set_buffer_packets(struct tst_mux_config_t *p, size_t n);

/**
 * Set program-level PMT descriptors for the specified program.
 *
 * `tlv_bytes` points to the concatenation of `tlv_count` TLV triples,
 * totalling `tlv_total_len` bytes. Each TLV has the layout:
 *   byte 0: tag
 *   byte 1: length of body (N)
 *   bytes 2..2+N: body
 *
 * Calling with `tlv_total_len == 0` or `tlv_count == 0` clears any
 * previously set program descriptors for this program.
 *
 * Returns 0 on success or a negative `TST_E_*` code on: null `cfg`,
 * null `tlv_bytes` with non-zero count, invalid program handle, or a
 * malformed TLV byte stream (truncated length or body).
 */

int tst_mux_config_set_program_descriptors(struct tst_mux_config_t *cfg,
                                           tst_program_handle_t program,
                                           const uint8_t *tlv_bytes,
                                           size_t tlv_total_len,
                                           size_t tlv_count);

/**
 * Set per-stream PMT descriptors for the specified video stream.
 *
 * `video` is a handle previously returned by `tst_mux_config_add_video_stream`.
 * The TLV byte format is the same as `tst_mux_config_set_program_descriptors`.
 *
 * Calling with `tlv_total_len == 0` or `tlv_count == 0` clears any
 * previously set stream descriptors for this stream.
 *
 * Returns 0 on success or a negative `TST_E_*` code on: null `cfg`,
 * invalid handle, null `tlv_bytes` with non-zero count, or malformed TLV.
 */

int tst_mux_config_set_stream_descriptors_for_video(struct tst_mux_config_t *cfg,
                                                    tst_video_stream_handle_t video,
                                                    const uint8_t *tlv_bytes,
                                                    size_t tlv_total_len,
                                                    size_t tlv_count);

/**
 * Set per-stream PMT descriptors for the specified KLV stream.
 *
 * `klv` is a handle previously returned by `tst_mux_config_add_klv_stream`.
 * The TLV byte format is the same as `tst_mux_config_set_program_descriptors`.
 *
 * Returns 0 on success or a negative `TST_E_*` code on the same conditions
 * as `tst_mux_config_set_stream_descriptors_for_video`.
 */

int tst_mux_config_set_stream_descriptors_for_klv(struct tst_mux_config_t *cfg,
                                                  tst_klv_stream_handle_t klv,
                                                  const uint8_t *tlv_bytes,
                                                  size_t tlv_total_len,
                                                  size_t tlv_count);

/**
 * Append one PMT descriptor to a video stream's per-PID descriptor list.
 *
 * `stream` is the handle returned by `tst_mux_config_add_video_stream`.
 * `desc` must be non-null with `desc.data` pointing to `desc.data_len`
 * bytes (stripped length — does not include the tag/length header bytes).
 * Bytes are copied; the caller's buffer is not retained after this call.
 * Multiple calls accumulate; descriptors appear in the PMT in add-order.
 *
 * Returns 0 on success, or a negative `TST_E_*` code on: null `cfg` or
 * `desc`, stale handle, null `desc.data` with non-zero `desc.data_len`,
 * or `desc.data_len > 255` (MPEG-TS descriptor body limit).
 */

int tst_mux_config_add_video_descriptor(struct tst_mux_config_t *cfg,
                                        tst_video_stream_handle_t stream,
                                        const struct tst_descriptor_t *desc);

/**
 * Append one PMT descriptor to a KLV stream's per-PID descriptor list.
 * Same contract as `tst_mux_config_add_video_descriptor`.
 *
 * `stream` is the handle returned by `tst_mux_config_add_klv_stream`.
 */

int tst_mux_config_add_klv_descriptor(struct tst_mux_config_t *cfg,
                                      tst_klv_stream_handle_t stream,
                                      const struct tst_descriptor_t *desc);

/**
 * Append one PMT descriptor to an audio stream's per-PID descriptor list.
 * Same contract as `tst_mux_config_add_video_descriptor`.
 *
 * `stream` is the handle returned by `tst_mux_config_add_audio_stream`.
 */

int tst_mux_config_add_audio_descriptor(struct tst_mux_config_t *cfg,
                                        TstAudioStreamHandle stream,
                                        const struct tst_descriptor_t *desc);

/**
 * Append one PMT descriptor to a subtitle stream's per-PID descriptor list.
 * Same contract as `tst_mux_config_add_video_descriptor`.
 *
 * `stream` is the handle returned by `tst_mux_config_add_subtitle_stream`.
 */

int tst_mux_config_add_subtitle_descriptor(struct tst_mux_config_t *cfg,
                                           TstSubtitleStreamHandle stream,
                                           const struct tst_descriptor_t *desc);

 struct tst_sender_config_t *tst_sender_config_new(void);

 void tst_sender_config_free(struct tst_sender_config_t *p);


int tst_sender_config_set_framing_mode(struct tst_sender_config_t *p,
                                       enum tst_ts_framing_mode mode);

 int tst_sender_config_set_max_unsynced_bytes(struct tst_sender_config_t *p, size_t n);

 struct tst_raw_sender_config_t *tst_raw_sender_config_new(void);

 void tst_raw_sender_config_free(struct tst_raw_sender_config_t *p);

 struct tst_reconnect_policy_t *tst_reconnect_policy_new(void);

 void tst_reconnect_policy_free(struct tst_reconnect_policy_t *p);

/**
 * Set max reconnect attempts. `n < 0` means retry forever.
 */
 int tst_reconnect_policy_set_max_attempts(struct tst_reconnect_policy_t *p, int32_t n);

 int tst_reconnect_policy_set_backoff_constant_ms(struct tst_reconnect_policy_t *p, uint32_t ms);


int tst_reconnect_policy_set_backoff_exponential_ms(struct tst_reconnect_policy_t *p,
                                                    uint32_t base_ms,
                                                    uint32_t max_ms);

 int tst_reconnect_policy_set_gap_buffer_capacity(struct tst_reconnect_policy_t *p, size_t n);


int tst_reconnect_policy_set_overflow_policy(struct tst_reconnect_policy_t *p,
                                             enum tst_overflow_policy policy);

/**
 * Allocate a new `tst_demux_config_t` with default values
 * (strict mode = Off, no overrides, default PES caps).
 *
 * Returns `NULL` on allocation failure or internal panic.
 * Free with `tst_demux_config_free`.
 */
 struct tst_demux_config_t *tst_demux_config_new(void);

/**
 * Release a `tst_demux_config_t`. Safe to call with NULL.
 */
 void tst_demux_config_free(struct tst_demux_config_t *cfg);

/**
 * Set the demuxer's strict mode. `mode` is one of
 * `TST_STRICT_MODE_OFF` (0, default), `TST_STRICT_MODE_TIMING_ONLY` (1),
 * `TST_STRICT_MODE_DESCRIPTORS_ONLY` (2), or `TST_STRICT_MODE_FULL` (3).
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` on null `cfg` or
 * unrecognized `mode`.
 */
 int tst_demux_config_set_strict_mode(struct tst_demux_config_t *cfg, int mode);

/**
 * Add a `klv_pid` → `video_pid` KLV-link override. Bypasses PMT-descriptor
 * inference. Returns 0 on success, `TST_E_INVALID_CONFIG` on null `cfg`.
 */

int tst_demux_config_add_link_klv(struct tst_demux_config_t *cfg,
                                  uint16_t klv_pid,
                                  uint16_t video_pid);

/**
 * Force a PID's stream-kind classification. `stream_kind` is one of
 * `TST_STREAM_KIND_VIDEO_H264`, `TST_STREAM_KIND_VIDEO_H265`,
 * `TST_STREAM_KIND_AUDIO_MP2`, ... — see the header for the full table.
 *
 * NOTE: The C-side mapping flattens (TstStreamKindTag × codec) pairs
 * into single integers. The implementation table below covers the
 * common cases — extend if a consumer asks for a kind not listed.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` on null `cfg` or
 * unrecognized `stream_kind`.
 */
 int tst_demux_config_add_treat_as(struct tst_demux_config_t *cfg, uint16_t pid, int stream_kind);

/**
 * Set PES reassembly caps. `0` means use the Rust-side default.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` on null `cfg`.
 */
 int tst_demux_config_set_pes_cap(struct tst_demux_config_t *cfg, size_t per_pid, size_t total);

/**
 * Open a `tst_demux_receiver_t` with default demux options.
 * Accepts `srt://host:port?...` URLs; `?mode=listener` routes through
 * the listener path (equivalent to `_open_listener`).
 */
 struct tst_demux_receiver_t *tst_demux_receiver_open(const char *srt_url);

/**
 * Explicit listener-mode open with default demux options.
 */
 struct tst_demux_receiver_t *tst_demux_receiver_open_listener(const char *srt_url);

/**
 * Open a `tst_demux_receiver_t` with a caller-supplied
 * `tst_demux_config_t`. The config is cloned-from at open time;
 * the caller still owns it and must `_free` it.
 */

struct tst_demux_receiver_t *tst_demux_receiver_open_with_config(const char *srt_url,
                                                                 const struct tst_demux_config_t *cfg);

/**
 * Explicit listener-mode open with a caller-supplied
 * `tst_demux_config_t`.
 */

struct tst_demux_receiver_t *tst_demux_receiver_open_listener_with_config(const char *srt_url,
                                                                          const struct tst_demux_config_t *cfg);

 void tst_demux_receiver_close(struct tst_demux_receiver_t *p);

/**
 * Block until one typed `TstEvent` is ready, then populate
 * `*out_event` with the converted event.
 *
 * **Borrowed buffer lifetime (design §4.5):** pointer fields on
 * `*out_event` borrow from this handle's `EventArena`. They are
 * valid until the next `_recv_event` / `_close` call on the same
 * handle. Callers wanting longer lifetime memcpy out before the
 * next call.
 *
 * Returns:
 * - `0` on success (`*out_event` populated; pointer fields borrow)
 * - `TST_E_END_OF_STREAM` (-12) on graceful peer close
 * - `TST_E_CLOSED` (-7) if the handle was `_cancel`'d or `_close`'d
 * - `TST_E_TRANSPORT` (-8) on transport failure
 * - `TST_E_INVALID_TS` (-3) on a demuxer error (strict-mode rejection
 *   or unrecoverable packet malformation)
 * - `TST_E_INVALID_CONFIG` (-1) on null pointer arguments
 *
 * On any non-zero return the contents of `*out_event` are unspecified.
 */
 int tst_demux_receiver_recv_event(struct tst_demux_receiver_t *p, struct tst_event_t *out_event);

/**
 * Cancel a `tst_demux_receiver_t`. Unblocks a thread parked in
 * `_recv_event` within one libsrt I/O cycle (~3-10 ms) by closing
 * the underlying libsrt socket. Safe to call from any thread.
 * Idempotent.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 *
 * After cancel, `_recv_event` returns `TST_E_CLOSED` (not
 * `TST_E_END_OF_STREAM`). The handle must still be `_close`'d to free.
 */
 int tst_demux_receiver_cancel(struct tst_demux_receiver_t *p);

/**
 * Snapshot stats for a `tst_demux_receiver_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer
 * is null, `TST_E_CLOSED` if the receiver has been closed.
 *
 * NOTE: per-PID counters are NOT included on this struct — call
 * `tst_demux_receiver_get_stream_stats` to retrieve them.
 */

int tst_demux_receiver_get_stats(struct tst_demux_receiver_t *p,
                                 struct tst_demux_receiver_stats_t *out);

/**
 * Reset stats counters for a `tst_demux_receiver_t` to zero.
 * Also invalidates the borrowed `_get_stream_stats` snapshot
 * (design §4.5).
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is
 * null, `TST_E_CLOSED` if the receiver has been closed.
 */
 int tst_demux_receiver_reset_stats(struct tst_demux_receiver_t *p);

/**
 * Snapshot per-PID stats for a `tst_demux_receiver_t` into the
 * handle's internal buffer; return a `(*const TstStreamStats, size_t)`
 * pair borrowing that buffer.
 *
 * **Borrowed buffer lifetime (design §4.5):** `*out_array` is valid
 * until the next `_get_stream_stats` / `_reset_stats` / `_close`
 * call on the same handle. Callers wanting longer lifetime memcpy
 * the array out.
 *
 * Capped at `TST_STATS_MAX_STREAMS = 64` entries (BTreeMap ordering
 * preserved by ascending PID); excess streams are silently dropped.
 * `program_number` field is `0` for now — populated once `StreamStats`
 * surfaces it (currently absent from `tst_core::mpegts::stats::StreamStats`).
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` on any null pointer
 * arg, or `TST_E_CLOSED` if the receiver has been closed.
 */

int tst_demux_receiver_get_stream_stats(struct tst_demux_receiver_t *p,
                                        const struct tst_stream_stats_t **out_array,
                                        size_t *out_count);

/**
 * Open a `tst_managed_demux_receiver_t` with default demux options.
 * URL-driven mode dispatch matches `tst_demux_receiver_open`.
 * `policy` is the reconnect policy; pass NULL for default.
 */

struct tst_managed_demux_receiver_t *tst_managed_demux_receiver_open(const char *srt_url,
                                                                     const struct tst_reconnect_policy_t *policy);

/**
 * Explicit listener-mode open for the managed demux receiver.
 */

struct tst_managed_demux_receiver_t *tst_managed_demux_receiver_open_listener(const char *srt_url,
                                                                              const struct tst_reconnect_policy_t *policy);

/**
 * Open with a TstDemuxConfig override. URL-driven mode dispatch.
 */

struct tst_managed_demux_receiver_t *tst_managed_demux_receiver_open_with_config(const char *srt_url,
                                                                                 const struct tst_reconnect_policy_t *policy,
                                                                                 const struct tst_demux_config_t *cfg);

/**
 * Explicit listener-mode open with a TstDemuxConfig override.
 */

struct tst_managed_demux_receiver_t *tst_managed_demux_receiver_open_listener_with_config(const char *srt_url,
                                                                                          const struct tst_reconnect_policy_t *policy,
                                                                                          const struct tst_demux_config_t *cfg);

/**
 * Block until one typed `TstEvent` is ready.
 *
 * **Asymmetry with plain receiver:** plain `tst_demux_receiver_recv_event`
 * maps `TransportError::Broken` on a non-cancelled handle to
 * `TST_E_END_OF_STREAM`. The managed version does NOT apply that mapping —
 * `ManagedReceiveTransport` retries internally on Broken, so a Broken
 * reaching this function means reconnect attempts are exhausted: a hard
 * transport failure (`TST_E_TRANSPORT`), not end-of-stream.
 */

int tst_managed_demux_receiver_recv_event(struct tst_managed_demux_receiver_t *p,
                                          struct tst_event_t *out_event);

/**
 * Cancel a `tst_managed_demux_receiver_t`. Same shape as the plain
 * sibling — side-channel cancel, no Mutex acquisition. Safe from
 * any thread. Idempotent.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 *
 * After cancel, `_recv_event` returns `TST_E_CLOSED` (not
 * `TST_E_END_OF_STREAM`). The handle must still be `_close`'d to free.
 */
 int tst_managed_demux_receiver_cancel(struct tst_managed_demux_receiver_t *p);

 void tst_managed_demux_receiver_close(struct tst_managed_demux_receiver_t *p);


int tst_managed_demux_receiver_get_stats(struct tst_managed_demux_receiver_t *p,
                                         struct tst_demux_receiver_stats_t *out);

 int tst_managed_demux_receiver_reset_stats(struct tst_managed_demux_receiver_t *p);


int tst_managed_demux_receiver_get_stream_stats(struct tst_managed_demux_receiver_t *p,
                                                const struct tst_stream_stats_t **out_array,
                                                size_t *out_count);

/**
 * Read the most recent error code on this thread. Returns `0`
 * (`TST_E_SUCCESS`) if no error has been recorded on this thread yet.
 * The value is not cleared by successful calls; it reflects the most
 * recent failure on this thread (or `TST_E_SUCCESS` if there has been
 * none since thread start).
 */
 int tst_get_last_error(void);

/**
 * Pointer to the most recent error message on this thread. Valid until
 * the next tst-c call on the same thread. Never NULL — empty string when
 * no error.
 */
 const char *tst_get_last_error_str(void);

/**
 * Open a `tst_mux_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `tst_get_last_error_str()` describes the specific problem.
 */
 struct tst_mux_sender_t *tst_mux_sender_open(const char *srt_url, struct tst_mux_config_t *cfg);


int tst_mux_sender_send_video(struct tst_mux_sender_t *p,
                              const uint8_t *nal,
                              size_t len,
                              int64_t pts_90khz,
                              bool key_frame);


int tst_mux_sender_send_klv(struct tst_mux_sender_t *p,
                            const uint8_t *klv,
                            size_t len,
                            int64_t pts_90khz);

/**
 * Push one Annex-B NAL targeting a specific video elementary stream.
 *
 * `stream_handle` is obtained from `tst_mux_config_add_video_stream` at
 * config time and is stable across the config→open boundary. Out-of-range
 * handles surface as `TST_E_INVALID_USAGE` (carrying
 * `MuxError::InvalidStreamHandle`).
 *
 * On a single-stream sender, prefer `tst_mux_sender_send_video` — same
 * effect, no handle required.
 */

int tst_mux_sender_send_video_to(struct tst_mux_sender_t *p,
                                 tst_video_stream_handle_t stream_handle,
                                 const uint8_t *nal,
                                 size_t len,
                                 int64_t pts_90khz,
                                 bool key_frame);

/**
 * Push one pre-built KLV blob targeting a specific KLV elementary stream.
 *
 * For `KlvStreamType::SynchronousMetadata` streams, the muxer auto-wraps
 * the caller's bytes in a `Metadata_AU_cell` header per ITU-T H.222.0
 * V9 § 2.12.4.2 (5 bytes prepended; PTS surfaced in the PES header).
 * For `KlvStreamType::PrivateData` streams, the caller's bytes pass
 * through unchanged.
 *
 * On a single-stream sender, prefer `tst_mux_sender_send_klv` — same
 * effect, no handle required.
 */

int tst_mux_sender_send_klv_to(struct tst_mux_sender_t *p,
                               tst_klv_stream_handle_t stream_handle,
                               const uint8_t *klv,
                               size_t len,
                               int64_t pts_90khz);

/**
 * Snapshot stats for a `tst_mux_sender_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */
 int tst_mux_sender_get_stats(struct tst_mux_sender_t *p, struct tst_mux_sender_stats_t *out);

/**
 * Read wire-level transport stats (RTT, packet loss, bandwidth, queue
 * depths) for the underlying libsrt socket. Cumulative since connect.
 *
 * `out` MUST point to a writable `TstSocketStats`; the function zeros
 * the struct on failure.
 *
 * Returns:
 * * `0` on success — `*out` is populated.
 * * `TST_E_INVALID_CONFIG` if `p` or `out` is NULL.
 * * `TST_E_NOT_AVAILABLE` if the inner transport has no live socket
 *   (closed or — for the managed sibling — mid-reconnect).
 * * `TST_E_CLOSED` if the sender has been closed.
 *
 * # Safety
 *
 * Caller MUST ensure `p` is a valid `*mut TstMuxSender` opened via
 * `tst_mux_sender_open` and `out` points to a writable `TstSocketStats`.
 */
 int tst_mux_sender_get_socket_stats(struct tst_mux_sender_t *p, struct tst_socket_stats_t *out);

/**
 * Reset stats counters for a `tst_mux_sender_t` to zero.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */
 int tst_mux_sender_reset_stats(struct tst_mux_sender_t *p);

 void tst_mux_sender_close(struct tst_mux_sender_t *p);

/**
 * Cancel a `tst_mux_sender_t`. Unblocks a thread parked in any `_send_*`
 * entry point within one libsrt I/O cycle (~3-10 ms) by closing the
 * underlying libsrt socket. Safe to call from any thread. Idempotent.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 *
 * After cancel, all `_send_*` entry points return `TST_E_CLOSED`. The
 * handle must still be `_close`'d to free.
 */
 int tst_mux_sender_cancel(struct tst_mux_sender_t *p);

/**
 * Open a `tst_managed_mux_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `tst_get_last_error_str()` describes the specific problem.
 */

struct tst_managed_mux_sender_t *tst_managed_mux_sender_open(const char *srt_url,
                                                             struct tst_mux_config_t *cfg,
                                                             const struct tst_reconnect_policy_t *policy);


int tst_managed_mux_sender_send_video(struct tst_managed_mux_sender_t *p,
                                      const uint8_t *nal,
                                      size_t len,
                                      int64_t pts_90khz,
                                      bool key_frame);


int tst_managed_mux_sender_send_klv(struct tst_managed_mux_sender_t *p,
                                    const uint8_t *klv,
                                    size_t len,
                                    int64_t pts_90khz);

/**
 * Push one Annex-B NAL targeting a specific video elementary stream on a
 * managed (auto-reconnecting) sender.
 *
 * `stream_handle` is obtained from `tst_mux_config_add_video_stream` at
 * config time and is stable across reconnects. Out-of-range handles
 * surface as `TST_E_INVALID_USAGE` (carrying
 * `MuxError::InvalidStreamHandle`).
 *
 * On a single-stream sender, prefer `tst_managed_mux_sender_send_video` —
 * same effect, no handle required.
 */

int tst_managed_mux_sender_send_video_to(struct tst_managed_mux_sender_t *p,
                                         tst_video_stream_handle_t stream_handle,
                                         const uint8_t *nal,
                                         size_t len,
                                         int64_t pts_90khz,
                                         bool key_frame);

/**
 * Push one pre-built KLV blob targeting a specific KLV elementary stream on
 * a managed (auto-reconnecting) sender.
 *
 * For `KlvStreamType::SynchronousMetadata` streams, the muxer auto-wraps
 * the caller's bytes in a `Metadata_AU_cell` header per ITU-T H.222.0
 * V9 § 2.12.4.2 (5 bytes prepended; PTS surfaced in the PES header).
 * For `KlvStreamType::PrivateData` streams, the caller's bytes pass
 * through unchanged.
 *
 * On a single-stream sender, prefer `tst_managed_mux_sender_send_klv` —
 * same effect, no handle required.
 */

int tst_managed_mux_sender_send_klv_to(struct tst_managed_mux_sender_t *p,
                                       tst_klv_stream_handle_t stream_handle,
                                       const uint8_t *klv,
                                       size_t len,
                                       int64_t pts_90khz);

/**
 * Snapshot stats for a `tst_managed_mux_sender_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */

int tst_managed_mux_sender_get_stats(struct tst_managed_mux_sender_t *p,
                                     struct tst_mux_sender_stats_t *out);

/**
 * See [`tst_mux_sender_get_socket_stats`]. The managed variant returns
 * `TST_E_NOT_AVAILABLE` whenever the reconnect loop currently has no
 * live inner socket — callers should treat this as transient and retry.
 *
 * # Safety
 *
 * Caller MUST ensure `p` is a valid `*mut TstManagedMuxSender` opened via
 * `tst_managed_mux_sender_open` and `out` points to a writable
 * `TstSocketStats`.
 */

int tst_managed_mux_sender_get_socket_stats(struct tst_managed_mux_sender_t *p,
                                            struct tst_socket_stats_t *out);

/**
 * Reset stats counters for a `tst_managed_mux_sender_t` to zero.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */
 int tst_managed_mux_sender_reset_stats(struct tst_managed_mux_sender_t *p);

 void tst_managed_mux_sender_close(struct tst_managed_mux_sender_t *p);

/**
 * Cancel a `tst_managed_mux_sender_t`. Same semantics as
 * `tst_mux_sender_cancel`; reaches the currently-active inner
 * transport's cancel handle through `ManagedTransport`'s atomic
 * snapshot.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 */
 int tst_managed_mux_sender_cancel(struct tst_managed_mux_sender_t *p);

/**
 * Open a standalone muxer. Builds the config from `cfg` so the caller may
 * free it immediately after this returns. Returns NULL on failure with
 * last-error set.
 */
 struct tst_muxer_t *tst_muxer_open(struct tst_mux_config_t *cfg);

/**
 * Push one Annex-B-framed video access unit. Returns 0 on success or a
 * negative TST_E_* code.
 */

int tst_muxer_push_video(struct tst_muxer_t *p,
                         const uint8_t *nal,
                         size_t len,
                         int64_t pts_90khz,
                         bool key_frame);

/**
 * Push one pre-built KLV blob.
 */
 int tst_muxer_push_klv(struct tst_muxer_t *p, const uint8_t *klv, size_t len, int64_t pts_90khz);

/**
 * Push one Annex-B NAL targeting a specific video elementary stream.
 *
 * `handle` is obtained from `tst_mux_config_add_video_stream` at config
 * time and is stable across managed-sender reconnects. Out-of-range
 * handles surface as `TST_E_INVALID_USAGE` (carrying
 * `MuxError::InvalidStreamHandle`).
 *
 * On a single-stream muxer, prefer `tst_muxer_push_video` — it has the
 * same effect and doesn't require a handle.
 */

int tst_muxer_push_video_to(struct tst_muxer_t *p,
                            tst_video_stream_handle_t handle,
                            const uint8_t *nal,
                            size_t len,
                            int64_t pts_90khz,
                            bool key_frame);

/**
 * Push one pre-built KLV blob targeting a specific KLV elementary stream.
 *
 * `handle` is obtained from `tst_mux_config_add_klv_stream`. Same
 * semantics as `tst_muxer_push_video_to`.
 *
 * For `KlvStreamType::SynchronousMetadata` streams, the muxer auto-wraps
 * the caller's bytes in a `Metadata_AU_cell` header per ITU-T H.222.0
 * V9 § 2.12.4.2 (5 bytes prepended; PTS surfaced in the PES header).
 * For `KlvStreamType::PrivateData` streams, the caller's bytes pass
 * through unchanged.
 */

int tst_muxer_push_klv_to(struct tst_muxer_t *p,
                          tst_klv_stream_handle_t handle,
                          const uint8_t *klv,
                          size_t len,
                          int64_t pts_90khz);

/**
 * Drain TS bytes into `out_buf` (capacity `out_cap`). Returns the number
 * of bytes written; 0 means nothing was ready or the buffer was too
 * small for the next chunk. Never sets last-error — 0 is a normal return
 * value.
 */
 size_t tst_muxer_pull(struct tst_muxer_t *p, uint8_t *out_buf, size_t out_cap);

/**
 * Snapshot stats for a `tst_muxer_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the muxer has been closed.
 */
 int tst_muxer_get_stats(struct tst_muxer_t *p, struct tst_muxer_stats_t *out);

/**
 * Reset stats counters for a `tst_muxer_t` to zero.
 *
 * Per-stream entries are preserved (identity fields remain); only flow
 * counters (`items`, `bytes`, `discontinuities`) are zeroed.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is
 * null, or `TST_E_CLOSED` if the muxer has been closed.
 */
 int tst_muxer_reset_stats(struct tst_muxer_t *p);

/**
 * Close and free the muxer. Idempotent — passing NULL is a no-op.
 */
 void tst_muxer_close(struct tst_muxer_t *p);

/**
 * Open a `tst_raw_receiver_t`. Accepts `srt://host:port?...` URLs;
 * URL with `?mode=listener` is routed through the listener path
 * (equivalent to calling `tst_raw_receiver_open_listener`).
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. `TST_E_TRANSPORT` set on connect/bind failure.
 */
 struct tst_raw_receiver_t *tst_raw_receiver_open(const char *srt_url);

/**
 * Explicit listener-mode open. Forces listener mode regardless of any
 * `?mode=` URL value — the `_listener` suffix is authoritative. URLs
 * with `?mode=caller` are accepted and silently overridden.
 *
 * Empty-host URLs like `srt://:7000` are accepted directly; the parser's
 * requirement for an explicit `?mode=listener` does not apply here because
 * the entry-point name is already the authoritative listener signal.
 *
 * (Phase 1 simplification of the design spec §4.2, which originally
 * proposed rejecting explicit `mode=caller` with `TST_E_INVALID_USAGE`.
 * The simpler rule is more forgiving and matches what most C consumers
 * expect from a `_listener`-suffixed entry point. The stricter check
 * can land in a future phase if a consumer asks.)
 */
 struct tst_raw_receiver_t *tst_raw_receiver_open_listener(const char *srt_url);

 void tst_raw_receiver_close(struct tst_raw_receiver_t *p);

/**
 * Cancel a `tst_raw_receiver_t`. Unblocks a thread parked in `_recv`
 * within one libsrt I/O cycle (~3-10 ms) by closing the underlying
 * libsrt socket. Safe to call from any thread. Idempotent.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 *
 * After cancel, `_recv` returns `TST_E_CLOSED` (not `TST_E_END_OF_STREAM`).
 * The handle must still be `_close`'d to free.
 */
 int tst_raw_receiver_cancel(struct tst_raw_receiver_t *p);

/**
 * Snapshot stats for a `tst_raw_receiver_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the receiver has been closed.
 */
 int tst_raw_receiver_get_stats(struct tst_raw_receiver_t *p, struct tst_raw_receiver_stats_t *out);

/**
 * Reset stats counters for a `tst_raw_receiver_t` to zero.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null,
 * or `TST_E_CLOSED` if the receiver has been closed.
 */
 int tst_raw_receiver_reset_stats(struct tst_raw_receiver_t *p);

/**
 * Block until one message arrives. Copies up to `len` bytes into `buf`
 * and writes the actual length to `*out_len`.
 *
 * Returns:
 * - 0 on success (`*out_len` set to bytes received; ≤ `len`)
 * - `TST_E_END_OF_STREAM` (-12) on graceful peer close
 * - `TST_E_CLOSED` (-7) if the handle was `_cancel`'d or `_close`'d
 * - `TST_E_TRANSPORT` (-8) on a transport failure other than a clean
 *   peer disconnect (peer FIN surfaces as `TST_E_END_OF_STREAM`; see
 *   the `TransportError::Broken` arm in this function for details)
 * - `TST_E_TOO_LARGE` (-6) if the inbound message exceeds `len`
 *   (`*out_len` is left unmodified)
 * - `TST_E_INVALID_CONFIG` (-1) on null pointer arguments
 */
 int tst_raw_receiver_recv(struct tst_raw_receiver_t *p, uint8_t *buf, size_t len, size_t *out_len);

/**
 * Open a `tst_managed_raw_receiver_t`. URL-driven mode dispatch
 * matches `tst_raw_receiver_open` semantics: `?mode=listener` routes
 * to the listener path, otherwise caller mode.
 *
 * On transport failure the managed wrapper automatically reconnects
 * (or re-binds for listener mode) according to `policy`. Pass `NULL`
 * for `policy` to use the default reconnect policy.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL. `TST_E_TRANSPORT` set on the
 * initial connect/bind failure.
 */

struct tst_managed_raw_receiver_t *tst_managed_raw_receiver_open(const char *srt_url,
                                                                 const struct tst_reconnect_policy_t *policy);

/**
 * Explicit listener-mode open for the managed receiver. Forces
 * listener mode regardless of any `?mode=` URL value — the
 * `_listener` suffix is authoritative. On peer disconnect the managed
 * wrapper re-binds a fresh listener socket and accepts the next
 * incoming connection. Note: the re-bind + re-accept may block
 * significantly between attempts depending on the reconnect policy.
 *
 * Empty-host URLs like `srt://:7000` are accepted directly; the parser's
 * requirement for an explicit `?mode=listener` does not apply here because
 * the entry-point name is already the authoritative listener signal.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set for malformed URLs
 * or `TST_E_TRANSPORT` on the initial bind/accept failure.
 */

struct tst_managed_raw_receiver_t *tst_managed_raw_receiver_open_listener(const char *srt_url,
                                                                          const struct tst_reconnect_policy_t *policy);

/**
 * Block until one message arrives. Semantics match `tst_raw_receiver_recv`;
 * on transport failure the managed inner reconnects transparently before
 * returning an error only once the retry budget is exhausted.
 *
 * # Asymmetry with `tst_raw_receiver_recv`
 *
 * The plain `tst_raw_receiver_recv` maps `TransportError::Broken` on
 * a non-cancelled handle to `TST_E_END_OF_STREAM` (peer disconnect at
 * the bare-transport layer is semantically end-of-stream). The managed
 * version does NOT apply that mapping: `ManagedReceiveTransport`
 * already retries internally on Broken, so a Broken that reaches this
 * function means all reconnect attempts have been exhausted — that is
 * a hard transport failure (`TST_E_TRANSPORT`), not an end-of-stream.
 */

int tst_managed_raw_receiver_recv(struct tst_managed_raw_receiver_t *p,
                                  uint8_t *buf,
                                  size_t len,
                                  size_t *out_len);

/**
 * Cancel a `tst_managed_raw_receiver_t`. Unblocks a thread parked in
 * `_recv` within one libsrt I/O cycle (~3-10 ms). Safe from any thread.
 * Idempotent. After cancel, `_recv` returns `TST_E_CLOSED`. The handle
 * must still be `_close`'d to free memory.
 */
 int tst_managed_raw_receiver_cancel(struct tst_managed_raw_receiver_t *p);

 void tst_managed_raw_receiver_close(struct tst_managed_raw_receiver_t *p);

/**
 * Snapshot stats for a `tst_managed_raw_receiver_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the receiver has been closed.
 */

int tst_managed_raw_receiver_get_stats(struct tst_managed_raw_receiver_t *p,
                                       struct tst_raw_receiver_stats_t *out);

/**
 * Reset stats counters for a `tst_managed_raw_receiver_t` to zero.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null,
 * or `TST_E_CLOSED` if the receiver has been closed.
 */
 int tst_managed_raw_receiver_reset_stats(struct tst_managed_raw_receiver_t *p);

/**
 * Open a `tst_raw_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `tst_get_last_error_str()` describes the specific problem.
 */

struct tst_raw_sender_t *tst_raw_sender_open(const char *srt_url,
                                             const struct tst_raw_sender_config_t *cfg);

 int tst_raw_sender_send(struct tst_raw_sender_t *p, const uint8_t *bytes, size_t len);

 void tst_raw_sender_close(struct tst_raw_sender_t *p);

/**
 * Cancel a `tst_raw_sender_t`. Unblocks a thread parked in `_send`
 * within one libsrt I/O cycle (~3-10 ms) by closing the underlying
 * libsrt socket. Safe to call from any thread. Idempotent.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 *
 * After cancel, `_send` returns `TST_E_CLOSED`. The handle must still
 * be `_close`'d to free.
 */
 int tst_raw_sender_cancel(struct tst_raw_sender_t *p);

/**
 * Open a `tst_managed_raw_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `tst_get_last_error_str()` describes the specific problem.
 */

struct tst_managed_raw_sender_t *tst_managed_raw_sender_open(const char *srt_url,
                                                             const struct tst_raw_sender_config_t *cfg,
                                                             const struct tst_reconnect_policy_t *policy);


int tst_managed_raw_sender_send(struct tst_managed_raw_sender_t *p,
                                const uint8_t *bytes,
                                size_t len);

 void tst_managed_raw_sender_close(struct tst_managed_raw_sender_t *p);

/**
 * Cancel a `tst_managed_raw_sender_t`. Same semantics as
 * `tst_raw_sender_cancel`; reaches the currently-active inner
 * transport's cancel handle through `ManagedTransport`'s atomic
 * snapshot.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 */
 int tst_managed_raw_sender_cancel(struct tst_managed_raw_sender_t *p);

/**
 * Snapshot stats for a `tst_raw_sender_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */
 int tst_raw_sender_get_stats(struct tst_raw_sender_t *p, struct tst_raw_sender_stats_t *out);

/**
 * Read wire-level transport stats for the underlying libsrt socket.
 * See [`tst_mux_sender_get_socket_stats`](crate::mux_sender::tst_mux_sender_get_socket_stats)
 * for full semantics — same shape, different handle type.
 *
 * # Safety
 *
 * Caller MUST ensure `p` is a valid `*mut TstRawSender` opened via
 * `tst_raw_sender_open` and `out` points to a writable `TstSocketStats`.
 */
 int tst_raw_sender_get_socket_stats(struct tst_raw_sender_t *p, struct tst_socket_stats_t *out);

/**
 * Reset stats counters for a `tst_raw_sender_t` to zero.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */
 int tst_raw_sender_reset_stats(struct tst_raw_sender_t *p);

/**
 * Snapshot stats for a `tst_managed_raw_sender_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */

int tst_managed_raw_sender_get_stats(struct tst_managed_raw_sender_t *p,
                                     struct tst_raw_sender_stats_t *out);

/**
 * Managed sibling of [`tst_raw_sender_get_socket_stats`]. Returns
 * `TST_E_NOT_AVAILABLE` when the reconnect loop currently has no live
 * inner socket.
 *
 * # Safety
 *
 * Caller MUST ensure `p` is a valid `*mut TstManagedRawSender` opened
 * via `tst_managed_raw_sender_open` and `out` points to a writable
 * `TstSocketStats`.
 */

int tst_managed_raw_sender_get_socket_stats(struct tst_managed_raw_sender_t *p,
                                            struct tst_socket_stats_t *out);

/**
 * Reset stats counters for a `tst_managed_raw_sender_t` to zero.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */
 int tst_managed_raw_sender_reset_stats(struct tst_managed_raw_sender_t *p);

/**
 * Open a `tst_receiver_t`. Accepts `srt://host:port?...` URLs;
 * URL with `?mode=listener` is routed through the listener path
 * (equivalent to calling `tst_receiver_open_listener`).
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. `TST_E_TRANSPORT` set on connect/bind failure.
 */
 struct tst_receiver_t *tst_receiver_open(const char *srt_url);

/**
 * Explicit listener-mode open. Forces listener mode regardless of any
 * `?mode=` URL value — the `_listener` suffix is authoritative. URLs
 * with `?mode=caller` are accepted and silently overridden.
 *
 * Empty-host URLs like `srt://:7000` are accepted directly; the parser's
 * requirement for an explicit `?mode=listener` does not apply here because
 * the entry-point name is already the authoritative listener signal.
 */
 struct tst_receiver_t *tst_receiver_open_listener(const char *srt_url);

 void tst_receiver_close(struct tst_receiver_t *p);

/**
 * Block until one 188-byte MPEG-TS packet is ready, then copy it into
 * the caller's `out_packet` buffer.
 *
 * `out_packet` MUST point to a buffer of at least 188 bytes (a
 * `uint8_t[188]` array on the C side). The pointer is dereferenced
 * once on success; no allocation crosses the FFI boundary.
 *
 * Returns:
 * - `0` on success (188 bytes written to `out_packet`)
 * - `TST_E_END_OF_STREAM` (-12) on graceful peer close
 * - `TST_E_CLOSED` (-7) if the handle was `_cancel`'d or `_close`'d
 * - `TST_E_TRANSPORT` (-8) on a transport failure other than a clean
 *   peer disconnect (peer FIN surfaces as `TST_E_END_OF_STREAM`; see
 *   the `TransportError::Broken` arm in this function for details)
 * - `TST_E_INVALID_CONFIG` (-1) on null pointer arguments
 *
 * On any non-zero return the contents of `out_packet` are unspecified.
 */
 int tst_receiver_recv_packet(struct tst_receiver_t *p, uint8_t *out_packet);

/**
 * Cancel a `tst_receiver_t`. Unblocks a thread parked in
 * `_recv_packet` within one libsrt I/O cycle (~3-10 ms) by closing
 * the underlying libsrt socket. Safe to call from any thread.
 * Idempotent.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 *
 * After cancel, `_recv_packet` returns `TST_E_CLOSED` (not
 * `TST_E_END_OF_STREAM`). The handle must still be `_close`'d to free.
 */
 int tst_receiver_cancel(struct tst_receiver_t *p);

/**
 * Snapshot stats for a `tst_receiver_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the receiver has been closed.
 */
 int tst_receiver_get_stats(struct tst_receiver_t *p, struct tst_receiver_stats_t *out);

/**
 * Read wire-level transport stats for the underlying libsrt socket.
 * See [`tst_mux_sender_get_socket_stats`](crate::mux_sender::tst_mux_sender_get_socket_stats)
 * for full semantics — same shape, different handle type.
 *
 * # Safety
 *
 * Caller MUST ensure `p` is a valid `*mut TstReceiver` opened via
 * `tst_receiver_open` and `out` points to a writable `TstSocketStats`.
 */
 int tst_receiver_get_socket_stats(struct tst_receiver_t *p, struct tst_socket_stats_t *out);

/**
 * Reset stats counters for a `tst_receiver_t` to zero. Does not
 * affect transport state or the syncer state machine.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null,
 * or `TST_E_CLOSED` if the receiver has been closed.
 */
 int tst_receiver_reset_stats(struct tst_receiver_t *p);

/**
 * Open a `tst_managed_receiver_t`. URL-driven mode dispatch
 * matches `tst_receiver_open` semantics: `?mode=listener` routes
 * to the listener path, otherwise caller mode.
 *
 * On transport failure the managed wrapper automatically reconnects
 * (or re-binds for listener mode) according to `policy`. Pass `NULL`
 * for `policy` to use the default reconnect policy.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL. `TST_E_TRANSPORT` set on the
 * initial connect/bind failure.
 */

struct tst_managed_receiver_t *tst_managed_receiver_open(const char *srt_url,
                                                         const struct tst_reconnect_policy_t *policy);

/**
 * Explicit listener-mode open for the managed receiver. Forces
 * listener mode regardless of any `?mode=` URL value — the
 * `_listener` suffix is authoritative. On peer disconnect the managed
 * wrapper re-binds a fresh listener socket and accepts the next
 * incoming connection. Note: the re-bind + re-accept may block
 * significantly between attempts depending on the reconnect policy.
 *
 * Empty-host URLs like `srt://:7000` are accepted directly; the parser's
 * requirement for an explicit `?mode=listener` does not apply here because
 * the entry-point name is already the authoritative listener signal.
 */

struct tst_managed_receiver_t *tst_managed_receiver_open_listener(const char *srt_url,
                                                                  const struct tst_reconnect_policy_t *policy);

/**
 * Block until one 188-byte MPEG-TS packet is ready. Semantics match
 * `tst_receiver_recv_packet`; on transport failure the managed
 * inner reconnects transparently before returning an error only once
 * the retry budget is exhausted.
 *
 * # Asymmetry with `tst_receiver_recv_packet`
 *
 * The plain `tst_receiver_recv_packet` maps `TransportError::Broken`
 * on a non-cancelled handle to `TST_E_END_OF_STREAM` (peer disconnect at
 * the bare-transport layer is semantically end-of-stream). The managed
 * version does NOT apply that mapping: `ManagedReceiveTransport`
 * already retries internally on Broken, so a Broken that reaches this
 * function means all reconnect attempts have been exhausted — that is
 * a hard transport failure (`TST_E_TRANSPORT`), not an end-of-stream.
 */
 int tst_managed_receiver_recv_packet(struct tst_managed_receiver_t *p, uint8_t *out_packet);

/**
 * Cancel a `tst_managed_receiver_t`. Unblocks a thread parked in
 * `_recv_packet` within one libsrt I/O cycle (~3-10 ms). Safe from
 * any thread. Idempotent. After cancel, `_recv_packet` returns
 * `TST_E_CLOSED`. The handle must still be `_close`'d to free memory.
 */
 int tst_managed_receiver_cancel(struct tst_managed_receiver_t *p);

 void tst_managed_receiver_close(struct tst_managed_receiver_t *p);

/**
 * Snapshot stats for a `tst_managed_receiver_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the receiver has been closed.
 */

int tst_managed_receiver_get_stats(struct tst_managed_receiver_t *p,
                                   struct tst_receiver_stats_t *out);

/**
 * Managed sibling of [`tst_receiver_get_socket_stats`]. Returns
 * `TST_E_NOT_AVAILABLE` when the reconnect loop currently has no live
 * inner socket.
 *
 * # Safety
 *
 * Caller MUST ensure `p` is a valid `*mut TstManagedReceiver` opened via
 * `tst_managed_receiver_open` and `out` points to a writable
 * `TstSocketStats`.
 */

int tst_managed_receiver_get_socket_stats(struct tst_managed_receiver_t *p,
                                          struct tst_socket_stats_t *out);

/**
 * Reset stats counters for a `tst_managed_receiver_t` to zero.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null,
 * or `TST_E_CLOSED` if the receiver has been closed.
 */
 int tst_managed_receiver_reset_stats(struct tst_managed_receiver_t *p);

/**
 * Open a `tst_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `tst_get_last_error_str()` describes the specific problem.
 */
 struct tst_sender_t *tst_sender_open(const char *srt_url, const struct tst_sender_config_t *cfg);

 int tst_sender_send_ts(struct tst_sender_t *p, const uint8_t *bytes, size_t len);

 int tst_sender_flush(struct tst_sender_t *p);

 int tst_sender_get_stats(struct tst_sender_t *p, struct tst_sender_stats_t *out);

/**
 * Read wire-level transport stats for the underlying libsrt socket.
 * See [`tst_mux_sender_get_socket_stats`](crate::mux_sender::tst_mux_sender_get_socket_stats)
 * for full semantics — same shape, different handle type.
 *
 * # Safety
 *
 * Caller MUST ensure `p` is a valid `*mut TstSender` opened via
 * `tst_sender_open` and `out` points to a writable `TstSocketStats`.
 */
 int tst_sender_get_socket_stats(struct tst_sender_t *p, struct tst_socket_stats_t *out);

 int tst_sender_reset_stats(struct tst_sender_t *p);

 void tst_sender_close(struct tst_sender_t *p);

/**
 * Cancel a `tst_sender_t`. Unblocks a thread parked in `_send`
 * within one libsrt I/O cycle (~3-10 ms) by closing the underlying
 * libsrt socket. Safe to call from any thread. Idempotent.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 *
 * After cancel, `_send` returns `TST_E_CLOSED`. The handle must still
 * be `_close`'d to free.
 */
 int tst_sender_cancel(struct tst_sender_t *p);

/**
 * Open a `tst_managed_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `tst_get_last_error_str()` describes the specific problem.
 */

struct tst_managed_sender_t *tst_managed_sender_open(const char *srt_url,
                                                     const struct tst_sender_config_t *cfg,
                                                     const struct tst_reconnect_policy_t *policy);

 int tst_managed_sender_send_ts(struct tst_managed_sender_t *p, const uint8_t *bytes, size_t len);

 int tst_managed_sender_flush(struct tst_managed_sender_t *p);

 int tst_managed_sender_get_stats(struct tst_managed_sender_t *p, struct tst_sender_stats_t *out);

/**
 * Managed sibling of [`tst_sender_get_socket_stats`]. Returns
 * `TST_E_NOT_AVAILABLE` when the reconnect loop currently has no live
 * inner socket.
 *
 * # Safety
 *
 * Caller MUST ensure `p` is a valid `*mut TstManagedSender` opened via
 * `tst_managed_sender_open` and `out` points to a writable
 * `TstSocketStats`.
 */

int tst_managed_sender_get_socket_stats(struct tst_managed_sender_t *p,
                                        struct tst_socket_stats_t *out);

 int tst_managed_sender_reset_stats(struct tst_managed_sender_t *p);

 void tst_managed_sender_close(struct tst_managed_sender_t *p);

/**
 * Cancel a `tst_managed_sender_t`. Same semantics as
 * `tst_sender_cancel`; reaches the currently-active inner
 * transport's cancel handle through `ManagedTransport`'s atomic
 * snapshot.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 */
 int tst_managed_sender_cancel(struct tst_managed_sender_t *p);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TSTRANS_H */

/* Phase 3 ABI layout guards — trip the C compiler at consumer-build
 * time if the Rust-side struct sizes drift from their Phase 3 baseline.
 * Layouts are pinned in `crates/tst-c/src/event.rs` via const-assertion
 * blocks on the Rust side; this duplicates the guard on the C side so
 * consumers building against an upgraded libtstrans see the mismatch
 * immediately.
 */
#if !defined(TST_SKIP_ABI_ASSERTS) && !defined(_TST_ABI_ASSERTS_DONE)
#define _TST_ABI_ASSERTS_DONE
#define _TST_ABI_ASSERT(c, msg) _Static_assert((c), msg)
_TST_ABI_ASSERT(sizeof(tst_nal_t)                  == 24, "tst_nal_t size drift");
_TST_ABI_ASSERT(sizeof(tst_obu_t)                  == 24, "tst_obu_t size drift");
_TST_ABI_ASSERT(sizeof(tst_descriptor_t)           == 24, "tst_descriptor_t size drift");
_TST_ABI_ASSERT(sizeof(tst_stream_info_t)          == 40, "tst_stream_info_t size drift");
_TST_ABI_ASSERT(sizeof(tst_klv_link_t)             ==  8, "tst_klv_link_t size drift");
_TST_ABI_ASSERT(sizeof(tst_demux_receiver_stats_t) == 48, "tst_demux_receiver_stats_t size drift");
_TST_ABI_ASSERT(sizeof(tst_event_t)               <= 256, "tst_event_t exceeds 256 B");
#endif
