/*
 * tstrans.h — C ABI for ts-transformer (mpeg-ts + KLV + SRT).
 *
 * This file is GENERATED by cbindgen. Do not edit manually.
 * Source of truth: crates/tst-c/src/ (Rust).
 *
 * Copyright (c) 2026 Andrew Klofas. Licensed under MIT OR Apache-2.0.
 */


#ifndef TSTRANS_H
#define TSTRANS_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>

/**
 * Major version (compile-time macro in the generated header).
 */
#define TST_VERSION_MAJOR 0

/**
 * Minor version.
 */
#define TST_VERSION_MINOR 1

/**
 * Patch version.
 */
#define TST_VERSION_PATCH 0

/**
 * Sentinel returned by `tst_mux_config_add_*_stream` on failure.
 * On failure, the last-error is also populated; check
 * `tst_get_last_error()` for the negative `TST_E_*` code.
 */
#define TST_INVALID_STREAM_HANDLE UINT32_MAX

/**
 * Maximum number of per-stream entries in any stats struct exposed at
 * the C ABI. Rarely exceeded — multi-stream `mpegts::mux` caps at
 * 16 video + 16 KLV = 32, leaving 32 slots of headroom for receiver
 * PSI + observed streams.
 */
#define TST_STATS_MAX_STREAMS 64

enum tst_video_codec
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  TST_VIDEO_CODEC_H264 = 0,
  TST_VIDEO_CODEC_H265 = 1,
  TST_VIDEO_CODEC_H266 = 2,
  TST_VIDEO_CODEC_AV1 = 3,
};
#ifndef __cplusplus
typedef int32_t tst_video_codec;
#endif // __cplusplus

typedef enum tst_klv_stream_type {
  TST_KLV_STREAM_TYPE_PRIVATE_DATA = 0,
  TST_KLV_STREAM_TYPE_SYNCHRONOUS_METADATA = 1,
} tst_klv_stream_type;

typedef enum tst_ts_framing_mode {
  TST_TS_FRAMING_MODE_RECOVER = 0,
  TST_TS_FRAMING_MODE_STRICT = 1,
} tst_ts_framing_mode;

typedef enum tst_overflow_policy {
  TST_OVERFLOW_POLICY_DROP_OLDEST = 0,
  TST_OVERFLOW_POLICY_REJECT = 1,
} tst_overflow_policy;

/**
 * Negative codes returned by every fallible tst-c entry point.
 *
 * `Success = 0` is the only non-negative variant. Codes are stable
 * across tst-c versions; new codes append at the end.
 */
enum tst_e
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  TST_E_SUCCESS = 0,
  TST_E_INVALID_CONFIG = -1,
  TST_E_INVALID_NAL = -2,
  TST_E_INVALID_TS = -3,
  TST_E_BUFFER_FULL = -4,
  TST_E_KLV_TOO_LARGE = -5,
  TST_E_TOO_LARGE = -6,
  TST_E_CLOSED = -7,
  TST_E_TRANSPORT = -8,
  TST_E_INVALID_USAGE = -9,
  TST_E_INTERNAL = -10,
  /**
   * Internal panic caught at the FFI boundary; the handle is now in
   * an indeterminate state. Subsequent calls on the same handle will
   * also fail (returning `Closed`). The caller should free the handle.
   */
  TST_E_PANIC_CAUGHT = -11,
  /**
   * Peer disconnected gracefully (received TCP-style FIN / SRT clean close).
   * Distinguished from `Closed` (caller-side cancel/close) so receive loops
   * can branch on the shutdown reason. After this code the handle is dead;
   * subsequent calls return `Closed`.
   */
  TST_E_END_OF_STREAM = -12,
};
#ifndef __cplusplus
typedef int32_t tst_e;
#endif // __cplusplus

/**
 * Opaque demux-config builder. Heap-allocated via `_new`, mutated
 * in place via setters, released via `_free`. The receiver clones
 * what it needs at `_open_with_config` time; the caller still owns
 * the builder.
 *
 * Lifecycle mirrors `tst_mux_config_t` from plan #14 exactly.
 */
typedef struct TstDemuxConfig TstDemuxConfig;

typedef struct tst_managed_mux_sender_t tst_managed_mux_sender_t;

typedef struct tst_managed_raw_receiver_t tst_managed_raw_receiver_t;

typedef struct tst_managed_raw_sender_t tst_managed_raw_sender_t;

typedef struct tst_managed_receiver_t tst_managed_receiver_t;

typedef struct tst_managed_sender_t tst_managed_sender_t;

/**
 * Opaque mux-config builder. Constructed via `tst_mux_config_new`,
 * populated via `tst_mux_config_add_program` + stream-add / descriptor-set
 * entry points, then consumed by `tst_*_open` (which clones the inner).
 * Caller is responsible for calling `tst_mux_config_free`.
 *
 * Unlike the pre-multi-program API, the config starts **empty** — no program
 * is pre-created. The caller must call `tst_mux_config_add_program` at
 * least once before opening a muxer or sender.
 */
typedef struct tst_mux_config_t tst_mux_config_t;

typedef struct tst_mux_sender_t tst_mux_sender_t;

typedef struct tst_muxer_t tst_muxer_t;

typedef struct tst_raw_receiver_t tst_raw_receiver_t;

typedef struct tst_raw_sender_t tst_raw_sender_t;

typedef struct tst_raw_sender_config_t tst_raw_sender_config_t;

typedef struct tst_receiver_t tst_receiver_t;

typedef struct tst_reconnect_policy_t tst_reconnect_policy_t;

typedef struct tst_sender_t tst_sender_t;

typedef struct tst_sender_config_t tst_sender_config_t;

/**
 * Opaque handle returned by `tst_mux_config_add_program`. Used as an
 * argument to subsequent stream-add and config-set entry points to
 * disambiguate which program's streams or descriptors are being modified.
 *
 * The value is a zero-based index into the program list. Programs are
 * numbered in the order they were added. Handles are stable across the
 * config→open boundary — the same index applies after `tst_muxer_open`.
 */
typedef uint32_t tst_program_handle_t;

/**
 * Opaque per-program ordinal for a video elementary stream. Obtained from
 * `tst_mux_config_add_video_stream` at config time and reused with the
 * `_video_to` push siblings on every muxer-owning C variant.
 *
 * Handles are stable across the config→open boundary and across managed
 * reconnects. They encode `(program_index, within_program_index)` as a
 * packed `u32` (bits 4..=7 = program, bits 0..=3 = within). They are NOT
 * interchangeable between muxers.
 */
typedef uint32_t tst_video_stream_handle_t;

/**
 * Opaque per-program ordinal for a KLV elementary stream. Same packed
 * encoding as [`TstVideoStreamHandle`].
 */
typedef uint32_t tst_klv_stream_handle_t;

/**
 * `repr(C)` mirror of `tst_core::mpegts::StreamStats`. Size 96 B.
 *
 * Layout (offsets):
 *   0: items (u64, 8 B)
 *   8: bytes (u64, 8 B)
 *  16: discontinuities (u64, 8 B)
 *  24: pid (u16, 2 B)
 *  26: stream_type (u8, 1 B)
 *  27: _pad (3 B, alignment bridge)
 *  30: program_number (u16, 2 B)
 *  32: label ([c_char; 64], 64 B)
 * Total: 96 B — identical to the pre-program_number layout.
 */
typedef struct tst_stream_stats_t {
  uint64_t items;
  uint64_t bytes;
  uint64_t discontinuities;
  uint16_t pid;
  uint8_t stream_type;
  /**
   * Alignment padding bridging stream_type → program_number.
   */
  uint8_t _pad[3];
  /**
   * Program number from the PAT that owns this stream. 0 for PSI PIDs.
   */
  uint16_t program_number;
  /**
   * NUL-terminated UTF-8. `label[0]==0` means None. Truncated at 63
   * bytes (first 63 + NUL).
   */
  char label[64];
} tst_stream_stats_t;

/**
 * `repr(C)` mirror of `tst_pipeline::MuxSenderStats`. Size 6188 B.
 */
typedef struct tst_mux_sender_stats_t {
  uint64_t bytes_sent;
  uint64_t packets_sent;
  uint64_t pending_bytes_queued;
  uint64_t pending_chunks_queued;
  /**
   * Number of programs (PAT entries) in the muxer configuration.
   */
  uint32_t programs_configured;
  uint32_t per_stream_count;
  uint32_t per_stream_truncated;
  struct tst_stream_stats_t per_stream[TST_STATS_MAX_STREAMS];
} tst_mux_sender_stats_t;

/**
 * `repr(C)` mirror of `tst_core::mpegts::mux::MuxerStats`. Size 6172 B.
 */
typedef struct tst_muxer_stats_t {
  uint64_t ts_packets_emitted;
  uint64_t ts_bytes_emitted;
  /**
   * Number of programs (PAT entries) in this muxer's configuration.
   */
  uint32_t programs_configured;
  uint32_t per_stream_count;
  uint32_t per_stream_truncated;
  struct tst_stream_stats_t per_stream[TST_STATS_MAX_STREAMS];
} tst_muxer_stats_t;

/**
 * `repr(C)` mirror of `tst_pipeline::RawReceiverStats`. Size 16 B.
 */
typedef struct tst_raw_receiver_stats_t {
  uint64_t bytes_received;
  uint64_t packets_received;
} tst_raw_receiver_stats_t;

/**
 * `repr(C)` mirror of `tst_pipeline::RawSenderStats`. Size 16 B.
 */
typedef struct tst_raw_sender_stats_t {
  uint64_t bytes_sent;
  uint64_t packets_sent;
} tst_raw_sender_stats_t;

/**
 * `repr(C)` mirror of `tst_pipeline::ReceiverStats`. Size 32 B.
 *
 * Application-level counters for the TS-aligned receive shell. Mirrors
 * the layout of `tst_pipeline::ReceiverStats`:
 * * `bytes_received` / `packets_received` — application-level totals
 *   (one 188-byte packet per `_recv_packet` success).
 * * `bytes_skipped_for_sync` / `resync_events` — sync-recovery state
 *   from the underlying `tst_pipeline::receiver::sync::Syncer`. Non-zero
 *   `resync_events` indicates the syncer hit HUNT/VERIFY mid-stream
 *   (either initial lock-on or re-lock after corruption).
 */
typedef struct tst_receiver_stats_t {
  uint64_t bytes_received;
  uint64_t bytes_skipped_for_sync;
  uint64_t resync_events;
  uint64_t packets_received;
} tst_receiver_stats_t;

/**
 * Public-ABI mirror of `tst_pipeline::SenderStats`. Same fields,
 * same units. Caller passes a pointer to a stack-allocated struct;
 * `tst_sender_get_stats` fills it in.
 */
typedef struct tst_sender_stats_t {
  uint64_t bytes_pushed;
  uint64_t bytes_skipped_for_sync;
  uint64_t resync_events;
  uint64_t packets_sent;
} tst_sender_stats_t;

/**
 * Sentinel returned by `tst_mux_config_add_program` on failure (null cfg
 * or other hard error). Check `tst_get_last_error()` for the reason.
 */
#define TST_INVALID_PROGRAM_HANDLE UINT32_MAX

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new, empty mux config. No programs are added — call
 * `tst_mux_config_add_program` before using this config to open a muxer
 * or sender. Returns NULL only on allocation failure (OOM).
 */
 struct tst_mux_config_t *tst_mux_config_new(void);

/**
 * Free a mux config previously returned by `tst_mux_config_new`. No-op on
 * NULL. The config must not be used after this call.
 */
 void tst_mux_config_free(struct tst_mux_config_t *p);

/**
 * Begin a new program in this multiplex. Returns a handle used as the
 * `program` argument to subsequent stream-add and descriptor-set entry
 * points. Programs are numbered in insertion order starting at 0.
 *
 * `program_number` is the PAT program_number field (must be > 0 and unique
 * within the config). `pmt_pid` is the PID on which this program's PMT will
 * be carried (must be unique within the config and not collide with any
 * stream PID).
 *
 * Returns `TST_INVALID_PROGRAM_HANDLE` and sets last-error on null `cfg`.
 * Validation (duplicate program_number, colliding PMT PID, etc.) is deferred
 * to `tst_muxer_open` / `tst_*_sender_open` time.
 */

tst_program_handle_t tst_mux_config_add_program(struct tst_mux_config_t *cfg,
                                                uint16_t program_number,
                                                uint16_t pmt_pid);

/**
 * Add a video elementary stream to the specified program and return its
 * handle.
 *
 * The returned `tst_video_stream_handle_t` is stable across the config→open
 * boundary and across managed-sender reconnects. Pass it to
 * `tst_muxer_push_video_to` / `tst_mux_sender_send_video_to` /
 * `tst_managed_mux_sender_send_video_to` to fan out to this specific stream.
 *
 * Returns `TST_INVALID_STREAM_HANDLE` and sets last-error on: null `cfg`,
 * invalid `program` handle, or per-program stream cap exceeded (>16 streams
 * of any kind per program). Hard validation errors surface at `_open` time.
 */

tst_video_stream_handle_t tst_mux_config_add_video_stream(struct tst_mux_config_t *cfg,
                                                          tst_program_handle_t program,
                                                          uint16_t pid,
                                                          tst_video_codec codec);

/**
 * Add a KLV elementary stream to the specified program and return its handle.
 *
 * `stream_type`: `TST_KLV_STREAM_TYPE_PRIVATE_DATA` (0x06, async — no AU
 * cell wrapping) or `TST_KLV_STREAM_TYPE_SYNCHRONOUS_METADATA` (0x15 —
 * the muxer auto-wraps each push in a 5-byte `Metadata_AU_cell` header
 * per ITU-T H.222.0 V9 § 2.12.4.2 before TS-framing; pass raw KLV LS
 * bytes to `push_klv_to`).
 *
 * `carries_pts`: set `true` for synchronous KLV (PTS carried in PES header),
 * `false` for async KLV.
 *
 * Returns `TST_INVALID_STREAM_HANDLE` on error (same conditions as
 * `tst_mux_config_add_video_stream`).
 */

tst_klv_stream_handle_t tst_mux_config_add_klv_stream(struct tst_mux_config_t *cfg,
                                                      tst_program_handle_t program,
                                                      uint16_t pid,
                                                      enum tst_klv_stream_type stream_type,
                                                      bool carries_pts);

/**
 * Pin the PCR PID for the specified program. By default the muxer uses the
 * first video stream's PID (or first KLV PID for KLV-only programs).
 *
 * Returns 0 on success, or a negative `TST_E_*` code on null pointer or
 * invalid program handle.
 */

int tst_mux_config_set_pcr_pid(struct tst_mux_config_t *cfg,
                               tst_program_handle_t program,
                               uint16_t pid);

/**
 * Set the PCR re-emission interval for this mux config (applies to all
 * programs). Default is 40 ms. Must be in range 1..=100.
 */
 int tst_mux_config_set_pcr_interval_ms(struct tst_mux_config_t *p, uint32_t ms);

/**
 * Set the PAT/PMT re-emission interval for this mux config. Default 100 ms.
 * Must be >= 10.
 */
 int tst_mux_config_set_psi_interval_ms(struct tst_mux_config_t *p, uint32_t ms);

/**
 * Set the TS-packet output buffer capacity. Default 10000 (~1.88 MB).
 * Must be >= 10.
 */
 int tst_mux_config_set_buffer_packets(struct tst_mux_config_t *p, size_t n);

/**
 * Set program-level PMT descriptors for the specified program.
 *
 * `tlv_bytes` points to the concatenation of `tlv_count` TLV triples,
 * totalling `tlv_total_len` bytes. Each TLV has the layout:
 *   byte 0: tag
 *   byte 1: length of body (N)
 *   bytes 2..2+N: body
 *
 * Calling with `tlv_total_len == 0` or `tlv_count == 0` clears any
 * previously set program descriptors for this program.
 *
 * Returns 0 on success or a negative `TST_E_*` code on: null `cfg`,
 * null `tlv_bytes` with non-zero count, invalid program handle, or a
 * malformed TLV byte stream (truncated length or body).
 */

int tst_mux_config_set_program_descriptors(struct tst_mux_config_t *cfg,
                                           tst_program_handle_t program,
                                           const uint8_t *tlv_bytes,
                                           size_t tlv_total_len,
                                           size_t tlv_count);

/**
 * Set per-stream PMT descriptors for the specified video stream.
 *
 * `video` is a handle previously returned by `tst_mux_config_add_video_stream`.
 * The TLV byte format is the same as `tst_mux_config_set_program_descriptors`.
 *
 * Calling with `tlv_total_len == 0` or `tlv_count == 0` clears any
 * previously set stream descriptors for this stream.
 *
 * Returns 0 on success or a negative `TST_E_*` code on: null `cfg`,
 * invalid handle, null `tlv_bytes` with non-zero count, or malformed TLV.
 */

int tst_mux_config_set_stream_descriptors_for_video(struct tst_mux_config_t *cfg,
                                                    tst_video_stream_handle_t video,
                                                    const uint8_t *tlv_bytes,
                                                    size_t tlv_total_len,
                                                    size_t tlv_count);

/**
 * Set per-stream PMT descriptors for the specified KLV stream.
 *
 * `klv` is a handle previously returned by `tst_mux_config_add_klv_stream`.
 * The TLV byte format is the same as `tst_mux_config_set_program_descriptors`.
 *
 * Returns 0 on success or a negative `TST_E_*` code on the same conditions
 * as `tst_mux_config_set_stream_descriptors_for_video`.
 */

int tst_mux_config_set_stream_descriptors_for_klv(struct tst_mux_config_t *cfg,
                                                  tst_klv_stream_handle_t klv,
                                                  const uint8_t *tlv_bytes,
                                                  size_t tlv_total_len,
                                                  size_t tlv_count);

 struct tst_sender_config_t *tst_sender_config_new(void);

 void tst_sender_config_free(struct tst_sender_config_t *p);


int tst_sender_config_set_framing_mode(struct tst_sender_config_t *p,
                                       enum tst_ts_framing_mode mode);

 int tst_sender_config_set_max_unsynced_bytes(struct tst_sender_config_t *p, size_t n);

 struct tst_raw_sender_config_t *tst_raw_sender_config_new(void);

 void tst_raw_sender_config_free(struct tst_raw_sender_config_t *p);

 struct tst_reconnect_policy_t *tst_reconnect_policy_new(void);

 void tst_reconnect_policy_free(struct tst_reconnect_policy_t *p);

/**
 * Set max reconnect attempts. `n < 0` means retry forever.
 */
 int tst_reconnect_policy_set_max_attempts(struct tst_reconnect_policy_t *p, int32_t n);

 int tst_reconnect_policy_set_backoff_constant_ms(struct tst_reconnect_policy_t *p, uint32_t ms);


int tst_reconnect_policy_set_backoff_exponential_ms(struct tst_reconnect_policy_t *p,
                                                    uint32_t base_ms,
                                                    uint32_t max_ms);

 int tst_reconnect_policy_set_gap_buffer_capacity(struct tst_reconnect_policy_t *p, size_t n);


int tst_reconnect_policy_set_overflow_policy(struct tst_reconnect_policy_t *p,
                                             enum tst_overflow_policy policy);

/**
 * Allocate a new `tst_demux_config_t` with default values
 * (strict mode = Off, no overrides, default PES caps).
 *
 * Returns `NULL` on allocation failure or internal panic.
 * Free with `tst_demux_config_free`.
 */
 struct TstDemuxConfig *tst_demux_config_new(void);

/**
 * Release a `tst_demux_config_t`. Safe to call with NULL.
 */
 void tst_demux_config_free(struct TstDemuxConfig *cfg);

/**
 * Set the demuxer's strict mode. `mode` is one of
 * `TST_STRICT_MODE_OFF` (0, default), `TST_STRICT_MODE_TIMING_ONLY` (1),
 * `TST_STRICT_MODE_DESCRIPTORS_ONLY` (2), or `TST_STRICT_MODE_FULL` (3).
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` on null `cfg` or
 * unrecognized `mode`.
 */
 int tst_demux_config_set_strict_mode(struct TstDemuxConfig *cfg, int mode);

/**
 * Add a `klv_pid` → `video_pid` KLV-link override. Bypasses PMT-descriptor
 * inference. Returns 0 on success, `TST_E_INVALID_CONFIG` on null `cfg`.
 */

int tst_demux_config_add_link_klv(struct TstDemuxConfig *cfg,
                                  uint16_t klv_pid,
                                  uint16_t video_pid);

/**
 * Force a PID's stream-kind classification. `stream_kind` is one of
 * `TST_STREAM_KIND_VIDEO_H264`, `TST_STREAM_KIND_VIDEO_H265`,
 * `TST_STREAM_KIND_AUDIO_MP2`, ... — see the header for the full table.
 *
 * NOTE: The C-side mapping flattens (TstStreamKindTag × codec) pairs
 * into single integers. The implementation table below covers the
 * common cases — extend if a consumer asks for a kind not listed.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` on null `cfg` or
 * unrecognized `stream_kind`.
 */
 int tst_demux_config_add_treat_as(struct TstDemuxConfig *cfg, uint16_t pid, int stream_kind);

/**
 * Set PES reassembly caps. `0` means use the Rust-side default.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` on null `cfg`.
 */
 int tst_demux_config_set_pes_cap(struct TstDemuxConfig *cfg, size_t per_pid, size_t total);

/**
 * Read the most recent error code on this thread. Returns `0`
 * (`TST_E_SUCCESS`) if no error has been recorded on this thread yet.
 * The value is not cleared by successful calls; it reflects the most
 * recent failure on this thread (or `TST_E_SUCCESS` if there has been
 * none since thread start).
 */
 int tst_get_last_error(void);

/**
 * Pointer to the most recent error message on this thread. Valid until
 * the next tst-c call on the same thread. Never NULL — empty string when
 * no error.
 */
 const char *tst_get_last_error_str(void);

/**
 * Open a `tst_mux_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `tst_get_last_error_str()` describes the specific problem.
 */
 struct tst_mux_sender_t *tst_mux_sender_open(const char *srt_url, struct tst_mux_config_t *cfg);


int tst_mux_sender_send_video(struct tst_mux_sender_t *p,
                              const uint8_t *nal,
                              size_t len,
                              int64_t pts_90khz,
                              bool key_frame);


int tst_mux_sender_send_klv(struct tst_mux_sender_t *p,
                            const uint8_t *klv,
                            size_t len,
                            int64_t pts_90khz);

/**
 * Push one Annex-B NAL targeting a specific video elementary stream.
 *
 * `stream_handle` is obtained from `tst_mux_config_add_video_stream` at
 * config time and is stable across the config→open boundary. Out-of-range
 * handles surface as `TST_E_INVALID_USAGE` (carrying
 * `MuxError::InvalidStreamHandle`).
 *
 * On a single-stream sender, prefer `tst_mux_sender_send_video` — same
 * effect, no handle required.
 */

int tst_mux_sender_send_video_to(struct tst_mux_sender_t *p,
                                 tst_video_stream_handle_t stream_handle,
                                 const uint8_t *nal,
                                 size_t len,
                                 int64_t pts_90khz,
                                 bool key_frame);

/**
 * Push one pre-built KLV blob targeting a specific KLV elementary stream.
 *
 * For `KlvStreamType::SynchronousMetadata` streams, the muxer auto-wraps
 * the caller's bytes in a `Metadata_AU_cell` header per ITU-T H.222.0
 * V9 § 2.12.4.2 (5 bytes prepended; PTS surfaced in the PES header).
 * For `KlvStreamType::PrivateData` streams, the caller's bytes pass
 * through unchanged.
 *
 * On a single-stream sender, prefer `tst_mux_sender_send_klv` — same
 * effect, no handle required.
 */

int tst_mux_sender_send_klv_to(struct tst_mux_sender_t *p,
                               tst_klv_stream_handle_t stream_handle,
                               const uint8_t *klv,
                               size_t len,
                               int64_t pts_90khz);

/**
 * Snapshot stats for a `tst_mux_sender_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */
 int tst_mux_sender_get_stats(struct tst_mux_sender_t *p, struct tst_mux_sender_stats_t *out);

/**
 * Reset stats counters for a `tst_mux_sender_t` to zero.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */
 int tst_mux_sender_reset_stats(struct tst_mux_sender_t *p);

 void tst_mux_sender_close(struct tst_mux_sender_t *p);

/**
 * Cancel a `tst_mux_sender_t`. Unblocks a thread parked in any `_send_*`
 * entry point within one libsrt I/O cycle (~3-10 ms) by closing the
 * underlying libsrt socket. Safe to call from any thread. Idempotent.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 *
 * After cancel, all `_send_*` entry points return `TST_E_CLOSED`. The
 * handle must still be `_close`'d to free.
 */
 int tst_mux_sender_cancel(struct tst_mux_sender_t *p);

/**
 * Open a `tst_managed_mux_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `tst_get_last_error_str()` describes the specific problem.
 */

struct tst_managed_mux_sender_t *tst_managed_mux_sender_open(const char *srt_url,
                                                             struct tst_mux_config_t *cfg,
                                                             const struct tst_reconnect_policy_t *policy);


int tst_managed_mux_sender_send_video(struct tst_managed_mux_sender_t *p,
                                      const uint8_t *nal,
                                      size_t len,
                                      int64_t pts_90khz,
                                      bool key_frame);


int tst_managed_mux_sender_send_klv(struct tst_managed_mux_sender_t *p,
                                    const uint8_t *klv,
                                    size_t len,
                                    int64_t pts_90khz);

/**
 * Push one Annex-B NAL targeting a specific video elementary stream on a
 * managed (auto-reconnecting) sender.
 *
 * `stream_handle` is obtained from `tst_mux_config_add_video_stream` at
 * config time and is stable across reconnects. Out-of-range handles
 * surface as `TST_E_INVALID_USAGE` (carrying
 * `MuxError::InvalidStreamHandle`).
 *
 * On a single-stream sender, prefer `tst_managed_mux_sender_send_video` —
 * same effect, no handle required.
 */

int tst_managed_mux_sender_send_video_to(struct tst_managed_mux_sender_t *p,
                                         tst_video_stream_handle_t stream_handle,
                                         const uint8_t *nal,
                                         size_t len,
                                         int64_t pts_90khz,
                                         bool key_frame);

/**
 * Push one pre-built KLV blob targeting a specific KLV elementary stream on
 * a managed (auto-reconnecting) sender.
 *
 * For `KlvStreamType::SynchronousMetadata` streams, the muxer auto-wraps
 * the caller's bytes in a `Metadata_AU_cell` header per ITU-T H.222.0
 * V9 § 2.12.4.2 (5 bytes prepended; PTS surfaced in the PES header).
 * For `KlvStreamType::PrivateData` streams, the caller's bytes pass
 * through unchanged.
 *
 * On a single-stream sender, prefer `tst_managed_mux_sender_send_klv` —
 * same effect, no handle required.
 */

int tst_managed_mux_sender_send_klv_to(struct tst_managed_mux_sender_t *p,
                                       tst_klv_stream_handle_t stream_handle,
                                       const uint8_t *klv,
                                       size_t len,
                                       int64_t pts_90khz);

/**
 * Snapshot stats for a `tst_managed_mux_sender_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */

int tst_managed_mux_sender_get_stats(struct tst_managed_mux_sender_t *p,
                                     struct tst_mux_sender_stats_t *out);

/**
 * Reset stats counters for a `tst_managed_mux_sender_t` to zero.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */
 int tst_managed_mux_sender_reset_stats(struct tst_managed_mux_sender_t *p);

 void tst_managed_mux_sender_close(struct tst_managed_mux_sender_t *p);

/**
 * Cancel a `tst_managed_mux_sender_t`. Same semantics as
 * `tst_mux_sender_cancel`; reaches the currently-active inner
 * transport's cancel handle through `ManagedTransport`'s atomic
 * snapshot.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 */
 int tst_managed_mux_sender_cancel(struct tst_managed_mux_sender_t *p);

/**
 * Open a standalone muxer. Builds the config from `cfg` so the caller may
 * free it immediately after this returns. Returns NULL on failure with
 * last-error set.
 */
 struct tst_muxer_t *tst_muxer_open(struct tst_mux_config_t *cfg);

/**
 * Push one Annex-B-framed video access unit. Returns 0 on success or a
 * negative TST_E_* code.
 */

int tst_muxer_push_video(struct tst_muxer_t *p,
                         const uint8_t *nal,
                         size_t len,
                         int64_t pts_90khz,
                         bool key_frame);

/**
 * Push one pre-built KLV blob.
 */
 int tst_muxer_push_klv(struct tst_muxer_t *p, const uint8_t *klv, size_t len, int64_t pts_90khz);

/**
 * Push one Annex-B NAL targeting a specific video elementary stream.
 *
 * `handle` is obtained from `tst_mux_config_add_video_stream` at config
 * time and is stable across managed-sender reconnects. Out-of-range
 * handles surface as `TST_E_INVALID_USAGE` (carrying
 * `MuxError::InvalidStreamHandle`).
 *
 * On a single-stream muxer, prefer `tst_muxer_push_video` — it has the
 * same effect and doesn't require a handle.
 */

int tst_muxer_push_video_to(struct tst_muxer_t *p,
                            tst_video_stream_handle_t handle,
                            const uint8_t *nal,
                            size_t len,
                            int64_t pts_90khz,
                            bool key_frame);

/**
 * Push one pre-built KLV blob targeting a specific KLV elementary stream.
 *
 * `handle` is obtained from `tst_mux_config_add_klv_stream`. Same
 * semantics as `tst_muxer_push_video_to`.
 *
 * For `KlvStreamType::SynchronousMetadata` streams, the muxer auto-wraps
 * the caller's bytes in a `Metadata_AU_cell` header per ITU-T H.222.0
 * V9 § 2.12.4.2 (5 bytes prepended; PTS surfaced in the PES header).
 * For `KlvStreamType::PrivateData` streams, the caller's bytes pass
 * through unchanged.
 */

int tst_muxer_push_klv_to(struct tst_muxer_t *p,
                          tst_klv_stream_handle_t handle,
                          const uint8_t *klv,
                          size_t len,
                          int64_t pts_90khz);

/**
 * Drain TS bytes into `out_buf` (capacity `out_cap`). Returns the number
 * of bytes written; 0 means nothing was ready or the buffer was too
 * small for the next chunk. Never sets last-error — 0 is a normal return
 * value.
 */
 size_t tst_muxer_pull(struct tst_muxer_t *p, uint8_t *out_buf, size_t out_cap);

/**
 * Snapshot stats for a `tst_muxer_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the muxer has been closed.
 */
 int tst_muxer_get_stats(struct tst_muxer_t *p, struct tst_muxer_stats_t *out);

/**
 * Reset stats counters for a `tst_muxer_t` to zero.
 *
 * Per-stream entries are preserved (identity fields remain); only flow
 * counters (`items`, `bytes`, `discontinuities`) are zeroed.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is
 * null, or `TST_E_CLOSED` if the muxer has been closed.
 */
 int tst_muxer_reset_stats(struct tst_muxer_t *p);

/**
 * Close and free the muxer. Idempotent — passing NULL is a no-op.
 */
 void tst_muxer_close(struct tst_muxer_t *p);

/**
 * Open a `tst_raw_receiver_t`. Accepts `srt://host:port?...` URLs;
 * URL with `?mode=listener` is routed through the listener path
 * (equivalent to calling `tst_raw_receiver_open_listener`).
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. `TST_E_TRANSPORT` set on connect/bind failure.
 */
 struct tst_raw_receiver_t *tst_raw_receiver_open(const char *srt_url);

/**
 * Explicit listener-mode open. Forces listener mode regardless of any
 * `?mode=` URL value — the `_listener` suffix is authoritative. URLs
 * with `?mode=caller` are accepted and silently overridden.
 *
 * Empty-host URLs like `srt://:7000` are accepted directly; the parser's
 * requirement for an explicit `?mode=listener` does not apply here because
 * the entry-point name is already the authoritative listener signal.
 *
 * (Phase 1 simplification of the design spec §4.2, which originally
 * proposed rejecting explicit `mode=caller` with `TST_E_INVALID_USAGE`.
 * The simpler rule is more forgiving and matches what most C consumers
 * expect from a `_listener`-suffixed entry point. The stricter check
 * can land in a future phase if a consumer asks.)
 */
 struct tst_raw_receiver_t *tst_raw_receiver_open_listener(const char *srt_url);

 void tst_raw_receiver_close(struct tst_raw_receiver_t *p);

/**
 * Cancel a `tst_raw_receiver_t`. Unblocks a thread parked in `_recv`
 * within one libsrt I/O cycle (~3-10 ms) by closing the underlying
 * libsrt socket. Safe to call from any thread. Idempotent.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 *
 * After cancel, `_recv` returns `TST_E_CLOSED` (not `TST_E_END_OF_STREAM`).
 * The handle must still be `_close`'d to free.
 */
 int tst_raw_receiver_cancel(struct tst_raw_receiver_t *p);

/**
 * Snapshot stats for a `tst_raw_receiver_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the receiver has been closed.
 */
 int tst_raw_receiver_get_stats(struct tst_raw_receiver_t *p, struct tst_raw_receiver_stats_t *out);

/**
 * Reset stats counters for a `tst_raw_receiver_t` to zero.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null,
 * or `TST_E_CLOSED` if the receiver has been closed.
 */
 int tst_raw_receiver_reset_stats(struct tst_raw_receiver_t *p);

/**
 * Block until one message arrives. Copies up to `len` bytes into `buf`
 * and writes the actual length to `*out_len`.
 *
 * Returns:
 * - 0 on success (`*out_len` set to bytes received; ≤ `len`)
 * - `TST_E_END_OF_STREAM` (-12) on graceful peer close
 * - `TST_E_CLOSED` (-7) if the handle was `_cancel`'d or `_close`'d
 * - `TST_E_TRANSPORT` (-8) on a transport failure other than a clean
 *   peer disconnect (peer FIN surfaces as `TST_E_END_OF_STREAM`; see
 *   the `TransportError::Broken` arm in this function for details)
 * - `TST_E_TOO_LARGE` (-6) if the inbound message exceeds `len`
 *   (`*out_len` is left unmodified)
 * - `TST_E_INVALID_CONFIG` (-1) on null pointer arguments
 */
 int tst_raw_receiver_recv(struct tst_raw_receiver_t *p, uint8_t *buf, size_t len, size_t *out_len);

/**
 * Open a `tst_managed_raw_receiver_t`. URL-driven mode dispatch
 * matches `tst_raw_receiver_open` semantics: `?mode=listener` routes
 * to the listener path, otherwise caller mode.
 *
 * On transport failure the managed wrapper automatically reconnects
 * (or re-binds for listener mode) according to `policy`. Pass `NULL`
 * for `policy` to use the default reconnect policy.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL. `TST_E_TRANSPORT` set on the
 * initial connect/bind failure.
 */

struct tst_managed_raw_receiver_t *tst_managed_raw_receiver_open(const char *srt_url,
                                                                 const struct tst_reconnect_policy_t *policy);

/**
 * Explicit listener-mode open for the managed receiver. Forces
 * listener mode regardless of any `?mode=` URL value — the
 * `_listener` suffix is authoritative. On peer disconnect the managed
 * wrapper re-binds a fresh listener socket and accepts the next
 * incoming connection. Note: the re-bind + re-accept may block
 * significantly between attempts depending on the reconnect policy.
 *
 * Empty-host URLs like `srt://:7000` are accepted directly; the parser's
 * requirement for an explicit `?mode=listener` does not apply here because
 * the entry-point name is already the authoritative listener signal.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set for malformed URLs
 * or `TST_E_TRANSPORT` on the initial bind/accept failure.
 */

struct tst_managed_raw_receiver_t *tst_managed_raw_receiver_open_listener(const char *srt_url,
                                                                          const struct tst_reconnect_policy_t *policy);

/**
 * Block until one message arrives. Semantics match `tst_raw_receiver_recv`;
 * on transport failure the managed inner reconnects transparently before
 * returning an error only once the retry budget is exhausted.
 *
 * # Asymmetry with `tst_raw_receiver_recv`
 *
 * The plain `tst_raw_receiver_recv` maps `TransportError::Broken` on
 * a non-cancelled handle to `TST_E_END_OF_STREAM` (peer disconnect at
 * the bare-transport layer is semantically end-of-stream). The managed
 * version does NOT apply that mapping: `ManagedReceiveTransport`
 * already retries internally on Broken, so a Broken that reaches this
 * function means all reconnect attempts have been exhausted — that is
 * a hard transport failure (`TST_E_TRANSPORT`), not an end-of-stream.
 */

int tst_managed_raw_receiver_recv(struct tst_managed_raw_receiver_t *p,
                                  uint8_t *buf,
                                  size_t len,
                                  size_t *out_len);

/**
 * Cancel a `tst_managed_raw_receiver_t`. Unblocks a thread parked in
 * `_recv` within one libsrt I/O cycle (~3-10 ms). Safe from any thread.
 * Idempotent. After cancel, `_recv` returns `TST_E_CLOSED`. The handle
 * must still be `_close`'d to free memory.
 */
 int tst_managed_raw_receiver_cancel(struct tst_managed_raw_receiver_t *p);

 void tst_managed_raw_receiver_close(struct tst_managed_raw_receiver_t *p);

/**
 * Snapshot stats for a `tst_managed_raw_receiver_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the receiver has been closed.
 */

int tst_managed_raw_receiver_get_stats(struct tst_managed_raw_receiver_t *p,
                                       struct tst_raw_receiver_stats_t *out);

/**
 * Reset stats counters for a `tst_managed_raw_receiver_t` to zero.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null,
 * or `TST_E_CLOSED` if the receiver has been closed.
 */
 int tst_managed_raw_receiver_reset_stats(struct tst_managed_raw_receiver_t *p);

/**
 * Open a `tst_raw_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `tst_get_last_error_str()` describes the specific problem.
 */

struct tst_raw_sender_t *tst_raw_sender_open(const char *srt_url,
                                             const struct tst_raw_sender_config_t *cfg);

 int tst_raw_sender_send(struct tst_raw_sender_t *p, const uint8_t *bytes, size_t len);

 void tst_raw_sender_close(struct tst_raw_sender_t *p);

/**
 * Cancel a `tst_raw_sender_t`. Unblocks a thread parked in `_send`
 * within one libsrt I/O cycle (~3-10 ms) by closing the underlying
 * libsrt socket. Safe to call from any thread. Idempotent.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 *
 * After cancel, `_send` returns `TST_E_CLOSED`. The handle must still
 * be `_close`'d to free.
 */
 int tst_raw_sender_cancel(struct tst_raw_sender_t *p);

/**
 * Open a `tst_managed_raw_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `tst_get_last_error_str()` describes the specific problem.
 */

struct tst_managed_raw_sender_t *tst_managed_raw_sender_open(const char *srt_url,
                                                             const struct tst_raw_sender_config_t *cfg,
                                                             const struct tst_reconnect_policy_t *policy);


int tst_managed_raw_sender_send(struct tst_managed_raw_sender_t *p,
                                const uint8_t *bytes,
                                size_t len);

 void tst_managed_raw_sender_close(struct tst_managed_raw_sender_t *p);

/**
 * Cancel a `tst_managed_raw_sender_t`. Same semantics as
 * `tst_raw_sender_cancel`; reaches the currently-active inner
 * transport's cancel handle through `ManagedTransport`'s atomic
 * snapshot.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 */
 int tst_managed_raw_sender_cancel(struct tst_managed_raw_sender_t *p);

/**
 * Snapshot stats for a `tst_raw_sender_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */
 int tst_raw_sender_get_stats(struct tst_raw_sender_t *p, struct tst_raw_sender_stats_t *out);

/**
 * Reset stats counters for a `tst_raw_sender_t` to zero.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */
 int tst_raw_sender_reset_stats(struct tst_raw_sender_t *p);

/**
 * Snapshot stats for a `tst_managed_raw_sender_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */

int tst_managed_raw_sender_get_stats(struct tst_managed_raw_sender_t *p,
                                     struct tst_raw_sender_stats_t *out);

/**
 * Reset stats counters for a `tst_managed_raw_sender_t` to zero.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is
 * null, or `TST_E_CLOSED` if the sender has been closed.
 */
 int tst_managed_raw_sender_reset_stats(struct tst_managed_raw_sender_t *p);

/**
 * Open a `tst_receiver_t`. Accepts `srt://host:port?...` URLs;
 * URL with `?mode=listener` is routed through the listener path
 * (equivalent to calling `tst_receiver_open_listener`).
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. `TST_E_TRANSPORT` set on connect/bind failure.
 */
 struct tst_receiver_t *tst_receiver_open(const char *srt_url);

/**
 * Explicit listener-mode open. Forces listener mode regardless of any
 * `?mode=` URL value — the `_listener` suffix is authoritative. URLs
 * with `?mode=caller` are accepted and silently overridden.
 *
 * Empty-host URLs like `srt://:7000` are accepted directly; the parser's
 * requirement for an explicit `?mode=listener` does not apply here because
 * the entry-point name is already the authoritative listener signal.
 */
 struct tst_receiver_t *tst_receiver_open_listener(const char *srt_url);

 void tst_receiver_close(struct tst_receiver_t *p);

/**
 * Block until one 188-byte MPEG-TS packet is ready, then copy it into
 * the caller's `out_packet` buffer.
 *
 * `out_packet` MUST point to a buffer of at least 188 bytes (a
 * `uint8_t[188]` array on the C side). The pointer is dereferenced
 * once on success; no allocation crosses the FFI boundary.
 *
 * Returns:
 * - `0` on success (188 bytes written to `out_packet`)
 * - `TST_E_END_OF_STREAM` (-12) on graceful peer close
 * - `TST_E_CLOSED` (-7) if the handle was `_cancel`'d or `_close`'d
 * - `TST_E_TRANSPORT` (-8) on a transport failure other than a clean
 *   peer disconnect (peer FIN surfaces as `TST_E_END_OF_STREAM`; see
 *   the `TransportError::Broken` arm in this function for details)
 * - `TST_E_INVALID_CONFIG` (-1) on null pointer arguments
 *
 * On any non-zero return the contents of `out_packet` are unspecified.
 */
 int tst_receiver_recv_packet(struct tst_receiver_t *p, uint8_t *out_packet);

/**
 * Cancel a `tst_receiver_t`. Unblocks a thread parked in
 * `_recv_packet` within one libsrt I/O cycle (~3-10 ms) by closing
 * the underlying libsrt socket. Safe to call from any thread.
 * Idempotent.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 *
 * After cancel, `_recv_packet` returns `TST_E_CLOSED` (not
 * `TST_E_END_OF_STREAM`). The handle must still be `_close`'d to free.
 */
 int tst_receiver_cancel(struct tst_receiver_t *p);

/**
 * Snapshot stats for a `tst_receiver_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the receiver has been closed.
 */
 int tst_receiver_get_stats(struct tst_receiver_t *p, struct tst_receiver_stats_t *out);

/**
 * Reset stats counters for a `tst_receiver_t` to zero. Does not
 * affect transport state or the syncer state machine.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null,
 * or `TST_E_CLOSED` if the receiver has been closed.
 */
 int tst_receiver_reset_stats(struct tst_receiver_t *p);

/**
 * Open a `tst_managed_receiver_t`. URL-driven mode dispatch
 * matches `tst_receiver_open` semantics: `?mode=listener` routes
 * to the listener path, otherwise caller mode.
 *
 * On transport failure the managed wrapper automatically reconnects
 * (or re-binds for listener mode) according to `policy`. Pass `NULL`
 * for `policy` to use the default reconnect policy.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL. `TST_E_TRANSPORT` set on the
 * initial connect/bind failure.
 */

struct tst_managed_receiver_t *tst_managed_receiver_open(const char *srt_url,
                                                         const struct tst_reconnect_policy_t *policy);

/**
 * Explicit listener-mode open for the managed receiver. Forces
 * listener mode regardless of any `?mode=` URL value — the
 * `_listener` suffix is authoritative. On peer disconnect the managed
 * wrapper re-binds a fresh listener socket and accepts the next
 * incoming connection. Note: the re-bind + re-accept may block
 * significantly between attempts depending on the reconnect policy.
 *
 * Empty-host URLs like `srt://:7000` are accepted directly; the parser's
 * requirement for an explicit `?mode=listener` does not apply here because
 * the entry-point name is already the authoritative listener signal.
 */

struct tst_managed_receiver_t *tst_managed_receiver_open_listener(const char *srt_url,
                                                                  const struct tst_reconnect_policy_t *policy);

/**
 * Block until one 188-byte MPEG-TS packet is ready. Semantics match
 * `tst_receiver_recv_packet`; on transport failure the managed
 * inner reconnects transparently before returning an error only once
 * the retry budget is exhausted.
 *
 * # Asymmetry with `tst_receiver_recv_packet`
 *
 * The plain `tst_receiver_recv_packet` maps `TransportError::Broken`
 * on a non-cancelled handle to `TST_E_END_OF_STREAM` (peer disconnect at
 * the bare-transport layer is semantically end-of-stream). The managed
 * version does NOT apply that mapping: `ManagedReceiveTransport`
 * already retries internally on Broken, so a Broken that reaches this
 * function means all reconnect attempts have been exhausted — that is
 * a hard transport failure (`TST_E_TRANSPORT`), not an end-of-stream.
 */
 int tst_managed_receiver_recv_packet(struct tst_managed_receiver_t *p, uint8_t *out_packet);

/**
 * Cancel a `tst_managed_receiver_t`. Unblocks a thread parked in
 * `_recv_packet` within one libsrt I/O cycle (~3-10 ms). Safe from
 * any thread. Idempotent. After cancel, `_recv_packet` returns
 * `TST_E_CLOSED`. The handle must still be `_close`'d to free memory.
 */
 int tst_managed_receiver_cancel(struct tst_managed_receiver_t *p);

 void tst_managed_receiver_close(struct tst_managed_receiver_t *p);

/**
 * Snapshot stats for a `tst_managed_receiver_t` into `*out`.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if either pointer is
 * null, or `TST_E_CLOSED` if the receiver has been closed.
 */

int tst_managed_receiver_get_stats(struct tst_managed_receiver_t *p,
                                   struct tst_receiver_stats_t *out);

/**
 * Reset stats counters for a `tst_managed_receiver_t` to zero.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null,
 * or `TST_E_CLOSED` if the receiver has been closed.
 */
 int tst_managed_receiver_reset_stats(struct tst_managed_receiver_t *p);

/**
 * Open a `tst_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `tst_get_last_error_str()` describes the specific problem.
 */
 struct tst_sender_t *tst_sender_open(const char *srt_url, const struct tst_sender_config_t *cfg);

 int tst_sender_send_ts(struct tst_sender_t *p, const uint8_t *bytes, size_t len);

 int tst_sender_flush(struct tst_sender_t *p);

 int tst_sender_get_stats(struct tst_sender_t *p, struct tst_sender_stats_t *out);

 int tst_sender_reset_stats(struct tst_sender_t *p);

 void tst_sender_close(struct tst_sender_t *p);

/**
 * Cancel a `tst_sender_t`. Unblocks a thread parked in `_send`
 * within one libsrt I/O cycle (~3-10 ms) by closing the underlying
 * libsrt socket. Safe to call from any thread. Idempotent.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 *
 * After cancel, `_send` returns `TST_E_CLOSED`. The handle must still
 * be `_close`'d to free.
 */
 int tst_sender_cancel(struct tst_sender_t *p);

/**
 * Open a `tst_managed_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `TST_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `tst_get_last_error_str()` describes the specific problem.
 */

struct tst_managed_sender_t *tst_managed_sender_open(const char *srt_url,
                                                     const struct tst_sender_config_t *cfg,
                                                     const struct tst_reconnect_policy_t *policy);

 int tst_managed_sender_send_ts(struct tst_managed_sender_t *p, const uint8_t *bytes, size_t len);

 int tst_managed_sender_flush(struct tst_managed_sender_t *p);

 int tst_managed_sender_get_stats(struct tst_managed_sender_t *p, struct tst_sender_stats_t *out);

 int tst_managed_sender_reset_stats(struct tst_managed_sender_t *p);

 void tst_managed_sender_close(struct tst_managed_sender_t *p);

/**
 * Cancel a `tst_managed_sender_t`. Same semantics as
 * `tst_sender_cancel`; reaches the currently-active inner
 * transport's cancel handle through `ManagedTransport`'s atomic
 * snapshot.
 *
 * Returns 0 on success, `TST_E_INVALID_CONFIG` if the pointer is null.
 */
 int tst_managed_sender_cancel(struct tst_managed_sender_t *p);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TSTRANS_H */
