/*
 * srtc.h — C ABI for the srt-core sender pipeline.
 *
 * This file is GENERATED by cbindgen. Do not edit manually.
 * Source of truth: crates/srt-c/src/ (Rust).
 *
 * Copyright (c) 2026 Andrew Klofas. Licensed under MIT OR Apache-2.0.
 */


#ifndef SRTC_H
#define SRTC_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>

/**
 * Major version (compile-time macro in the generated header).
 */
#define SRTC_VERSION_MAJOR 0

/**
 * Minor version.
 */
#define SRTC_VERSION_MINOR 1

/**
 * Patch version.
 */
#define SRTC_VERSION_PATCH 0

/**
 * Sentinel returned by `srtc_mux_config_add_*_stream` on failure.
 * On failure, the last-error is also populated; check
 * `srtc_get_last_error()` for the negative `SRTC_E_*` code.
 */
#define SRTC_INVALID_STREAM_HANDLE UINT32_MAX

/**
 * Maximum number of per-stream entries in any stats struct exposed at
 * the C ABI. Rarely exceeded — multi-stream `mpegts::mux` caps at
 * 16 video + 16 KLV = 32, leaving 32 slots of headroom for receiver
 * PSI + observed streams.
 */
#define SRTC_STATS_MAX_STREAMS 64

typedef enum srtc_video_codec {
  SRTC_VIDEO_CODEC_H264 = 0,
  SRTC_VIDEO_CODEC_H265 = 1,
} srtc_video_codec;

typedef enum srtc_klv_stream_type {
  SRTC_KLV_STREAM_TYPE_PRIVATE_DATA = 0,
  SRTC_KLV_STREAM_TYPE_SYNCHRONOUS_METADATA = 1,
} srtc_klv_stream_type;

typedef enum srtc_ts_framing_mode {
  SRTC_TS_FRAMING_MODE_RECOVER = 0,
  SRTC_TS_FRAMING_MODE_STRICT = 1,
} srtc_ts_framing_mode;

typedef enum srtc_overflow_policy {
  SRTC_OVERFLOW_POLICY_DROP_OLDEST = 0,
  SRTC_OVERFLOW_POLICY_REJECT = 1,
} srtc_overflow_policy;

/**
 * Negative codes returned by every fallible srt-c entry point.
 *
 * `Success = 0` is the only non-negative variant. Codes are stable
 * across srt-c versions; new codes append at the end.
 */
enum srtc_e
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  SRTC_E_SUCCESS = 0,
  SRTC_E_INVALID_CONFIG = -1,
  SRTC_E_INVALID_NAL = -2,
  SRTC_E_INVALID_TS = -3,
  SRTC_E_BUFFER_FULL = -4,
  SRTC_E_KLV_TOO_LARGE = -5,
  SRTC_E_TOO_LARGE = -6,
  SRTC_E_CLOSED = -7,
  SRTC_E_TRANSPORT = -8,
  SRTC_E_INVALID_USAGE = -9,
  SRTC_E_INTERNAL = -10,
};
#ifndef __cplusplus
typedef int32_t srtc_e;
#endif // __cplusplus

typedef struct srtc_managed_mux_sender_t srtc_managed_mux_sender_t;

typedef struct srtc_managed_raw_sender_t srtc_managed_raw_sender_t;

typedef struct srtc_managed_ts_sender_t srtc_managed_ts_sender_t;

/**
 * Opaque mux-config builder. Constructed via `srtc_mux_config_new`,
 * populated via `srtc_mux_config_add_program` + stream-add / descriptor-set
 * entry points, then consumed by `srtc_*_open` (which clones the inner).
 * Caller is responsible for calling `srtc_mux_config_free`.
 *
 * Unlike the pre-multi-program API, the config starts **empty** — no program
 * is pre-created. The caller must call `srtc_mux_config_add_program` at
 * least once before opening a muxer or sender.
 */
typedef struct srtc_mux_config_t srtc_mux_config_t;

typedef struct srtc_mux_sender_t srtc_mux_sender_t;

typedef struct srtc_muxer_t srtc_muxer_t;

typedef struct srtc_raw_sender_t srtc_raw_sender_t;

typedef struct srtc_raw_sender_config_t srtc_raw_sender_config_t;

typedef struct srtc_reconnect_policy_t srtc_reconnect_policy_t;

typedef struct srtc_ts_sender_t srtc_ts_sender_t;

typedef struct srtc_ts_sender_config_t srtc_ts_sender_config_t;

/**
 * Opaque handle returned by `srtc_mux_config_add_program`. Used as an
 * argument to subsequent stream-add and config-set entry points to
 * disambiguate which program's streams or descriptors are being modified.
 *
 * The value is a zero-based index into the program list. Programs are
 * numbered in the order they were added. Handles are stable across the
 * config→open boundary — the same index applies after `srtc_muxer_open`.
 */
typedef uint32_t srtc_program_handle_t;

/**
 * Opaque per-program ordinal for a video elementary stream. Obtained from
 * [`srtc_mux_config_add_video_stream`] at config time and reused with the
 * `_video_to` push siblings on every muxer-owning C variant.
 *
 * Handles are stable across the config→open boundary and across managed
 * reconnects. They encode `(program_index, within_program_index)` as a
 * packed `u32` (bits 4..=7 = program, bits 0..=3 = within). They are NOT
 * interchangeable between muxers.
 */
typedef uint32_t srtc_video_stream_handle_t;

/**
 * Opaque per-program ordinal for a KLV elementary stream. Same packed
 * encoding as [`SrtcVideoStreamHandle`].
 */
typedef uint32_t srtc_klv_stream_handle_t;

/**
 * `repr(C)` mirror of `srt_core::mpegts::StreamStats`. Size 96 B.
 *
 * Layout (offsets):
 *   0: items (u64, 8 B)
 *   8: bytes (u64, 8 B)
 *  16: discontinuities (u64, 8 B)
 *  24: pid (u16, 2 B)
 *  26: stream_type (u8, 1 B)
 *  27: _pad (3 B, alignment bridge)
 *  30: program_number (u16, 2 B)
 *  32: label ([c_char; 64], 64 B)
 * Total: 96 B — identical to the pre-program_number layout.
 */
typedef struct srtc_stream_stats_t {
  uint64_t items;
  uint64_t bytes;
  uint64_t discontinuities;
  uint16_t pid;
  uint8_t stream_type;
  /**
   * Alignment padding bridging stream_type → program_number.
   */
  uint8_t _pad[3];
  /**
   * Program number from the PAT that owns this stream. 0 for PSI PIDs.
   */
  uint16_t program_number;
  /**
   * NUL-terminated UTF-8. label[0]==0 means None. Truncated at 63
   * bytes (first 63 + NUL).
   */
  char label[64];
} srtc_stream_stats_t;

/**
 * `repr(C)` mirror of `srt_core::pipeline::SenderStats`. Size 6188 B.
 */
typedef struct srtc_sender_stats_t {
  uint64_t bytes_sent;
  uint64_t packets_sent;
  uint64_t pending_bytes_queued;
  uint64_t pending_chunks_queued;
  /**
   * Number of programs (PAT entries) in the muxer configuration.
   */
  uint32_t programs_configured;
  uint32_t per_stream_count;
  uint32_t per_stream_truncated;
  struct srtc_stream_stats_t per_stream[SRTC_STATS_MAX_STREAMS];
} srtc_sender_stats_t;

/**
 * `repr(C)` mirror of `srt_core::mpegts::mux::MuxerStats`. Size 6172 B.
 */
typedef struct srtc_muxer_stats_t {
  uint64_t ts_packets_emitted;
  uint64_t ts_bytes_emitted;
  /**
   * Number of programs (PAT entries) in this muxer's configuration.
   */
  uint32_t programs_configured;
  uint32_t per_stream_count;
  uint32_t per_stream_truncated;
  struct srtc_stream_stats_t per_stream[SRTC_STATS_MAX_STREAMS];
} srtc_muxer_stats_t;

/**
 * `repr(C)` mirror of `srt_core::pipeline::RawSenderStats`. Size 16 B.
 */
typedef struct srtc_raw_sender_stats_t {
  uint64_t bytes_sent;
  uint64_t packets_sent;
} srtc_raw_sender_stats_t;

/**
 * Public-ABI mirror of `srt_core::pipeline::TsSenderStats`. Same fields,
 * same units. Caller passes a pointer to a stack-allocated struct;
 * `srtc_ts_sender_get_stats` fills it in.
 */
typedef struct srtc_ts_sender_stats_t {
  uint64_t bytes_pushed;
  uint64_t bytes_skipped_for_sync;
  uint64_t resync_events;
  uint64_t packets_sent;
} srtc_ts_sender_stats_t;

/**
 * Sentinel returned by `srtc_mux_config_add_program` on failure (null cfg
 * or other hard error). Check `srtc_get_last_error()` for the reason.
 */
#define SRTC_INVALID_PROGRAM_HANDLE UINT32_MAX

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new, empty mux config. No programs are added — call
 * `srtc_mux_config_add_program` before using this config to open a muxer
 * or sender. Returns NULL only on allocation failure (OOM).
 */
 struct srtc_mux_config_t *srtc_mux_config_new(void);

/**
 * Free a mux config previously returned by `srtc_mux_config_new`. No-op on
 * NULL. The config must not be used after this call.
 */
 void srtc_mux_config_free(struct srtc_mux_config_t *p);

/**
 * Begin a new program in this multiplex. Returns a handle used as the
 * `program` argument to subsequent stream-add and descriptor-set entry
 * points. Programs are numbered in insertion order starting at 0.
 *
 * `program_number` is the PAT program_number field (must be > 0 and unique
 * within the config). `pmt_pid` is the PID on which this program's PMT will
 * be carried (must be unique within the config and not collide with any
 * stream PID).
 *
 * Returns `SRTC_INVALID_PROGRAM_HANDLE` and sets last-error on null `cfg`.
 * Validation (duplicate program_number, colliding PMT PID, etc.) is deferred
 * to `srtc_muxer_open` / `srtc_*_sender_open` time.
 */

srtc_program_handle_t srtc_mux_config_add_program(struct srtc_mux_config_t *cfg,
                                                  uint16_t program_number,
                                                  uint16_t pmt_pid);

/**
 * Add a video elementary stream to the specified program and return its
 * handle.
 *
 * The returned `srtc_video_stream_handle_t` is stable across the config→open
 * boundary and across managed-sender reconnects. Pass it to
 * `srtc_muxer_push_video_to` / `srtc_mux_sender_send_video_to` /
 * `srtc_managed_mux_sender_send_video_to` to fan out to this specific stream.
 *
 * Returns `SRTC_INVALID_STREAM_HANDLE` and sets last-error on: null `cfg`,
 * invalid `program` handle, or per-program stream cap exceeded (>16 streams
 * of any kind per program). Hard validation errors surface at `_open` time.
 */

srtc_video_stream_handle_t srtc_mux_config_add_video_stream(struct srtc_mux_config_t *cfg,
                                                            srtc_program_handle_t program,
                                                            uint16_t pid,
                                                            enum srtc_video_codec codec);

/**
 * Add a KLV elementary stream to the specified program and return its handle.
 *
 * `stream_type`: `SRTC_KLV_STREAM_TYPE_PRIVATE_DATA` (0x06, async — no AU
 * cell wrapping required) or `SRTC_KLV_STREAM_TYPE_SYNCHRONOUS_METADATA`
 * (0x15 — callers MUST pre-wrap each blob via the ST 1910 AU cell wrapper
 * before calling `push_klv_to`; the muxer does not auto-wrap).
 *
 * `carries_pts`: set `true` for synchronous KLV (PTS carried in PES header),
 * `false` for async KLV.
 *
 * Returns `SRTC_INVALID_STREAM_HANDLE` on error (same conditions as
 * `srtc_mux_config_add_video_stream`).
 */

srtc_klv_stream_handle_t srtc_mux_config_add_klv_stream(struct srtc_mux_config_t *cfg,
                                                        srtc_program_handle_t program,
                                                        uint16_t pid,
                                                        enum srtc_klv_stream_type stream_type,
                                                        bool carries_pts);

/**
 * Pin the PCR PID for the specified program. By default the muxer uses the
 * first video stream's PID (or first KLV PID for KLV-only programs).
 *
 * Returns 0 on success, or a negative `SRTC_E_*` code on null pointer or
 * invalid program handle.
 */

int srtc_mux_config_set_pcr_pid(struct srtc_mux_config_t *cfg,
                                srtc_program_handle_t program,
                                uint16_t pid);

/**
 * Set the PCR re-emission interval for this mux config (applies to all
 * programs). Default is 40 ms. Must be in range 1..=100.
 */
 int srtc_mux_config_set_pcr_interval_ms(struct srtc_mux_config_t *p, uint32_t ms);

/**
 * Set the PAT/PMT re-emission interval for this mux config. Default 100 ms.
 * Must be >= 10.
 */
 int srtc_mux_config_set_psi_interval_ms(struct srtc_mux_config_t *p, uint32_t ms);

/**
 * Set the TS-packet output buffer capacity. Default 10000 (~1.88 MB).
 * Must be >= 10.
 */
 int srtc_mux_config_set_buffer_packets(struct srtc_mux_config_t *p, size_t n);

/**
 * Set program-level PMT descriptors for the specified program.
 *
 * `tlv_bytes` points to the concatenation of `tlv_count` TLV triples,
 * totalling `tlv_total_len` bytes. Each TLV has the layout:
 *   byte 0: tag
 *   byte 1: length of body (N)
 *   bytes 2..2+N: body
 *
 * Calling with `tlv_total_len == 0` or `tlv_count == 0` clears any
 * previously set program descriptors for this program.
 *
 * Returns 0 on success or a negative `SRTC_E_*` code on: null `cfg`,
 * null `tlv_bytes` with non-zero count, invalid program handle, or a
 * malformed TLV byte stream (truncated length or body).
 */

int srtc_mux_config_set_program_descriptors(struct srtc_mux_config_t *cfg,
                                            srtc_program_handle_t program,
                                            const uint8_t *tlv_bytes,
                                            size_t tlv_total_len,
                                            size_t tlv_count);

/**
 * Set per-stream PMT descriptors for the specified video stream.
 *
 * `video` is a handle previously returned by `srtc_mux_config_add_video_stream`.
 * The TLV byte format is the same as `srtc_mux_config_set_program_descriptors`.
 *
 * Calling with `tlv_total_len == 0` or `tlv_count == 0` clears any
 * previously set stream descriptors for this stream.
 *
 * Returns 0 on success or a negative `SRTC_E_*` code on: null `cfg`,
 * invalid handle, null `tlv_bytes` with non-zero count, or malformed TLV.
 */

int srtc_mux_config_set_stream_descriptors_for_video(struct srtc_mux_config_t *cfg,
                                                     srtc_video_stream_handle_t video,
                                                     const uint8_t *tlv_bytes,
                                                     size_t tlv_total_len,
                                                     size_t tlv_count);

/**
 * Set per-stream PMT descriptors for the specified KLV stream.
 *
 * `klv` is a handle previously returned by `srtc_mux_config_add_klv_stream`.
 * The TLV byte format is the same as `srtc_mux_config_set_program_descriptors`.
 *
 * Returns 0 on success or a negative `SRTC_E_*` code on the same conditions
 * as `srtc_mux_config_set_stream_descriptors_for_video`.
 */

int srtc_mux_config_set_stream_descriptors_for_klv(struct srtc_mux_config_t *cfg,
                                                   srtc_klv_stream_handle_t klv,
                                                   const uint8_t *tlv_bytes,
                                                   size_t tlv_total_len,
                                                   size_t tlv_count);

 struct srtc_ts_sender_config_t *srtc_ts_sender_config_new(void);

 void srtc_ts_sender_config_free(struct srtc_ts_sender_config_t *p);


int srtc_ts_sender_config_set_framing_mode(struct srtc_ts_sender_config_t *p,
                                           enum srtc_ts_framing_mode mode);

 int srtc_ts_sender_config_set_max_unsynced_bytes(struct srtc_ts_sender_config_t *p, size_t n);

 struct srtc_raw_sender_config_t *srtc_raw_sender_config_new(void);

 void srtc_raw_sender_config_free(struct srtc_raw_sender_config_t *p);

 struct srtc_reconnect_policy_t *srtc_reconnect_policy_new(void);

 void srtc_reconnect_policy_free(struct srtc_reconnect_policy_t *p);

/**
 * Set max reconnect attempts. `n < 0` means retry forever.
 */
 int srtc_reconnect_policy_set_max_attempts(struct srtc_reconnect_policy_t *p, int32_t n);

 int srtc_reconnect_policy_set_backoff_constant_ms(struct srtc_reconnect_policy_t *p, uint32_t ms);


int srtc_reconnect_policy_set_backoff_exponential_ms(struct srtc_reconnect_policy_t *p,
                                                     uint32_t base_ms,
                                                     uint32_t max_ms);

 int srtc_reconnect_policy_set_gap_buffer_capacity(struct srtc_reconnect_policy_t *p, size_t n);


int srtc_reconnect_policy_set_overflow_policy(struct srtc_reconnect_policy_t *p,
                                              enum srtc_overflow_policy policy);

/**
 * Read the most recent error code on this thread. Returns `0`
 * (`SRTC_E_SUCCESS`) if no error has been recorded on this thread yet.
 * The value is not cleared by successful calls; it reflects the most
 * recent failure on this thread (or `SRTC_E_SUCCESS` if there has been
 * none since thread start).
 */
 int srtc_get_last_error(void);

/**
 * Pointer to the most recent error message on this thread. Valid until
 * the next srt-c call on the same thread. Never NULL — empty string when
 * no error.
 */
 const char *srtc_get_last_error_str(void);

/**
 * Open a `srtc_mux_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `SRTC_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `srtc_get_last_error_str()` describes the specific problem.
 */
 struct srtc_mux_sender_t *srtc_mux_sender_open(const char *srt_url, struct srtc_mux_config_t *cfg);


int srtc_mux_sender_send_video(struct srtc_mux_sender_t *p,
                               const uint8_t *nal,
                               size_t len,
                               int64_t pts_90khz,
                               bool key_frame);


int srtc_mux_sender_send_klv(struct srtc_mux_sender_t *p,
                             const uint8_t *klv,
                             size_t len,
                             int64_t pts_90khz);

/**
 * Push one Annex-B NAL targeting a specific video elementary stream.
 *
 * `stream_handle` is obtained from `srtc_mux_config_add_video_stream` at
 * config time and is stable across the config→open boundary. Out-of-range
 * handles surface as `SRTC_E_INVALID_USAGE` (carrying
 * `MuxError::InvalidStreamHandle`).
 *
 * On a single-stream sender, prefer `srtc_mux_sender_send_video` — same
 * effect, no handle required.
 */

int srtc_mux_sender_send_video_to(struct srtc_mux_sender_t *p,
                                  srtc_video_stream_handle_t stream_handle,
                                  const uint8_t *nal,
                                  size_t len,
                                  int64_t pts_90khz,
                                  bool key_frame);

/**
 * Push one pre-built KLV blob targeting a specific KLV elementary stream.
 *
 * For `KlvStreamType::SynchronousMetadata` streams, callers must
 * pre-wrap the KLV via `srt_core::klv::st1910::wrap_au_cell` — the
 * muxer does not auto-wrap.
 *
 * On a single-stream sender, prefer `srtc_mux_sender_send_klv` — same
 * effect, no handle required.
 */

int srtc_mux_sender_send_klv_to(struct srtc_mux_sender_t *p,
                                srtc_klv_stream_handle_t stream_handle,
                                const uint8_t *klv,
                                size_t len,
                                int64_t pts_90khz);

/**
 * Snapshot stats for a `srtc_mux_sender_t` into `*out`.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if either pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */
 int srtc_mux_sender_get_stats(struct srtc_mux_sender_t *p, struct srtc_sender_stats_t *out);

/**
 * Reset stats counters for a `srtc_mux_sender_t` to zero.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if the pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */
 int srtc_mux_sender_reset_stats(struct srtc_mux_sender_t *p);

 void srtc_mux_sender_close(struct srtc_mux_sender_t *p);

/**
 * Open a `srtc_managed_mux_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `SRTC_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `srtc_get_last_error_str()` describes the specific problem.
 */

struct srtc_managed_mux_sender_t *srtc_managed_mux_sender_open(const char *srt_url,
                                                               struct srtc_mux_config_t *cfg,
                                                               const struct srtc_reconnect_policy_t *policy);


int srtc_managed_mux_sender_send_video(struct srtc_managed_mux_sender_t *p,
                                       const uint8_t *nal,
                                       size_t len,
                                       int64_t pts_90khz,
                                       bool key_frame);


int srtc_managed_mux_sender_send_klv(struct srtc_managed_mux_sender_t *p,
                                     const uint8_t *klv,
                                     size_t len,
                                     int64_t pts_90khz);

/**
 * Push one Annex-B NAL targeting a specific video elementary stream on a
 * managed (auto-reconnecting) sender.
 *
 * `stream_handle` is obtained from `srtc_mux_config_add_video_stream` at
 * config time and is stable across reconnects. Out-of-range handles
 * surface as `SRTC_E_INVALID_USAGE` (carrying
 * `MuxError::InvalidStreamHandle`).
 *
 * On a single-stream sender, prefer `srtc_managed_mux_sender_send_video` —
 * same effect, no handle required.
 */

int srtc_managed_mux_sender_send_video_to(struct srtc_managed_mux_sender_t *p,
                                          srtc_video_stream_handle_t stream_handle,
                                          const uint8_t *nal,
                                          size_t len,
                                          int64_t pts_90khz,
                                          bool key_frame);

/**
 * Push one pre-built KLV blob targeting a specific KLV elementary stream on
 * a managed (auto-reconnecting) sender.
 *
 * For `KlvStreamType::SynchronousMetadata` streams, callers must
 * pre-wrap the KLV via `srt_core::klv::st1910::wrap_au_cell` — the
 * muxer does not auto-wrap.
 *
 * On a single-stream sender, prefer `srtc_managed_mux_sender_send_klv` —
 * same effect, no handle required.
 */

int srtc_managed_mux_sender_send_klv_to(struct srtc_managed_mux_sender_t *p,
                                        srtc_klv_stream_handle_t stream_handle,
                                        const uint8_t *klv,
                                        size_t len,
                                        int64_t pts_90khz);

/**
 * Snapshot stats for a `srtc_managed_mux_sender_t` into `*out`.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if either pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */

int srtc_managed_mux_sender_get_stats(struct srtc_managed_mux_sender_t *p,
                                      struct srtc_sender_stats_t *out);

/**
 * Reset stats counters for a `srtc_managed_mux_sender_t` to zero.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if the pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */
 int srtc_managed_mux_sender_reset_stats(struct srtc_managed_mux_sender_t *p);

 void srtc_managed_mux_sender_close(struct srtc_managed_mux_sender_t *p);

/**
 * Open a standalone muxer. Builds the config from `cfg` so the caller may
 * free it immediately after this returns. Returns NULL on failure with
 * last-error set.
 */
 struct srtc_muxer_t *srtc_muxer_open(struct srtc_mux_config_t *cfg);

/**
 * Push one Annex-B-framed video access unit. Returns 0 on success or a
 * negative SRTC_E_* code.
 */

int srtc_muxer_push_video(struct srtc_muxer_t *p,
                          const uint8_t *nal,
                          size_t len,
                          int64_t pts_90khz,
                          bool key_frame);

/**
 * Push one pre-built KLV blob.
 */
 int srtc_muxer_push_klv(struct srtc_muxer_t *p, const uint8_t *klv, size_t len, int64_t pts_90khz);

/**
 * Push one Annex-B NAL targeting a specific video elementary stream.
 *
 * `handle` is obtained from `srtc_mux_config_add_video_stream` at config
 * time and is stable across managed-sender reconnects. Out-of-range
 * handles surface as `SRTC_E_INVALID_USAGE` (carrying
 * `MuxError::InvalidStreamHandle`).
 *
 * On a single-stream muxer, prefer `srtc_muxer_push_video` — it has the
 * same effect and doesn't require a handle.
 */

int srtc_muxer_push_video_to(struct srtc_muxer_t *p,
                             srtc_video_stream_handle_t handle,
                             const uint8_t *nal,
                             size_t len,
                             int64_t pts_90khz,
                             bool key_frame);

/**
 * Push one pre-built KLV blob targeting a specific KLV elementary stream.
 *
 * `handle` is obtained from `srtc_mux_config_add_klv_stream`. Same
 * semantics as `srtc_muxer_push_video_to`.
 *
 * For `KlvStreamType::SynchronousMetadata` streams, callers must
 * pre-wrap the KLV via `srt_core::klv::st1910::wrap_au_cell` (or the
 * equivalent in their consumer language) — the muxer does NOT auto-wrap.
 */

int srtc_muxer_push_klv_to(struct srtc_muxer_t *p,
                           srtc_klv_stream_handle_t handle,
                           const uint8_t *klv,
                           size_t len,
                           int64_t pts_90khz);

/**
 * Drain TS bytes into `out_buf` (capacity `out_cap`). Returns the number
 * of bytes written; 0 means nothing was ready or the buffer was too
 * small for the next chunk. Never sets last-error — 0 is a normal return
 * value.
 */
 size_t srtc_muxer_pull(struct srtc_muxer_t *p, uint8_t *out_buf, size_t out_cap);

/**
 * Snapshot stats for a `srtc_muxer_t` into `*out`.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if either pointer is
 * null, or `SRTC_E_CLOSED` if the muxer has been closed.
 */
 int srtc_muxer_get_stats(struct srtc_muxer_t *p, struct srtc_muxer_stats_t *out);

/**
 * Reset stats counters for a `srtc_muxer_t` to zero.
 *
 * Per-stream entries are preserved (identity fields remain); only flow
 * counters (`items`, `bytes`, `discontinuities`) are zeroed.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if the pointer is
 * null, or `SRTC_E_CLOSED` if the muxer has been closed.
 */
 int srtc_muxer_reset_stats(struct srtc_muxer_t *p);

/**
 * Close and free the muxer. Idempotent — passing NULL is a no-op.
 */
 void srtc_muxer_close(struct srtc_muxer_t *p);

/**
 * Open a `srtc_raw_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `SRTC_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `srtc_get_last_error_str()` describes the specific problem.
 */

struct srtc_raw_sender_t *srtc_raw_sender_open(const char *srt_url,
                                               const struct srtc_raw_sender_config_t *cfg);

 int srtc_raw_sender_send(struct srtc_raw_sender_t *p, const uint8_t *bytes, size_t len);

 void srtc_raw_sender_close(struct srtc_raw_sender_t *p);

/**
 * Open a `srtc_managed_raw_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `SRTC_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `srtc_get_last_error_str()` describes the specific problem.
 */

struct srtc_managed_raw_sender_t *srtc_managed_raw_sender_open(const char *srt_url,
                                                               const struct srtc_raw_sender_config_t *cfg,
                                                               const struct srtc_reconnect_policy_t *policy);


int srtc_managed_raw_sender_send(struct srtc_managed_raw_sender_t *p,
                                 const uint8_t *bytes,
                                 size_t len);

 void srtc_managed_raw_sender_close(struct srtc_managed_raw_sender_t *p);

/**
 * Snapshot stats for a `srtc_raw_sender_t` into `*out`.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if either pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */
 int srtc_raw_sender_get_stats(struct srtc_raw_sender_t *p, struct srtc_raw_sender_stats_t *out);

/**
 * Reset stats counters for a `srtc_raw_sender_t` to zero.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if the pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */
 int srtc_raw_sender_reset_stats(struct srtc_raw_sender_t *p);

/**
 * Snapshot stats for a `srtc_managed_raw_sender_t` into `*out`.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if either pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */

int srtc_managed_raw_sender_get_stats(struct srtc_managed_raw_sender_t *p,
                                      struct srtc_raw_sender_stats_t *out);

/**
 * Reset stats counters for a `srtc_managed_raw_sender_t` to zero.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if the pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */
 int srtc_managed_raw_sender_reset_stats(struct srtc_managed_raw_sender_t *p);

/**
 * Open a `srtc_ts_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `SRTC_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `srtc_get_last_error_str()` describes the specific problem.
 */

struct srtc_ts_sender_t *srtc_ts_sender_open(const char *srt_url,
                                             const struct srtc_ts_sender_config_t *cfg);

 int srtc_ts_sender_send_ts(struct srtc_ts_sender_t *p, const uint8_t *bytes, size_t len);

 int srtc_ts_sender_flush(struct srtc_ts_sender_t *p);

 int srtc_ts_sender_get_stats(struct srtc_ts_sender_t *p, struct srtc_ts_sender_stats_t *out);

 int srtc_ts_sender_reset_stats(struct srtc_ts_sender_t *p);

 void srtc_ts_sender_close(struct srtc_ts_sender_t *p);

/**
 * Open a `srtc_managed_ts_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `SRTC_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `srtc_get_last_error_str()` describes the specific problem.
 */

struct srtc_managed_ts_sender_t *srtc_managed_ts_sender_open(const char *srt_url,
                                                             const struct srtc_ts_sender_config_t *cfg,
                                                             const struct srtc_reconnect_policy_t *policy);


int srtc_managed_ts_sender_send_ts(struct srtc_managed_ts_sender_t *p,
                                   const uint8_t *bytes,
                                   size_t len);

 int srtc_managed_ts_sender_flush(struct srtc_managed_ts_sender_t *p);


int srtc_managed_ts_sender_get_stats(struct srtc_managed_ts_sender_t *p,
                                     struct srtc_ts_sender_stats_t *out);

 int srtc_managed_ts_sender_reset_stats(struct srtc_managed_ts_sender_t *p);

 void srtc_managed_ts_sender_close(struct srtc_managed_ts_sender_t *p);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SRTC_H */
