/*
 * srtc.h — C ABI for the srt-core sender pipeline.
 *
 * This file is GENERATED by cbindgen. Do not edit manually.
 * Source of truth: crates/srt-c/src/ (Rust).
 *
 * Copyright (c) 2026 Andrew Klofas. Licensed under MIT OR Apache-2.0.
 */


#ifndef SRTC_H
#define SRTC_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>

/**
 * Major version (compile-time macro in the generated header).
 */
#define SRTC_VERSION_MAJOR 0

/**
 * Minor version.
 */
#define SRTC_VERSION_MINOR 1

/**
 * Patch version.
 */
#define SRTC_VERSION_PATCH 0

/**
 * Sentinel returned by `srtc_mux_config_add_*_stream` on failure.
 * On failure, the last-error is also populated; check
 * `srtc_get_last_error()` for the negative `SRTC_E_*` code.
 */
#define SRTC_INVALID_STREAM_HANDLE UINT32_MAX

/**
 * Maximum number of per-stream entries in any stats struct exposed at
 * the C ABI. Rarely exceeded — multi-stream `mpegts::mux` caps at
 * 16 video + 16 KLV = 32, leaving 32 slots of headroom for receiver
 * PSI + observed streams.
 */
#define SRTC_STATS_MAX_STREAMS 64

typedef enum srtc_video_codec {
  SRTC_VIDEO_CODEC_H264 = 0,
  SRTC_VIDEO_CODEC_H265 = 1,
} srtc_video_codec;

typedef enum srtc_klv_stream_type {
  SRTC_KLV_STREAM_TYPE_PRIVATE_DATA = 0,
  SRTC_KLV_STREAM_TYPE_SYNCHRONOUS_METADATA = 1,
} srtc_klv_stream_type;

typedef enum srtc_ts_framing_mode {
  SRTC_TS_FRAMING_MODE_RECOVER = 0,
  SRTC_TS_FRAMING_MODE_STRICT = 1,
} srtc_ts_framing_mode;

typedef enum srtc_overflow_policy {
  SRTC_OVERFLOW_POLICY_DROP_OLDEST = 0,
  SRTC_OVERFLOW_POLICY_REJECT = 1,
} srtc_overflow_policy;

/**
 * Negative codes returned by every fallible srt-c entry point.
 *
 * `Success = 0` is the only non-negative variant. Codes are stable
 * across srt-c versions; new codes append at the end.
 */
enum srtc_e
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  SRTC_E_SUCCESS = 0,
  SRTC_E_INVALID_CONFIG = -1,
  SRTC_E_INVALID_NAL = -2,
  SRTC_E_INVALID_TS = -3,
  SRTC_E_BUFFER_FULL = -4,
  SRTC_E_KLV_TOO_LARGE = -5,
  SRTC_E_TOO_LARGE = -6,
  SRTC_E_CLOSED = -7,
  SRTC_E_TRANSPORT = -8,
  SRTC_E_INVALID_USAGE = -9,
  SRTC_E_INTERNAL = -10,
};
#ifndef __cplusplus
typedef int32_t srtc_e;
#endif // __cplusplus

typedef struct srtc_managed_mux_sender_t srtc_managed_mux_sender_t;

typedef struct srtc_managed_raw_sender_t srtc_managed_raw_sender_t;

typedef struct srtc_managed_ts_sender_t srtc_managed_ts_sender_t;

/**
 * Opaque mux-config builder. Constructed via `srtc_mux_config_new`,
 * populated with setters, consumed by `srtc_*_open` (which clones the
 * inner). Caller is responsible for calling `srtc_mux_config_free`.
 *
 * Internally stores the accumulated state as a `ConfigBuilder` that has
 * already opened a single-program block via `add_program(1, 0x1000)`.
 * `build_config()` closes the program block and calls `.build()`.
 */
typedef struct srtc_mux_config_t srtc_mux_config_t;

typedef struct srtc_mux_sender_t srtc_mux_sender_t;

typedef struct srtc_muxer_t srtc_muxer_t;

typedef struct srtc_raw_sender_t srtc_raw_sender_t;

typedef struct srtc_raw_sender_config_t srtc_raw_sender_config_t;

typedef struct srtc_reconnect_policy_t srtc_reconnect_policy_t;

typedef struct srtc_ts_sender_t srtc_ts_sender_t;

typedef struct srtc_ts_sender_config_t srtc_ts_sender_config_t;

/**
 * Opaque per-program ordinal for a video elementary stream. Obtained from
 * [`srtc_mux_config_add_video_stream`] at config time and reused with the
 * `_video_to` push siblings on every muxer-owning C variant.
 *
 * Handles are stable across the config→open boundary and across managed
 * reconnects. They are NOT interchangeable between muxers — passing a
 * handle from one muxer to a different one yields `SRTC_E_INVALID_USAGE`
 * via `MuxError::InvalidStreamHandle` (the index simply happens to be
 * out of range on the new muxer in practice).
 */
typedef uint32_t srtc_video_stream_handle_t;

/**
 * Opaque per-program ordinal for a KLV elementary stream. See
 * [`SrtcVideoStreamHandle`] for semantics.
 */
typedef uint32_t srtc_klv_stream_handle_t;

/**
 * `repr(C)` mirror of `srt_core::mpegts::StreamStats`. Size 96 B.
 */
typedef struct srtc_stream_stats_t {
  uint64_t items;
  uint64_t bytes;
  uint64_t discontinuities;
  uint16_t pid;
  uint8_t stream_type;
  uint8_t _pad[5];
  /**
   * NUL-terminated UTF-8. label[0]==0 means None. Truncated at 63
   * bytes (first 63 + NUL).
   */
  char label[64];
} srtc_stream_stats_t;

/**
 * `repr(C)` mirror of `srt_core::pipeline::SenderStats`. Size 6184 B.
 */
typedef struct srtc_sender_stats_t {
  uint64_t bytes_sent;
  uint64_t packets_sent;
  uint64_t pending_bytes_queued;
  uint64_t pending_chunks_queued;
  uint32_t per_stream_count;
  uint32_t per_stream_truncated;
  struct srtc_stream_stats_t per_stream[SRTC_STATS_MAX_STREAMS];
} srtc_sender_stats_t;

/**
 * `repr(C)` mirror of `srt_core::mpegts::mux::MuxerStats`. Size 6168 B.
 */
typedef struct srtc_muxer_stats_t {
  uint64_t ts_packets_emitted;
  uint64_t ts_bytes_emitted;
  uint32_t per_stream_count;
  uint32_t per_stream_truncated;
  struct srtc_stream_stats_t per_stream[SRTC_STATS_MAX_STREAMS];
} srtc_muxer_stats_t;

/**
 * `repr(C)` mirror of `srt_core::pipeline::RawSenderStats`. Size 16 B.
 */
typedef struct srtc_raw_sender_stats_t {
  uint64_t bytes_sent;
  uint64_t packets_sent;
} srtc_raw_sender_stats_t;

/**
 * Public-ABI mirror of `srt_core::pipeline::TsSenderStats`. Same fields,
 * same units. Caller passes a pointer to a stack-allocated struct;
 * `srtc_ts_sender_get_stats` fills it in.
 */
typedef struct srtc_ts_sender_stats_t {
  uint64_t bytes_pushed;
  uint64_t bytes_skipped_for_sync;
  uint64_t resync_events;
  uint64_t packets_sent;
} srtc_ts_sender_stats_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

 struct srtc_mux_config_t *srtc_mux_config_new(void);

 void srtc_mux_config_free(struct srtc_mux_config_t *p);


int srtc_mux_config_add_video(struct srtc_mux_config_t *p,
                              uint16_t pid,
                              enum srtc_video_codec codec);


int srtc_mux_config_add_klv(struct srtc_mux_config_t *p,
                            uint16_t pid,
                            enum srtc_klv_stream_type stream_type,
                            bool carries_pts);

/**
 * Add a video elementary stream to the mux config and return its handle.
 *
 * Returns the stream handle (a zero-based ordinal) on success. The handle is
 * stable across the config→open boundary and across managed-sender reconnects,
 * and can be passed to the `_video_to` push siblings to fan out to a specific
 * elementary stream.
 *
 * Returns `SRTC_INVALID_STREAM_HANDLE` and sets last-error on null pointer.
 * Cap-violation errors (`TooManyVideoStreams`) surface at `_open` time, not
 * here, so this function always succeeds on a valid pointer.
 */

srtc_video_stream_handle_t srtc_mux_config_add_video_stream(struct srtc_mux_config_t *p,
                                                            uint16_t pid,
                                                            enum srtc_video_codec codec);

/**
 * Add a KLV elementary stream to the mux config and return its handle.
 *
 * Returns the stream handle (a zero-based ordinal) on success. The handle is
 * stable across the config→open boundary and across managed-sender reconnects,
 * and can be passed to the `_klv_to` push siblings to fan out to a specific
 * elementary stream.
 *
 * Returns `SRTC_INVALID_STREAM_HANDLE` and sets last-error on null pointer.
 * Cap-violation errors (`TooManyKlvStreams`) surface at `_open` time, not
 * here, so this function always succeeds on a valid pointer.
 */

srtc_klv_stream_handle_t srtc_mux_config_add_klv_stream(struct srtc_mux_config_t *p,
                                                        uint16_t pid,
                                                        enum srtc_klv_stream_type stream_type,
                                                        bool carries_pts);

 int srtc_mux_config_set_pcr_pid(struct srtc_mux_config_t *p, uint16_t pid);

 int srtc_mux_config_set_pcr_interval_ms(struct srtc_mux_config_t *p, uint32_t ms);

 int srtc_mux_config_set_psi_interval_ms(struct srtc_mux_config_t *p, uint32_t ms);

 int srtc_mux_config_set_buffer_packets(struct srtc_mux_config_t *p, size_t n);

 struct srtc_ts_sender_config_t *srtc_ts_sender_config_new(void);

 void srtc_ts_sender_config_free(struct srtc_ts_sender_config_t *p);


int srtc_ts_sender_config_set_framing_mode(struct srtc_ts_sender_config_t *p,
                                           enum srtc_ts_framing_mode mode);

 int srtc_ts_sender_config_set_max_unsynced_bytes(struct srtc_ts_sender_config_t *p, size_t n);

 struct srtc_raw_sender_config_t *srtc_raw_sender_config_new(void);

 void srtc_raw_sender_config_free(struct srtc_raw_sender_config_t *p);

 struct srtc_reconnect_policy_t *srtc_reconnect_policy_new(void);

 void srtc_reconnect_policy_free(struct srtc_reconnect_policy_t *p);

/**
 * Set max reconnect attempts. `n < 0` means retry forever.
 */
 int srtc_reconnect_policy_set_max_attempts(struct srtc_reconnect_policy_t *p, int32_t n);

 int srtc_reconnect_policy_set_backoff_constant_ms(struct srtc_reconnect_policy_t *p, uint32_t ms);


int srtc_reconnect_policy_set_backoff_exponential_ms(struct srtc_reconnect_policy_t *p,
                                                     uint32_t base_ms,
                                                     uint32_t max_ms);

 int srtc_reconnect_policy_set_gap_buffer_capacity(struct srtc_reconnect_policy_t *p, size_t n);


int srtc_reconnect_policy_set_overflow_policy(struct srtc_reconnect_policy_t *p,
                                              enum srtc_overflow_policy policy);

/**
 * Read the most recent error code on this thread. Returns `0`
 * (`SRTC_E_SUCCESS`) if no error has been recorded on this thread yet.
 * The value is not cleared by successful calls; it reflects the most
 * recent failure on this thread (or `SRTC_E_SUCCESS` if there has been
 * none since thread start).
 */
 int srtc_get_last_error(void);

/**
 * Pointer to the most recent error message on this thread. Valid until
 * the next srt-c call on the same thread. Never NULL — empty string when
 * no error.
 */
 const char *srtc_get_last_error_str(void);

/**
 * Open a `srtc_mux_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `SRTC_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `srtc_get_last_error_str()` describes the specific problem.
 */
 struct srtc_mux_sender_t *srtc_mux_sender_open(const char *srt_url, struct srtc_mux_config_t *cfg);


int srtc_mux_sender_send_video(struct srtc_mux_sender_t *p,
                               const uint8_t *nal,
                               size_t len,
                               int64_t pts_90khz,
                               bool key_frame);


int srtc_mux_sender_send_klv(struct srtc_mux_sender_t *p,
                             const uint8_t *klv,
                             size_t len,
                             int64_t pts_90khz);

/**
 * Push one Annex-B NAL targeting a specific video elementary stream.
 *
 * `stream_handle` is obtained from `srtc_mux_config_add_video_stream` at
 * config time and is stable across the config→open boundary. Out-of-range
 * handles surface as `SRTC_E_INVALID_USAGE` (carrying
 * `MuxError::InvalidStreamHandle`).
 *
 * On a single-stream sender, prefer `srtc_mux_sender_send_video` — same
 * effect, no handle required.
 */

int srtc_mux_sender_send_video_to(struct srtc_mux_sender_t *p,
                                  srtc_video_stream_handle_t stream_handle,
                                  const uint8_t *nal,
                                  size_t len,
                                  int64_t pts_90khz,
                                  bool key_frame);

/**
 * Push one pre-built KLV blob targeting a specific KLV elementary stream.
 *
 * For `KlvStreamType::SynchronousMetadata` streams, callers must
 * pre-wrap the KLV via `srt_core::klv::st1910::wrap_au_cell` — the
 * muxer does not auto-wrap.
 *
 * On a single-stream sender, prefer `srtc_mux_sender_send_klv` — same
 * effect, no handle required.
 */

int srtc_mux_sender_send_klv_to(struct srtc_mux_sender_t *p,
                                srtc_klv_stream_handle_t stream_handle,
                                const uint8_t *klv,
                                size_t len,
                                int64_t pts_90khz);

/**
 * Snapshot stats for a `srtc_mux_sender_t` into `*out`.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if either pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */
 int srtc_mux_sender_get_stats(struct srtc_mux_sender_t *p, struct srtc_sender_stats_t *out);

/**
 * Reset stats counters for a `srtc_mux_sender_t` to zero.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if the pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */
 int srtc_mux_sender_reset_stats(struct srtc_mux_sender_t *p);

 void srtc_mux_sender_close(struct srtc_mux_sender_t *p);

/**
 * Open a `srtc_managed_mux_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `SRTC_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `srtc_get_last_error_str()` describes the specific problem.
 */

struct srtc_managed_mux_sender_t *srtc_managed_mux_sender_open(const char *srt_url,
                                                               struct srtc_mux_config_t *cfg,
                                                               const struct srtc_reconnect_policy_t *policy);


int srtc_managed_mux_sender_send_video(struct srtc_managed_mux_sender_t *p,
                                       const uint8_t *nal,
                                       size_t len,
                                       int64_t pts_90khz,
                                       bool key_frame);


int srtc_managed_mux_sender_send_klv(struct srtc_managed_mux_sender_t *p,
                                     const uint8_t *klv,
                                     size_t len,
                                     int64_t pts_90khz);

/**
 * Push one Annex-B NAL targeting a specific video elementary stream on a
 * managed (auto-reconnecting) sender.
 *
 * `stream_handle` is obtained from `srtc_mux_config_add_video_stream` at
 * config time and is stable across reconnects. Out-of-range handles
 * surface as `SRTC_E_INVALID_USAGE` (carrying
 * `MuxError::InvalidStreamHandle`).
 *
 * On a single-stream sender, prefer `srtc_managed_mux_sender_send_video` —
 * same effect, no handle required.
 */

int srtc_managed_mux_sender_send_video_to(struct srtc_managed_mux_sender_t *p,
                                          srtc_video_stream_handle_t stream_handle,
                                          const uint8_t *nal,
                                          size_t len,
                                          int64_t pts_90khz,
                                          bool key_frame);

/**
 * Push one pre-built KLV blob targeting a specific KLV elementary stream on
 * a managed (auto-reconnecting) sender.
 *
 * For `KlvStreamType::SynchronousMetadata` streams, callers must
 * pre-wrap the KLV via `srt_core::klv::st1910::wrap_au_cell` — the
 * muxer does not auto-wrap.
 *
 * On a single-stream sender, prefer `srtc_managed_mux_sender_send_klv` —
 * same effect, no handle required.
 */

int srtc_managed_mux_sender_send_klv_to(struct srtc_managed_mux_sender_t *p,
                                        srtc_klv_stream_handle_t stream_handle,
                                        const uint8_t *klv,
                                        size_t len,
                                        int64_t pts_90khz);

/**
 * Snapshot stats for a `srtc_managed_mux_sender_t` into `*out`.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if either pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */

int srtc_managed_mux_sender_get_stats(struct srtc_managed_mux_sender_t *p,
                                      struct srtc_sender_stats_t *out);

/**
 * Reset stats counters for a `srtc_managed_mux_sender_t` to zero.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if the pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */
 int srtc_managed_mux_sender_reset_stats(struct srtc_managed_mux_sender_t *p);

 void srtc_managed_mux_sender_close(struct srtc_managed_mux_sender_t *p);

/**
 * Open a standalone muxer. Builds the config from `cfg` so the caller may
 * free it immediately after this returns. Returns NULL on failure with
 * last-error set.
 */
 struct srtc_muxer_t *srtc_muxer_open(struct srtc_mux_config_t *cfg);

/**
 * Push one Annex-B-framed video access unit. Returns 0 on success or a
 * negative SRTC_E_* code.
 */

int srtc_muxer_push_video(struct srtc_muxer_t *p,
                          const uint8_t *nal,
                          size_t len,
                          int64_t pts_90khz,
                          bool key_frame);

/**
 * Push one pre-built KLV blob.
 */
 int srtc_muxer_push_klv(struct srtc_muxer_t *p, const uint8_t *klv, size_t len, int64_t pts_90khz);

/**
 * Push one Annex-B NAL targeting a specific video elementary stream.
 *
 * `handle` is obtained from `srtc_mux_config_add_video_stream` at config
 * time and is stable across managed-sender reconnects. Out-of-range
 * handles surface as `SRTC_E_INVALID_USAGE` (carrying
 * `MuxError::InvalidStreamHandle`).
 *
 * On a single-stream muxer, prefer `srtc_muxer_push_video` — it has the
 * same effect and doesn't require a handle.
 */

int srtc_muxer_push_video_to(struct srtc_muxer_t *p,
                             srtc_video_stream_handle_t handle,
                             const uint8_t *nal,
                             size_t len,
                             int64_t pts_90khz,
                             bool key_frame);

/**
 * Push one pre-built KLV blob targeting a specific KLV elementary stream.
 *
 * `handle` is obtained from `srtc_mux_config_add_klv_stream`. Same
 * semantics as `srtc_muxer_push_video_to`.
 *
 * For `KlvStreamType::SynchronousMetadata` streams, callers must
 * pre-wrap the KLV via `srt_core::klv::st1910::wrap_au_cell` (or the
 * equivalent in their consumer language) — the muxer does NOT auto-wrap.
 */

int srtc_muxer_push_klv_to(struct srtc_muxer_t *p,
                           srtc_klv_stream_handle_t handle,
                           const uint8_t *klv,
                           size_t len,
                           int64_t pts_90khz);

/**
 * Drain TS bytes into `out_buf` (capacity `out_cap`). Returns the number
 * of bytes written; 0 means nothing was ready or the buffer was too
 * small for the next chunk. Never sets last-error — 0 is a normal return
 * value.
 */
 size_t srtc_muxer_pull(struct srtc_muxer_t *p, uint8_t *out_buf, size_t out_cap);

/**
 * Snapshot stats for a `srtc_muxer_t` into `*out`.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if either pointer is
 * null, or `SRTC_E_CLOSED` if the muxer has been closed.
 */
 int srtc_muxer_get_stats(struct srtc_muxer_t *p, struct srtc_muxer_stats_t *out);

/**
 * Reset stats counters for a `srtc_muxer_t` to zero.
 *
 * Per-stream entries are preserved (identity fields remain); only flow
 * counters (`items`, `bytes`, `discontinuities`) are zeroed.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if the pointer is
 * null, or `SRTC_E_CLOSED` if the muxer has been closed.
 */
 int srtc_muxer_reset_stats(struct srtc_muxer_t *p);

/**
 * Close and free the muxer. Idempotent — passing NULL is a no-op.
 */
 void srtc_muxer_close(struct srtc_muxer_t *p);

/**
 * Open a `srtc_raw_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `SRTC_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `srtc_get_last_error_str()` describes the specific problem.
 */

struct srtc_raw_sender_t *srtc_raw_sender_open(const char *srt_url,
                                               const struct srtc_raw_sender_config_t *cfg);

 int srtc_raw_sender_send(struct srtc_raw_sender_t *p, const uint8_t *bytes, size_t len);

 void srtc_raw_sender_close(struct srtc_raw_sender_t *p);

/**
 * Open a `srtc_managed_raw_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `SRTC_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `srtc_get_last_error_str()` describes the specific problem.
 */

struct srtc_managed_raw_sender_t *srtc_managed_raw_sender_open(const char *srt_url,
                                                               const struct srtc_raw_sender_config_t *cfg,
                                                               const struct srtc_reconnect_policy_t *policy);


int srtc_managed_raw_sender_send(struct srtc_managed_raw_sender_t *p,
                                 const uint8_t *bytes,
                                 size_t len);

 void srtc_managed_raw_sender_close(struct srtc_managed_raw_sender_t *p);

/**
 * Snapshot stats for a `srtc_raw_sender_t` into `*out`.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if either pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */
 int srtc_raw_sender_get_stats(struct srtc_raw_sender_t *p, struct srtc_raw_sender_stats_t *out);

/**
 * Reset stats counters for a `srtc_raw_sender_t` to zero.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if the pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */
 int srtc_raw_sender_reset_stats(struct srtc_raw_sender_t *p);

/**
 * Snapshot stats for a `srtc_managed_raw_sender_t` into `*out`.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if either pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */

int srtc_managed_raw_sender_get_stats(struct srtc_managed_raw_sender_t *p,
                                      struct srtc_raw_sender_stats_t *out);

/**
 * Reset stats counters for a `srtc_managed_raw_sender_t` to zero.
 *
 * Returns 0 on success, `SRTC_E_INVALID_CONFIG` if the pointer is
 * null, or `SRTC_E_CLOSED` if the sender has been closed.
 */
 int srtc_managed_raw_sender_reset_stats(struct srtc_managed_raw_sender_t *p);

/**
 * Open a `srtc_ts_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `SRTC_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `srtc_get_last_error_str()` describes the specific problem.
 */

struct srtc_ts_sender_t *srtc_ts_sender_open(const char *srt_url,
                                             const struct srtc_ts_sender_config_t *cfg);

 int srtc_ts_sender_send_ts(struct srtc_ts_sender_t *p, const uint8_t *bytes, size_t len);

 int srtc_ts_sender_flush(struct srtc_ts_sender_t *p);

 int srtc_ts_sender_get_stats(struct srtc_ts_sender_t *p, struct srtc_ts_sender_stats_t *out);

 int srtc_ts_sender_reset_stats(struct srtc_ts_sender_t *p);

 void srtc_ts_sender_close(struct srtc_ts_sender_t *p);

/**
 * Open a `srtc_managed_ts_sender_t` connected via SRT.
 *
 * `srt_url` is a `srt://host:port?key=value&...` URL. Query
 * parameters apply libsrt-vocabulary options to the connection
 * (passphrase, latency, streamid, etc.). URL values override config
 * values for the same option. See
 * `docs/guide-srt.md#url-parsing` for the recognized key table.
 *
 * Returns `NULL` with `SRTC_E_INVALID_CONFIG` set in the thread-local
 * last-error for any malformed URL, unsupported key, unknown key, or
 * invalid value. The detail string from
 * `srtc_get_last_error_str()` describes the specific problem.
 */

struct srtc_managed_ts_sender_t *srtc_managed_ts_sender_open(const char *srt_url,
                                                             const struct srtc_ts_sender_config_t *cfg,
                                                             const struct srtc_reconnect_policy_t *policy);


int srtc_managed_ts_sender_send_ts(struct srtc_managed_ts_sender_t *p,
                                   const uint8_t *bytes,
                                   size_t len);

 int srtc_managed_ts_sender_flush(struct srtc_managed_ts_sender_t *p);


int srtc_managed_ts_sender_get_stats(struct srtc_managed_ts_sender_t *p,
                                     struct srtc_ts_sender_stats_t *out);

 int srtc_managed_ts_sender_reset_stats(struct srtc_managed_ts_sender_t *p);

 void srtc_managed_ts_sender_close(struct srtc_managed_ts_sender_t *p);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SRTC_H */
