"""Type stubs for tstrans.codec — see codec.py for the runtime + full docstrings.

Covers the shared codec enums and value types (ChromaFormat, colour signalling,
Rational, ColorInfo), the typed NAL / OBU wrappers, the per-codec parameter-set
and slice-header-light classes (H.264 / H.265 / H.266), the AV1 sequence /
frame-header classes, the AAC + MPEG-2 audio frame classes and their iterators,
all the parse_* / iter_* functions, and the raw-first split_units / parse_audio
entry points (v0.2.0 item #1).

The *_np properties (payload_np / raw_rbsp_np / raw_np) are attached at runtime
by codec.py and return numpy.ndarray; they are typed Any here so the stubs never
import numpy (which is an optional [pandas] extra).

mypy --strict clean.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Tuple, Union, final

# Bytes-like input accepted by the parsers. PyO3's &[u8] extractor takes any
# buffer-protocol object; the raw-first entry points also accept SharedBytes-
# backed views. Typed broadly to match that runtime flexibility. Private
# (leading underscore) so stubtest doesn't treat it as a public runtime member.
_BytesLike = Union[bytes, bytearray, memoryview]

# --- shared enums (PyO3 eq_int #[pyclass] — plain classes, members are
#     instances of the class itself; NOT enum.IntEnum) ---

@final
class ChromaFormat:
    MONOCHROME: ChromaFormat
    YUV420: ChromaFormat
    YUV422: ChromaFormat
    YUV444: ChromaFormat
    INVALID: ChromaFormat

@final
class ColourPrimaries:
    BT709: ColourPrimaries
    UNSPECIFIED: ColourPrimaries
    BT470M: ColourPrimaries
    BT470BG: ColourPrimaries
    SMPTE170M: ColourPrimaries
    SMPTE240M: ColourPrimaries
    FILM: ColourPrimaries
    BT2020: ColourPrimaries
    SMPTE_ST428: ColourPrimaries
    SMPTE_ST431_2: ColourPrimaries
    SMPTE_ST432_1: ColourPrimaries
    EBU3213E: ColourPrimaries
    RESERVED: ColourPrimaries

@final
class TransferCharacteristics:
    BT709: TransferCharacteristics
    UNSPECIFIED: TransferCharacteristics
    GAMMA22: TransferCharacteristics
    GAMMA28: TransferCharacteristics
    SMPTE170M: TransferCharacteristics
    SMPTE240M: TransferCharacteristics
    LINEAR: TransferCharacteristics
    LOG100: TransferCharacteristics
    LOG_SQRT: TransferCharacteristics
    IEC61966_2_4: TransferCharacteristics
    BT1361E: TransferCharacteristics
    IEC61966_2_1: TransferCharacteristics
    BT2020_BITS10: TransferCharacteristics
    BT2020_BITS12: TransferCharacteristics
    SMPTE_ST2084: TransferCharacteristics
    SMPTE_ST428: TransferCharacteristics
    ARIB_STD_B67: TransferCharacteristics
    RESERVED: TransferCharacteristics

@final
class MatrixCoefficients:
    IDENTITY: MatrixCoefficients
    BT709: MatrixCoefficients
    UNSPECIFIED: MatrixCoefficients
    FCC_MC: MatrixCoefficients
    BT470BG: MatrixCoefficients
    SMPTE170M: MatrixCoefficients
    SMPTE240M: MatrixCoefficients
    YCGCO: MatrixCoefficients
    BT2020_NON_CONSTANT: MatrixCoefficients
    BT2020_CONSTANT: MatrixCoefficients
    SMPTE_ST2085: MatrixCoefficients
    CHROMA_DERIVED_NON_CONSTANT: MatrixCoefficients
    CHROMA_DERIVED_CONSTANT: MatrixCoefficients
    ICTCP: MatrixCoefficients
    IPT_C2: MatrixCoefficients
    YCGCO_RE: MatrixCoefficients
    YCGCO_RO: MatrixCoefficients
    RESERVED: MatrixCoefficients

# --- shared value types ---

@final
class Rational:
    def __new__(cls, num: int, den: int) -> Rational: ...
    @property
    def num(self) -> int: ...
    @property
    def den(self) -> int: ...
    def as_float(self) -> float: ...

@final
class ColorInfo:
    def __new__(
        cls,
        primaries: ColourPrimaries,
        transfer: TransferCharacteristics,
        matrix: MatrixCoefficients,
        full_range: bool,
    ) -> ColorInfo: ...
    @property
    def primaries(self) -> ColourPrimaries: ...
    @property
    def transfer(self) -> TransferCharacteristics: ...
    @property
    def matrix(self) -> MatrixCoefficients: ...
    @property
    def full_range(self) -> bool: ...

# --- typed NAL / OBU wrappers ---

@final
class NalUnit:
    @staticmethod
    def h264(nal_type: int, ref_idc: int, payload: _BytesLike) -> NalUnit: ...
    @staticmethod
    def h265(
        nal_type: int, layer_id: int, temporal_id_plus1: int, payload: _BytesLike
    ) -> NalUnit: ...
    @staticmethod
    def h266(
        nal_type: int, layer_id: int, temporal_id_plus1: int, payload: _BytesLike
    ) -> NalUnit: ...
    @property
    def kind(self) -> str: ...
    @property
    def nal_type(self) -> int: ...
    @property
    def ref_idc(self) -> Optional[int]: ...
    @property
    def layer_id(self) -> Optional[int]: ...
    @property
    def temporal_id_plus1(self) -> Optional[int]: ...
    @property
    def payload(self) -> bytes: ...
    @property
    def payload_np(self) -> Any: ...

@final
class ObuExtension:
    def __new__(cls, temporal_id: int, spatial_id: int) -> ObuExtension: ...
    @property
    def temporal_id(self) -> int: ...
    @property
    def spatial_id(self) -> int: ...

@final
class Obu:
    def __new__(
        cls, obu_type: int, extension: Optional[ObuExtension], payload: _BytesLike
    ) -> Obu: ...
    @property
    def obu_type(self) -> int: ...
    @property
    def extension(self) -> Optional[ObuExtension]: ...
    @property
    def payload(self) -> bytes: ...
    @property
    def payload_np(self) -> Any: ...

# --- H.264 ---

@final
class EntropyCodingMode:
    CAVLC: EntropyCodingMode
    CABAC: EntropyCodingMode

@final
class H264SliceType:
    P: H264SliceType
    B: H264SliceType
    I: H264SliceType
    Sp: H264SliceType
    Si: H264SliceType
    Unknown: H264SliceType

@final
class H264Sps:
    @property
    def seq_parameter_set_id(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def profile_idc(self) -> int: ...
    @property
    def level_idc(self) -> int: ...
    @property
    def constraint_set_flags(self) -> int: ...
    @property
    def bit_depth_luma(self) -> int: ...
    @property
    def bit_depth_chroma(self) -> int: ...
    @property
    def chroma_format(self) -> ChromaFormat: ...
    @property
    def frame_mbs_only(self) -> bool: ...
    @property
    def fixed_frame_rate(self) -> bool: ...
    @property
    def has_b_frames(self) -> bool: ...
    @property
    def frame_rate(self) -> Optional[Rational]: ...
    @property
    def color(self) -> Optional[ColorInfo]: ...
    @property
    def crop_left(self) -> int: ...
    @property
    def crop_right(self) -> int: ...
    @property
    def crop_top(self) -> int: ...
    @property
    def crop_bottom(self) -> int: ...
    @property
    def log2_max_frame_num_minus4(self) -> int: ...
    @property
    def raw_rbsp(self) -> bytes: ...
    @property
    def raw_rbsp_np(self) -> Any: ...
    def coded_width(self) -> int: ...
    def coded_height(self) -> int: ...

@final
class H264Pps:
    @property
    def pic_parameter_set_id(self) -> int: ...
    @property
    def seq_parameter_set_id(self) -> int: ...
    @property
    def entropy_coding_mode(self) -> EntropyCodingMode: ...
    @property
    def raw_rbsp(self) -> bytes: ...
    @property
    def raw_rbsp_np(self) -> Any: ...

@final
class H264SliceHeaderLight:
    @property
    def first_in_pic(self) -> bool: ...
    @property
    def slice_type(self) -> H264SliceType: ...
    @property
    def pps_id(self) -> int: ...
    @property
    def frame_num(self) -> Optional[int]: ...
    @property
    def idr(self) -> bool: ...
    @property
    def raw_rbsp(self) -> bytes: ...
    @property
    def raw_rbsp_np(self) -> Any: ...

@final
class H264ParameterSets:
    @property
    def sps_by_id(self) -> Dict[int, H264Sps]: ...
    @property
    def pps_by_id(self) -> Dict[int, H264Pps]: ...

def parse_h264_sps(rbsp: _BytesLike) -> H264Sps: ...
def parse_h264_pps(rbsp: _BytesLike) -> H264Pps: ...
def parse_h264_parameter_sets(nals: List[NalUnit]) -> H264ParameterSets: ...
def parse_h264_slice_header_light(
    rbsp: _BytesLike, sps: Optional[H264Sps], nal_unit_type: int
) -> H264SliceHeaderLight: ...

# --- H.265 ---

@final
class H265SliceType:
    B: H265SliceType
    P: H265SliceType
    I: H265SliceType
    Unknown: H265SliceType

@final
class H265ProfileTierLevel:
    @property
    def general_profile_space(self) -> int: ...
    @property
    def general_tier_flag(self) -> bool: ...
    @property
    def general_profile_idc(self) -> int: ...
    @property
    def general_profile_compatibility_flags(self) -> int: ...
    @property
    def general_progressive_source_flag(self) -> bool: ...
    @property
    def general_interlaced_source_flag(self) -> bool: ...
    @property
    def general_non_packed_constraint_flag(self) -> bool: ...
    @property
    def general_frame_only_constraint_flag(self) -> bool: ...
    @property
    def general_level_idc(self) -> int: ...

@final
class H265Sps:
    @property
    def sps_seq_parameter_set_id(self) -> int: ...
    @property
    def sps_video_parameter_set_id(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def general_profile_idc(self) -> int: ...
    @property
    def general_tier_flag(self) -> bool: ...
    @property
    def general_level_idc(self) -> int: ...
    @property
    def general_profile_compatibility_flags(self) -> int: ...
    @property
    def general_progressive_source_flag(self) -> bool: ...
    @property
    def general_interlaced_source_flag(self) -> bool: ...
    @property
    def general_non_packed_constraint_flag(self) -> bool: ...
    @property
    def general_frame_only_constraint_flag(self) -> bool: ...
    @property
    def bit_depth_luma(self) -> int: ...
    @property
    def bit_depth_chroma(self) -> int: ...
    @property
    def chroma_format(self) -> ChromaFormat: ...
    @property
    def max_sub_layers_minus1(self) -> int: ...
    @property
    def frame_rate(self) -> Optional[Rational]: ...
    @property
    def color(self) -> Optional[ColorInfo]: ...
    @property
    def crop_left(self) -> int: ...
    @property
    def crop_right(self) -> int: ...
    @property
    def crop_top(self) -> int: ...
    @property
    def crop_bottom(self) -> int: ...
    @property
    def log2_max_pic_order_cnt_lsb_minus4(self) -> int: ...
    @property
    def raw_rbsp(self) -> bytes: ...
    @property
    def raw_rbsp_np(self) -> Any: ...
    def profile_tier_level(self) -> H265ProfileTierLevel: ...
    def coded_width(self) -> int: ...
    def coded_height(self) -> int: ...

@final
class H265Pps:
    @property
    def pps_pic_parameter_set_id(self) -> int: ...
    @property
    def pps_seq_parameter_set_id(self) -> int: ...
    @property
    def raw_rbsp(self) -> bytes: ...
    @property
    def raw_rbsp_np(self) -> Any: ...

@final
class H265Vps:
    @property
    def vps_video_parameter_set_id(self) -> int: ...
    @property
    def max_layers_minus1(self) -> int: ...
    @property
    def max_sub_layers_minus1(self) -> int: ...
    @property
    def temporal_id_nesting_flag(self) -> bool: ...
    @property
    def general_profile_idc(self) -> int: ...
    @property
    def general_tier_flag(self) -> bool: ...
    @property
    def general_level_idc(self) -> int: ...
    @property
    def general_profile_compatibility_flags(self) -> int: ...
    @property
    def general_progressive_source_flag(self) -> bool: ...
    @property
    def general_interlaced_source_flag(self) -> bool: ...
    @property
    def general_non_packed_constraint_flag(self) -> bool: ...
    @property
    def general_frame_only_constraint_flag(self) -> bool: ...
    @property
    def raw_rbsp(self) -> bytes: ...
    @property
    def raw_rbsp_np(self) -> Any: ...
    def profile_tier_level(self) -> H265ProfileTierLevel: ...

@final
class H265SliceHeaderLight:
    @property
    def first_in_pic(self) -> bool: ...
    @property
    def slice_type(self) -> H265SliceType: ...
    @property
    def pps_id(self) -> int: ...
    @property
    def pic_order_cnt_lsb(self) -> Optional[int]: ...
    @property
    def idr(self) -> bool: ...
    @property
    def raw_rbsp(self) -> bytes: ...
    @property
    def raw_rbsp_np(self) -> Any: ...

@final
class H265ParameterSets:
    @property
    def vps_by_id(self) -> Dict[int, H265Vps]: ...
    @property
    def sps_by_id(self) -> Dict[int, H265Sps]: ...
    @property
    def pps_by_id(self) -> Dict[int, H265Pps]: ...

def parse_h265_sps(rbsp: _BytesLike) -> H265Sps: ...
def parse_h265_pps(rbsp: _BytesLike) -> H265Pps: ...
def parse_h265_vps(rbsp: _BytesLike) -> H265Vps: ...
def parse_h265_parameter_sets(nals: List[NalUnit]) -> H265ParameterSets: ...
def parse_h265_slice_header_light(
    rbsp: _BytesLike, sps: Optional[H265Sps], nal_unit_type: int
) -> H265SliceHeaderLight: ...

# --- H.266 / VVC ---

@final
class H266SliceType:
    B: H266SliceType
    P: H266SliceType
    I: H266SliceType
    Unknown: H266SliceType

@final
class H266ProfileTierLevel:
    @property
    def general_profile_idc(self) -> int: ...
    @property
    def general_tier_flag(self) -> bool: ...
    @property
    def general_level_idc(self) -> int: ...

@final
class H266Sps:
    @property
    def sps_id(self) -> int: ...
    @property
    def vps_id(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def general_profile_idc(self) -> int: ...
    @property
    def general_tier_flag(self) -> bool: ...
    @property
    def general_level_idc(self) -> int: ...
    @property
    def bit_depth_luma(self) -> int: ...
    @property
    def bit_depth_chroma(self) -> int: ...
    @property
    def chroma_format(self) -> ChromaFormat: ...
    @property
    def frame_rate(self) -> Optional[Rational]: ...
    @property
    def color(self) -> Optional[ColorInfo]: ...
    @property
    def crop_left(self) -> int: ...
    @property
    def crop_right(self) -> int: ...
    @property
    def crop_top(self) -> int: ...
    @property
    def crop_bottom(self) -> int: ...
    @property
    def raw_rbsp(self) -> bytes: ...
    @property
    def raw_rbsp_np(self) -> Any: ...
    def profile_tier_level(self) -> H266ProfileTierLevel: ...
    def coded_width(self) -> int: ...
    def coded_height(self) -> int: ...

@final
class H266Pps:
    @property
    def pps_id(self) -> int: ...
    @property
    def sps_id(self) -> int: ...
    @property
    def raw_rbsp(self) -> bytes: ...
    @property
    def raw_rbsp_np(self) -> Any: ...

@final
class H266Vps:
    @property
    def vps_id(self) -> int: ...
    @property
    def max_layers(self) -> int: ...
    @property
    def max_sub_layers(self) -> int: ...
    @property
    def raw_rbsp(self) -> bytes: ...
    @property
    def raw_rbsp_np(self) -> Any: ...

@final
class H266SliceHeaderLight:
    @property
    def first_in_pic(self) -> bool: ...
    @property
    def slice_type(self) -> H266SliceType: ...
    @property
    def pps_id(self) -> int: ...
    @property
    def pic_order_cnt_lsb(self) -> Optional[int]: ...
    @property
    def idr(self) -> bool: ...
    @property
    def raw_rbsp(self) -> bytes: ...
    @property
    def raw_rbsp_np(self) -> Any: ...

@final
class H266ParameterSets:
    @property
    def vpses(self) -> List[H266Vps]: ...
    @property
    def spses(self) -> List[H266Sps]: ...
    @property
    def ppses(self) -> List[H266Pps]: ...

def parse_h266_sps(rbsp: _BytesLike) -> H266Sps: ...
def parse_h266_pps(rbsp: _BytesLike) -> H266Pps: ...
def parse_h266_vps(rbsp: _BytesLike) -> H266Vps: ...
def parse_h266_parameter_sets(nals: List[NalUnit]) -> H266ParameterSets: ...
def parse_h266_slice_header_light(
    rbsp: _BytesLike, sps: Optional[H266Sps], nal_unit_type: int
) -> H266SliceHeaderLight: ...

# --- AV1 ---

@final
class Av1SequenceHeader:
    @property
    def profile(self) -> int: ...
    @property
    def level(self) -> int: ...
    @property
    def tier(self) -> int: ...
    @property
    def max_frame_width(self) -> int: ...
    @property
    def max_frame_height(self) -> int: ...
    @property
    def bit_depth(self) -> int: ...
    @property
    def monochrome(self) -> bool: ...
    @property
    def chroma_format(self) -> ChromaFormat: ...
    @property
    def still_picture(self) -> bool: ...
    @property
    def reduced_still_picture_header(self) -> bool: ...
    @property
    def color_info(self) -> Optional[ColorInfo]: ...
    @property
    def frame_rate(self) -> Optional[Rational]: ...
    @property
    def raw(self) -> bytes: ...
    @property
    def raw_np(self) -> Any: ...

@final
class Av1FrameHeaderLight:
    @property
    def frame_type(self) -> int: ...
    @property
    def show_frame(self) -> bool: ...
    @property
    def show_existing_frame(self) -> bool: ...
    @property
    def frame_size(self) -> Optional[Tuple[int, int]]: ...
    @property
    def raw(self) -> bytes: ...
    @property
    def raw_np(self) -> Any: ...

@final
class Av1ObuStream:
    @property
    def sequence_headers(self) -> List[Av1SequenceHeader]: ...
    @property
    def frame_headers(self) -> List[Av1FrameHeaderLight]: ...
    @property
    def unparseable(self) -> List[Tuple[int, str]]: ...

def parse_av1_sequence_header(payload: _BytesLike) -> Av1SequenceHeader: ...
def parse_av1_frame_header_light(
    payload: _BytesLike, seq: Av1SequenceHeader
) -> Av1FrameHeaderLight: ...
def parse_av1_obu_stream(obus: List[Obu]) -> Av1ObuStream: ...

# --- AAC ---

@final
class AacProfile:
    MAIN: AacProfile
    LC: AacProfile
    SSR: AacProfile
    LTP: AacProfile

@final
class MpegVersion:
    MPEG2: MpegVersion
    MPEG4: MpegVersion

@final
class AacChannelLayout:
    @property
    def is_pce_defined(self) -> bool: ...
    @property
    def channels(self) -> Optional[int]: ...

@final
class AdtsFrame:
    @property
    def profile(self) -> AacProfile: ...
    @property
    def sample_rate_hz(self) -> int: ...
    @property
    def channel_configuration(self) -> int: ...
    @property
    def channel_layout(self) -> AacChannelLayout: ...
    @property
    def frame_length_bytes(self) -> int: ...
    @property
    def samples_per_frame(self) -> int: ...
    @property
    def num_raw_data_blocks(self) -> int: ...
    @property
    def has_crc(self) -> bool: ...
    @property
    def mpeg_version(self) -> MpegVersion: ...
    @property
    def raw_header(self) -> bytes: ...
    @property
    def payload(self) -> bytes: ...
    @property
    def payload_np(self) -> Any: ...

@final
class AdtsFrameIter:
    def __iter__(self) -> AdtsFrameIter: ...
    def __next__(self) -> AdtsFrame: ...

def iter_aac_frames(bytes_buf: _BytesLike) -> AdtsFrameIter: ...
def iter_aac_frames_with_resync(bytes_buf: _BytesLike) -> AdtsFrameIter: ...
def parse_aac_frames(bytes_buf: _BytesLike) -> List[AdtsFrame]: ...
def parse_aac_frames_with_resync(bytes_buf: _BytesLike) -> List[AdtsFrame]: ...

# --- MPEG-2 audio ---

@final
class Layer:
    I: Layer
    II: Layer
    III: Layer

@final
class Version:
    MPEG1: Version
    MPEG2: Version
    MPEG2_5: Version

@final
class ChannelMode:
    STEREO: ChannelMode
    JOINT_STEREO: ChannelMode
    DUAL_CHANNEL: ChannelMode
    MONO: ChannelMode

@final
class Mpeg2AudioFrame:
    @property
    def layer(self) -> Layer: ...
    @property
    def version(self) -> Version: ...
    @property
    def bitrate_kbps(self) -> int: ...
    @property
    def sample_rate_hz(self) -> int: ...
    @property
    def channel_mode(self) -> ChannelMode: ...
    @property
    def channels(self) -> int: ...
    @property
    def frame_length_bytes(self) -> int: ...
    @property
    def samples_per_frame(self) -> int: ...
    @property
    def has_crc(self) -> bool: ...
    @property
    def raw_header(self) -> bytes: ...
    @property
    def payload(self) -> bytes: ...
    @property
    def payload_np(self) -> Any: ...

@final
class Mpeg2AudioFrameIter:
    def __iter__(self) -> Mpeg2AudioFrameIter: ...
    def __next__(self) -> Mpeg2AudioFrame: ...

def iter_mpeg2_audio_frames(bytes_buf: _BytesLike) -> Mpeg2AudioFrameIter: ...
def iter_mpeg2_audio_frames_with_resync(bytes_buf: _BytesLike) -> Mpeg2AudioFrameIter: ...
def parse_mpeg2_audio_frames(bytes_buf: _BytesLike) -> List[Mpeg2AudioFrame]: ...
def parse_mpeg2_audio_frames_with_resync(bytes_buf: _BytesLike) -> List[Mpeg2AudioFrame]: ...

# --- raw-first opt-in ES parse entry points (v0.2.0 item #1) ---
#
# The units / frame element type is codec-dependent (NalUnit vs Obu;
# AdtsFrame vs Mpeg2AudioFrame), and `codec` may be a VideoCodec/AudioCodec
# enum OR its str name — so the element type is intentionally erased to Any.
# This is deliberate, not a stale TODO (overloads can't cover the enum case).

def split_units(
    raw: _BytesLike,
    codec: Any,
    *,
    strict: bool = ...,
    carriage: Optional[Any] = ...,
) -> Union[Tuple[List[Any], List[str]], List[Any]]: ...
# strict=False (default) → (units, issues) where units is List[NalUnit]|List[Obu]
# and issues is List[str]; strict=True → units only, raising ValueError on the
# first ES-conformance issue.
# carriage — Optional[Av1CarriageMode]; forwarded from DemuxEvent.Video.av1_carriage
# so split_units uses the right framing expectation for AV1. Ignored for H.26x.
def parse_audio(
    raw: _BytesLike,
    codec: Any,
    *,
    strict: bool = ...,
) -> List[Any]: ...   # List[AdtsFrame] | List[Mpeg2AudioFrame] | []

__all__ = [
    "ChromaFormat",
    "ColorInfo",
    "ColourPrimaries",
    "MatrixCoefficients",
    "NalUnit",
    "Obu",
    "ObuExtension",
    "Rational",
    "TransferCharacteristics",
    "EntropyCodingMode",
    "H264ParameterSets",
    "H264Pps",
    "H264SliceHeaderLight",
    "H264SliceType",
    "H264Sps",
    "parse_h264_parameter_sets",
    "parse_h264_pps",
    "parse_h264_slice_header_light",
    "parse_h264_sps",
    "H265ParameterSets",
    "H265Pps",
    "H265ProfileTierLevel",
    "H265SliceHeaderLight",
    "H265SliceType",
    "H265Sps",
    "H265Vps",
    "parse_h265_parameter_sets",
    "parse_h265_pps",
    "parse_h265_slice_header_light",
    "parse_h265_sps",
    "parse_h265_vps",
    "H266ParameterSets",
    "H266Pps",
    "H266ProfileTierLevel",
    "H266SliceHeaderLight",
    "H266SliceType",
    "H266Sps",
    "H266Vps",
    "parse_h266_parameter_sets",
    "parse_h266_pps",
    "parse_h266_slice_header_light",
    "parse_h266_sps",
    "parse_h266_vps",
    "Av1FrameHeaderLight",
    "Av1ObuStream",
    "Av1SequenceHeader",
    "parse_av1_frame_header_light",
    "parse_av1_obu_stream",
    "parse_av1_sequence_header",
    "AacChannelLayout",
    "AacProfile",
    "AdtsFrame",
    "AdtsFrameIter",
    "MpegVersion",
    "iter_aac_frames",
    "iter_aac_frames_with_resync",
    "parse_aac_frames",
    "parse_aac_frames_with_resync",
    "ChannelMode",
    "Layer",
    "Mpeg2AudioFrame",
    "Mpeg2AudioFrameIter",
    "Version",
    "iter_mpeg2_audio_frames",
    "iter_mpeg2_audio_frames_with_resync",
    "parse_mpeg2_audio_frames",
    "parse_mpeg2_audio_frames_with_resync",
    "split_units",
    "parse_audio",
]
