"""Type stubs for tstrans.klv — see klv.py for the runtime + full docstrings.

Covers the MISB typed sets — ST 0605 Precision Time Stamp Pack, ST 0102 Security
Metadata LS, ST 0903 VMTI LS, ST 0601 UAS Datalink LS (in runtime declaration
order) — as frozen dataclasses, their ST 0102 coding-method enums, the
`KlvFieldError` diagnostic type, the per-set `decode_*` / `encode_*`
`_native`-backed entry points, the universal `parse_klv_universal` dispatcher,
the well-known 16-byte UL `bytes` constants, and the `is_st0601_family`
predicate.

The `decode_*` / `encode_*` functions are re-exported from the compiled
`_native` extension; signatures here mirror the `#[pyo3(signature = ...)]`
attributes in src/klv.rs.

mypy --strict clean.
"""
from __future__ import annotations

import enum
from dataclasses import dataclass
from typing import Optional, Tuple, Union, final

# Bytes-like input accepted by the decoders. PyO3's &[u8] extractor takes any
# buffer-protocol object. Private (leading underscore) so stubtest doesn't
# treat it as a public runtime member.
_BytesLike = Union[bytes, bytearray, memoryview]

# ---------------------------------------------------------------------------
# Per-field decode diagnostics
# ---------------------------------------------------------------------------

class KlvFieldErrorKind(enum.Enum):
    OUT_OF_RANGE = "out_of_range"
    INVALID_UTF8 = "invalid_utf8"
    INVALID_UTF16 = "invalid_utf16"
    INVALID_LENGTH = "invalid_length"
    INVALID_CODEPOINT = "invalid_codepoint"
    TRUNCATED_FIELD = "truncated_field"
    UNSUPPORTED_IMAPB_LENGTH = "unsupported_imapb_length"
    INVALID_IMAPB_PARAMS = "invalid_imapb_params"

@dataclass(frozen=True, slots=True)
class KlvFieldError:
    kind: KlvFieldErrorKind
    tag: int
    message: str

# ---------------------------------------------------------------------------
# Well-known SMPTE / MISB Universal Labels (16-byte bytes constants)
# ---------------------------------------------------------------------------

ST_0601_UL: bytes
SECURITY_LS_UL: bytes
PRECISION_TIMESTAMP_PACK_UL: bytes
VMTI_LS_UL: bytes

def is_st0601_family(buf: bytes) -> bool: ...

# ---------------------------------------------------------------------------
# ST 0605 §7 Precision Time Stamp Pack
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class TimeStatus:
    raw: int
    def __post_init__(self) -> None: ...
    @property
    def is_locked(self) -> bool: ...
    @property
    def has_discontinuity(self) -> bool: ...
    @property
    def is_reverse_jump(self) -> bool: ...
    @property
    def reserved_bits_valid(self) -> bool: ...

@dataclass(frozen=True, slots=True)
class PrecisionTimeStampPack:
    time_status: TimeStatus
    timestamp_us: int
    def with_(self, **changes: object) -> PrecisionTimeStampPack: ...

# Spec-compat alias.
Klv0605 = PrecisionTimeStampPack

def decode_precision_timestamp(buf: _BytesLike) -> PrecisionTimeStampPack: ...
def encode_precision_timestamp(pack: PrecisionTimeStampPack) -> bytes: ...

# ---------------------------------------------------------------------------
# ST 0102.12 §6.1 enums
# ---------------------------------------------------------------------------

class SecurityClassification(enum.Enum):
    UNCLASSIFIED = 0x01
    RESTRICTED = 0x02
    CONFIDENTIAL = 0x03
    SECRET = 0x04
    TOP_SECRET = 0x05

class ClassifyingCountryCodingMethod(enum.Enum):
    ISO_3166_TWO_LETTER = 0x01
    ISO_3166_THREE_LETTER = 0x02
    FIPS_104_TWO_LETTER = 0x03
    FIPS_104_FOUR_LETTER = 0x04
    ISO_3166_NUMERIC = 0x05
    STANAG_1059_TWO_LETTER = 0x06
    STANAG_1059_THREE_LETTER = 0x07
    OMITTED_VALUE_08 = 0x08
    OMITTED_VALUE_09 = 0x09
    FIPS_104_MIXED = 0x0A
    ISO_3166_MIXED = 0x0B
    STANAG_1059_MIXED = 0x0C
    GENC_TWO_LETTER = 0x0D
    GENC_THREE_LETTER = 0x0E
    GENC_NUMERIC = 0x0F
    GENC_MIXED = 0x10

class ObjectCountryCodingMethod(enum.Enum):
    ISO_3166_TWO_LETTER = 0x01
    ISO_3166_THREE_LETTER = 0x02
    ISO_3166_NUMERIC = 0x03
    FIPS_104_TWO_LETTER = 0x04
    FIPS_104_FOUR_LETTER = 0x05
    STANAG_1059_TWO_LETTER = 0x06
    STANAG_1059_THREE_LETTER = 0x07
    OMITTED_VALUE_08 = 0x08
    OMITTED_VALUE_09 = 0x09
    OMITTED_VALUE_0A = 0x0A
    OMITTED_VALUE_0B = 0x0B
    OMITTED_VALUE_0C = 0x0C
    GENC_TWO_LETTER = 0x0D
    GENC_THREE_LETTER = 0x0E
    GENC_NUMERIC = 0x0F
    GENC_ADMIN_SUB = 0x40

# ---------------------------------------------------------------------------
# ST 0102.12 Security Metadata LS
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class SecurityLs:
    security_classification: Union[SecurityClassification, int, None] = ...
    classifying_country_coding_method: Union[ClassifyingCountryCodingMethod, int, None] = ...
    classifying_country: Optional[str] = ...
    object_country_coding_method: Union[ObjectCountryCodingMethod, int, None] = ...
    object_country_codes: Optional[str] = ...
    version: Optional[int] = ...
    sci_shi_info: Optional[str] = ...
    caveats: Optional[str] = ...
    releasing_instructions: Optional[str] = ...
    classified_by: Optional[str] = ...
    derived_from: Optional[str] = ...
    classification_reason: Optional[str] = ...
    declassification_date: Optional[str] = ...
    classification_marking_system: Optional[str] = ...
    classification_comments: Optional[str] = ...
    classifying_country_coding_method_version_date: Optional[str] = ...
    object_country_coding_method_version_date: Optional[str] = ...
    unknown: Tuple[Tuple[int, bytes], ...] = ...
    field_errors: Tuple[KlvFieldError, ...] = ...
    def with_(self, **changes: object) -> SecurityLs: ...

# Spec-compat alias.
Klv0102 = SecurityLs

def decode_security(buf: _BytesLike, *, strict: bool = ...) -> SecurityLs: ...
def encode_security(record: SecurityLs) -> bytes: ...
def encode_security_strict_compliance(record: SecurityLs) -> bytes: ...

# ---------------------------------------------------------------------------
# ST 0903.6 §10.2 VTargetPack
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class VTargetPack:
    target_id: int
    centroid_pixel: Optional[int] = ...
    bbox_top_left_pixel: Optional[int] = ...
    bbox_bottom_right_pixel: Optional[int] = ...
    priority: Optional[int] = ...
    confidence_level: Optional[int] = ...
    history: Optional[int] = ...
    percentage_of_target_pixels: Optional[int] = ...
    target_color: Optional[Tuple[int, int, int]] = ...
    target_intensity: Optional[int] = ...
    centroid_lat_offset: Optional[float] = ...
    centroid_lon_offset: Optional[float] = ...
    centroid_hae: Optional[float] = ...
    bbox_top_left_lat_offset: Optional[float] = ...
    bbox_top_left_lon_offset: Optional[float] = ...
    bbox_bottom_right_lat_offset: Optional[float] = ...
    bbox_bottom_right_lon_offset: Optional[float] = ...
    target_location: Optional[bytes] = ...
    geospatial_contour_series: Optional[bytes] = ...
    centroid_pix_row: Optional[int] = ...
    centroid_pix_col: Optional[int] = ...
    algorithm_id: Optional[int] = ...
    detection_status: Optional[int] = ...
    vmask: Optional[bytes] = ...
    vtracker: Optional[bytes] = ...
    vchip: Optional[bytes] = ...
    vchip_series: Optional[bytes] = ...
    vobject_series: Optional[bytes] = ...
    unknown: Tuple[Tuple[int, bytes], ...] = ...
    field_errors: Tuple[KlvFieldError, ...] = ...
    def __post_init__(self) -> None: ...

# ---------------------------------------------------------------------------
# ST 0903.6 VMTI Local Set
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class VmtiLs:
    checksum: Optional[int] = ...
    precision_time_stamp: Optional[int] = ...
    vmti_system_name: Optional[str] = ...
    version_number: Optional[int] = ...
    total_targets_in_frame: Optional[int] = ...
    num_targets_reported: Optional[int] = ...
    frame_width: Optional[int] = ...
    frame_height: Optional[int] = ...
    source_sensor: Optional[str] = ...
    horizontal_fov: Optional[float] = ...
    vertical_fov: Optional[float] = ...
    miis_id: Optional[bytes] = ...
    targets: Tuple[VTargetPack, ...] = ...
    algorithm_series: Optional[bytes] = ...
    ontology_series: Optional[bytes] = ...
    unknown: Tuple[Tuple[int, bytes], ...] = ...
    field_errors: Tuple[KlvFieldError, ...] = ...
    def with_(self, **changes: object) -> VmtiLs: ...

# Spec-compat alias.
Klv0903 = VmtiLs

def decode_vmti(buf: _BytesLike, *, strict: bool = ...) -> VmtiLs: ...
def encode_vmti(record: VmtiLs) -> bytes: ...
def encode_vmti_standalone(record: VmtiLs) -> bytes: ...
def encode_vmti_strict_compliance(record: VmtiLs) -> bytes: ...
def encode_vmti_standalone_strict_compliance(record: VmtiLs) -> bytes: ...

# ---------------------------------------------------------------------------
# ST 0601 composite read-only views
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class GeoPoint:
    lat_deg: float
    lon_deg: float
    alt_m: float

@dataclass(frozen=True, slots=True)
class Attitude:
    heading_deg: float
    pitch_deg: float
    roll_deg: float

@dataclass(frozen=True, slots=True)
class FieldOfView:
    horizontal_deg: float
    vertical_deg: float

@dataclass(frozen=True, slots=True)
class Corners:
    p1: Tuple[float, float]
    p2: Tuple[float, float]
    p3: Tuple[float, float]
    p4: Tuple[float, float]

# ---------------------------------------------------------------------------
# ST 0601.19 coded enums (Items 34, 63, 77)
# ---------------------------------------------------------------------------

class IcingDetected(enum.Enum):
    DETECTOR_OFF = 0
    NO_ICING_DETECTED = 1
    ICING_DETECTED = 2

class SensorFovName(enum.Enum):
    ULTRANARROW = 0
    NARROW = 1
    MEDIUM = 2
    WIDE = 3
    ULTRAWIDE = 4
    NARROW_MEDIUM = 5
    TWO_X_ULTRANARROW = 6
    FOUR_X_ULTRANARROW = 7
    CONTINUOUS_ZOOM = 8

class OperationalMode(enum.Enum):
    OTHER_MODE = 0
    OPERATIONAL = 1
    TRAINING = 2
    EXERCISE = 3
    MAINTENANCE = 4
    TEST = 5

# ---------------------------------------------------------------------------
# ST 0601 UAS Datalink Local Set
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class UasDatalinkLs:
    """MISB ST 0601.19 UAS Datalink Local Set typed view.

    Encode-enforced ranges (MISB ST 0601.19). Values outside a range raise
    ``KlvEncodeError`` on ``encode_uas_datalink``. Narrow/full twins:
    pitch 6↔90, roll 7↔91, corner offsets 26-33↔82-89 (absolute).

    Platform state
    --------------
    platform_heading_deg        Tag  5, [0, 360] deg
    platform_pitch_deg          Tag  6, [-20, 20] deg      — narrow; full twin: platform_pitch_full_deg (Tag 90)
    platform_roll_deg           Tag  7, [-50, 50] deg      — narrow; full twin: platform_roll_full_deg (Tag 91)
    platform_true_airspeed      Tag  8, [0, 255] m/s
    platform_indicated_airspeed Tag  9, [0, 255] m/s
    platform_pitch_full_deg     Tag 90, [-90, 90] deg      — full twin of platform_pitch_deg (Tag 6)
    platform_roll_full_deg      Tag 91, [-90, 90] deg      — full twin of platform_roll_deg (Tag 7)
    platform_angle_of_attack_deg Tag 50, [-20, 20] deg

    Sensor pose & position
    ----------------------
    sensor_lat_deg              Tag 13, [-90, 90] deg
    sensor_lon_deg              Tag 14, [-180, 180] deg
    sensor_alt_m                Tag 15, [-900, 19000] m
    sensor_ellipsoid_height_m   Tag 75, [-900, 19000] m
    sensor_hfov_deg             Tag 16, [0, 180] deg
    sensor_vfov_deg             Tag 17, [0, 180] deg
    sensor_rel_az_deg           Tag 18, [0, 360] deg
    sensor_rel_el_deg           Tag 19, [-180, 180] deg
    sensor_rel_roll_deg         Tag 20, [0, 360] deg

    Ranging & frame center
    ----------------------
    slant_range_m               Tag 21, [0, 5000000] m
    target_width_m              Tag 22, [0, 10000] m
    frame_center_lat_deg        Tag 23, [-90, 90] deg
    frame_center_lon_deg        Tag 24, [-180, 180] deg
    frame_center_elev_m         Tag 25, [-900, 19000] m
    frame_center_ellipsoid_height_m Tag 78, [-900, 19000] m

    Corner offsets (narrow ±0.075°)
    --------------------------------
    corner_lat_offset_p1_deg    Tag 26, [-0.075, 0.075] deg  — full twin: corner_lat_p1_deg (Tag 82)
    corner_lon_offset_p1_deg    Tag 27, [-0.075, 0.075] deg  — full twin: corner_lon_p1_deg (Tag 83)
    corner_lat_offset_p2_deg    Tag 28, [-0.075, 0.075] deg  — full twin: corner_lat_p2_deg (Tag 84)
    corner_lon_offset_p2_deg    Tag 29, [-0.075, 0.075] deg  — full twin: corner_lon_p2_deg (Tag 85)
    corner_lat_offset_p3_deg    Tag 30, [-0.075, 0.075] deg  — full twin: corner_lat_p3_deg (Tag 86)
    corner_lon_offset_p3_deg    Tag 31, [-0.075, 0.075] deg  — full twin: corner_lon_p3_deg (Tag 87)
    corner_lat_offset_p4_deg    Tag 32, [-0.075, 0.075] deg  — full twin: corner_lat_p4_deg (Tag 88)
    corner_lon_offset_p4_deg    Tag 33, [-0.075, 0.075] deg  — full twin: corner_lon_p4_deg (Tag 89)

    Corner full lat/lon (ST 0601.13+)
    -----------------------------------
    corner_lat_p1_deg           Tag 82, [-90, 90] deg        — full twin of corner_lat_offset_p1_deg (Tag 26)
    corner_lon_p1_deg           Tag 83, [-180, 180] deg      — full twin of corner_lon_offset_p1_deg (Tag 27)
    corner_lat_p2_deg           Tag 84, [-90, 90] deg        — full twin of corner_lat_offset_p2_deg (Tag 28)
    corner_lon_p2_deg           Tag 85, [-180, 180] deg      — full twin of corner_lon_offset_p2_deg (Tag 29)
    corner_lat_p3_deg           Tag 86, [-90, 90] deg        — full twin of corner_lat_offset_p3_deg (Tag 30)
    corner_lon_p3_deg           Tag 87, [-180, 180] deg      — full twin of corner_lon_offset_p3_deg (Tag 31)
    corner_lat_p4_deg           Tag 88, [-90, 90] deg        — full twin of corner_lat_offset_p4_deg (Tag 32)
    corner_lon_p4_deg           Tag 89, [-180, 180] deg      — full twin of corner_lon_offset_p4_deg (Tag 33)
    """

    universal_label: bytes = ...
    declared_version: int = ...
    mission_id: Optional[str] = ...
    platform_tail_number: Optional[str] = ...
    platform_designation: Optional[str] = ...
    image_source_sensor: Optional[str] = ...
    image_coordinate_system: Optional[str] = ...
    platform_call_sign: Optional[str] = ...
    uas_ls_version: Optional[int] = ...
    timestamp_us: Optional[int] = ...
    platform_heading_deg: Optional[float] = ...
    platform_pitch_deg: Optional[float] = ...
    platform_roll_deg: Optional[float] = ...
    platform_true_airspeed: Optional[float] = ...
    platform_indicated_airspeed: Optional[float] = ...
    platform_pitch_full_deg: Optional[float] = ...
    platform_roll_full_deg: Optional[float] = ...
    platform_angle_of_attack_deg: Optional[float] = ...
    sensor_lat_deg: Optional[float] = ...
    sensor_lon_deg: Optional[float] = ...
    sensor_alt_m: Optional[float] = ...
    sensor_ellipsoid_height_m: Optional[float] = ...
    sensor_hfov_deg: Optional[float] = ...
    sensor_vfov_deg: Optional[float] = ...
    sensor_rel_az_deg: Optional[float] = ...
    sensor_rel_el_deg: Optional[float] = ...
    sensor_rel_roll_deg: Optional[float] = ...
    slant_range_m: Optional[float] = ...
    target_width_m: Optional[float] = ...
    frame_center_lat_deg: Optional[float] = ...
    frame_center_lon_deg: Optional[float] = ...
    frame_center_elev_m: Optional[float] = ...
    frame_center_ellipsoid_height_m: Optional[float] = ...
    corner_lat_offset_p1_deg: Optional[float] = ...
    corner_lon_offset_p1_deg: Optional[float] = ...
    corner_lat_offset_p2_deg: Optional[float] = ...
    corner_lon_offset_p2_deg: Optional[float] = ...
    corner_lat_offset_p3_deg: Optional[float] = ...
    corner_lon_offset_p3_deg: Optional[float] = ...
    corner_lat_offset_p4_deg: Optional[float] = ...
    corner_lon_offset_p4_deg: Optional[float] = ...
    corner_lat_p1_deg: Optional[float] = ...
    corner_lon_p1_deg: Optional[float] = ...
    corner_lat_p2_deg: Optional[float] = ...
    corner_lon_p2_deg: Optional[float] = ...
    corner_lat_p3_deg: Optional[float] = ...
    corner_lon_p3_deg: Optional[float] = ...
    corner_lat_p4_deg: Optional[float] = ...
    corner_lon_p4_deg: Optional[float] = ...
    target_location_lat_deg: Optional[float] = ...
    target_location_lon_deg: Optional[float] = ...
    target_location_elev_m: Optional[float] = ...
    target_track_gate_width_px: Optional[float] = ...
    target_track_gate_height_px: Optional[float] = ...
    target_error_ce90_m: Optional[float] = ...
    target_error_le90_m: Optional[float] = ...
    wind_direction_deg: Optional[float] = ...
    wind_speed: Optional[float] = ...
    static_pressure_mbar: Optional[float] = ...
    density_altitude_m: Optional[float] = ...
    differential_pressure_mbar: Optional[float] = ...
    airfield_barometric_pressure_mbar: Optional[float] = ...
    airfield_elevation_m: Optional[float] = ...
    relative_humidity_pct: Optional[float] = ...
    platform_vertical_speed: Optional[float] = ...
    platform_sideslip_deg: Optional[float] = ...
    platform_ground_speed: Optional[float] = ...
    ground_range_m: Optional[float] = ...
    platform_fuel_remaining_kg: Optional[float] = ...
    platform_magnetic_heading_deg: Optional[float] = ...
    platform_angle_of_attack_full_deg: Optional[float] = ...
    platform_sideslip_full_deg: Optional[float] = ...
    alternate_platform_lat_deg: Optional[float] = ...
    alternate_platform_lon_deg: Optional[float] = ...
    alternate_platform_alt_m: Optional[float] = ...
    alternate_platform_heading_deg: Optional[float] = ...
    alternate_platform_ellipsoid_height_m: Optional[float] = ...
    sensor_north_velocity: Optional[float] = ...
    sensor_east_velocity: Optional[float] = ...
    generic_flag_data: Optional[int] = ...
    security_local_set: Optional[bytes] = ...
    rvt: Optional[bytes] = ...
    vmti: Optional[bytes] = ...
    miis_core_id: Optional[bytes] = ...
    sar_mi_local_set: Optional[bytes] = ...
    range_image_local_set: Optional[bytes] = ...
    geo_registration_local_set: Optional[bytes] = ...
    composite_imaging_local_set: Optional[bytes] = ...
    segment_local_set: Optional[bytes] = ...
    amend_local_set: Optional[bytes] = ...
    outside_air_temp_c: Optional[int] = ...
    weapon_load: Optional[int] = ...
    weapon_fired: Optional[int] = ...
    laser_prf_code: Optional[int] = ...
    alternate_platform_name: Optional[str] = ...
    event_start_time_us: Optional[int] = ...
    stream_designator: Optional[str] = ...
    operational_base: Optional[str] = ...
    broadcast_source: Optional[str] = ...
    target_id: Optional[str] = ...
    communications_method: Optional[str] = ...
    icing_detected: Union[IcingDetected, int, None] = ...
    sensor_fov_name: Union[SensorFovName, int, None] = ...
    operational_mode: Union[OperationalMode, int, None] = ...
    unknown: Tuple[Tuple[int, bytes], ...] = ...
    field_errors: Tuple[KlvFieldError, ...] = ...
    sentinel_tags: Tuple[int, ...] = ...
    def __post_init__(self) -> None: ...
    def with_(self, **changes: object) -> UasDatalinkLs: ...
    def sensor_position(self) -> Optional[GeoPoint]: ...
    def sensor_attitude(self) -> Optional[Attitude]: ...
    def sensor_fov(self) -> Optional[FieldOfView]: ...
    def platform_attitude(self) -> Optional[Attitude]: ...
    def frame_center(self) -> Optional[GeoPoint]: ...
    def corners(self) -> Optional[Corners]: ...

# Spec-compat alias.
Klv0601 = UasDatalinkLs

@final
class OutOfRangePolicy:
    """Policy for values outside their ST 0601 mapped range during encoding.

    - ``ERROR`` (default): raise ``KlvEncodeError(OUT_OF_RANGE)``.
    - ``INDICATOR``: emit the tag's spec-defined Out-of-Range special value
      (INT_MIN sentinel, ``0x8000`` or ``0x80000000``) instead of raising.
      Applies only to tags where ST 0601 defines the indicator; of the
      currently encodable fields: platform pitch/roll/angle-of-attack
      (Tags 6, 7, 50) and full-range pitch/roll (Tags 90, 91). All other
      fields, and any non-finite value, still raise under ``INDICATOR``.
    """

    ERROR: OutOfRangePolicy
    INDICATOR: OutOfRangePolicy

def decode_uas_datalink(
    buf: _BytesLike, *, strict: bool = ..., compliance: bool = ...
) -> UasDatalinkLs: ...
def encode_uas_datalink(
    record: UasDatalinkLs,
    *,
    out_of_range_policy: Optional[OutOfRangePolicy] = ...,
) -> bytes: ...
def encode_uas_datalink_strict_compliance(record: UasDatalinkLs) -> bytes: ...
def patch_uas_datalink(
    raw: bytes, edits: Union[UasDatalinkLs, dict[str, object]]
) -> bytes: ...
def st0601_sentinel_meaning(tag: int) -> Optional[str]: ...

# ---------------------------------------------------------------------------
# Universal Label dispatcher
# ---------------------------------------------------------------------------

def parse_klv_universal(
    buf: bytes, *, strict: bool = ...
) -> Optional[Union[UasDatalinkLs, SecurityLs, PrecisionTimeStampPack, VmtiLs]]: ...

# ---------------------------------------------------------------------------
# ST 1204.3 MIIS Core Identifier
# ---------------------------------------------------------------------------

class IdType(enum.Enum):
    """Source type for a sensor or platform UUID within a CoreId.

    Maps to the two-bit field in ST 1204.3 §7.3.1 Table 3 usage byte."""

    PHYSICAL = "physical"
    VIRTUAL = "virtual"
    MANAGED = "managed"

@dataclass(frozen=True, slots=True)
class CoreId:
    """MISB ST 1204.3 MIIS Core Identifier typed view."""

    version: int
    sensor: Optional[Tuple[IdType, bytes]] = ...
    platform: Optional[Tuple[IdType, bytes]] = ...
    window: Optional[bytes] = ...
    minor: Optional[bytes] = ...
    def with_(self, **changes: object) -> CoreId: ...

def decode_core_id(buf: _BytesLike) -> CoreId: ...
def encode_core_id(core_id: CoreId) -> bytes: ...
def core_id_text(core_id: CoreId) -> str: ...

# ---------------------------------------------------------------------------
# ST 0902.8 Minimum Metadata Set (MISMMS) violation
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class MismmsViolation:
    """A violation of the ST 0902.8 Minimum Metadata Set requirements."""

    kind: str
    tag: int
    name: Optional[str] = ...
    tag_b: Optional[int] = ...

def validate_mismms(record: UasDatalinkLs) -> list[MismmsViolation]: ...

__all__ = [
    "KlvFieldErrorKind",
    "KlvFieldError",
    "ST_0601_UL",
    "SECURITY_LS_UL",
    "PRECISION_TIMESTAMP_PACK_UL",
    "VMTI_LS_UL",
    "is_st0601_family",
    "TimeStatus",
    "PrecisionTimeStampPack",
    "Klv0605",
    "decode_precision_timestamp",
    "encode_precision_timestamp",
    "SecurityClassification",
    "ClassifyingCountryCodingMethod",
    "ObjectCountryCodingMethod",
    "SecurityLs",
    "Klv0102",
    "decode_security",
    "encode_security",
    "encode_security_strict_compliance",
    "VTargetPack",
    "VmtiLs",
    "Klv0903",
    "decode_vmti",
    "encode_vmti",
    "encode_vmti_standalone",
    "encode_vmti_strict_compliance",
    "encode_vmti_standalone_strict_compliance",
    "GeoPoint",
    "Attitude",
    "FieldOfView",
    "Corners",
    "OutOfRangePolicy",
    "IcingDetected",
    "SensorFovName",
    "OperationalMode",
    "UasDatalinkLs",
    "Klv0601",
    "decode_uas_datalink",
    "encode_uas_datalink",
    "encode_uas_datalink_strict_compliance",
    "patch_uas_datalink",
    "st0601_sentinel_meaning",
    "parse_klv_universal",
    "IdType",
    "CoreId",
    "decode_core_id",
    "encode_core_id",
    "core_id_text",
    "MismmsViolation",
    "validate_mismms",
]
