"""Type stubs for tstrans.klv — see klv.py for the runtime + full docstrings.

Covers the MISB typed sets — ST 0605 Precision Time Stamp Pack, ST 0102 Security
Metadata LS, ST 0903 VMTI LS, ST 0601 UAS Datalink LS (in runtime declaration
order) — as frozen dataclasses, their ST 0102 coding-method enums, the
`KlvFieldError` diagnostic type, the per-set `decode_*` / `encode_*`
`_native`-backed entry points, the universal `parse_klv_universal` dispatcher,
the well-known 16-byte UL `bytes` constants, and the `is_st0601_family`
predicate.

The `decode_*` / `encode_*` functions are re-exported from the compiled
`_native` extension; signatures here mirror the `#[pyo3(signature = ...)]`
attributes in src/klv.rs.

mypy --strict clean.
"""
from __future__ import annotations

import enum
from dataclasses import dataclass
from typing import Optional, Tuple, Union

# Bytes-like input accepted by the decoders. PyO3's &[u8] extractor takes any
# buffer-protocol object. Private (leading underscore) so stubtest doesn't
# treat it as a public runtime member.
_BytesLike = Union[bytes, bytearray, memoryview]

# ---------------------------------------------------------------------------
# Per-field decode diagnostics
# ---------------------------------------------------------------------------

class KlvFieldErrorKind(enum.Enum):
    OUT_OF_RANGE = "out_of_range"
    INVALID_UTF8 = "invalid_utf8"
    INVALID_UTF16 = "invalid_utf16"
    INVALID_LENGTH = "invalid_length"
    INVALID_SENTINEL = "invalid_sentinel"
    INVALID_CODEPOINT = "invalid_codepoint"
    TRUNCATED_FIELD = "truncated_field"
    UNSUPPORTED_IMAPB_LENGTH = "unsupported_imapb_length"
    INVALID_IMAPB_PARAMS = "invalid_imapb_params"

@dataclass(frozen=True, slots=True)
class KlvFieldError:
    kind: KlvFieldErrorKind
    tag: int
    message: str

# ---------------------------------------------------------------------------
# Well-known SMPTE / MISB Universal Labels (16-byte bytes constants)
# ---------------------------------------------------------------------------

ST_0601_UL: bytes
SECURITY_LS_UL: bytes
PRECISION_TIMESTAMP_PACK_UL: bytes
VMTI_LS_UL: bytes

def is_st0601_family(buf: bytes) -> bool: ...

# ---------------------------------------------------------------------------
# ST 0605 §7 Precision Time Stamp Pack
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class TimeStatus:
    raw: int
    def __post_init__(self) -> None: ...
    @property
    def is_locked(self) -> bool: ...
    @property
    def has_discontinuity(self) -> bool: ...
    @property
    def is_reverse_jump(self) -> bool: ...
    @property
    def reserved_bits_valid(self) -> bool: ...

@dataclass(frozen=True, slots=True)
class PrecisionTimeStampPack:
    time_status: TimeStatus
    timestamp_us: int
    def with_(self, **changes: object) -> PrecisionTimeStampPack: ...

# Spec-compat alias.
Klv0605 = PrecisionTimeStampPack

def decode_precision_timestamp(buf: _BytesLike) -> PrecisionTimeStampPack: ...
def encode_precision_timestamp(pack: PrecisionTimeStampPack) -> bytes: ...

# ---------------------------------------------------------------------------
# ST 0102.12 §6.1 enums
# ---------------------------------------------------------------------------

class SecurityClassification(enum.Enum):
    UNCLASSIFIED = 0x01
    RESTRICTED = 0x02
    CONFIDENTIAL = 0x03
    SECRET = 0x04
    TOP_SECRET = 0x05

class ClassifyingCountryCodingMethod(enum.Enum):
    ISO_3166_TWO_LETTER = 0x01
    ISO_3166_THREE_LETTER = 0x02
    FIPS_104_TWO_LETTER = 0x03
    FIPS_104_FOUR_LETTER = 0x04
    ISO_3166_NUMERIC = 0x05
    STANAG_1059_TWO_LETTER = 0x06
    STANAG_1059_THREE_LETTER = 0x07
    OMITTED_VALUE_08 = 0x08
    OMITTED_VALUE_09 = 0x09
    FIPS_104_MIXED = 0x0A
    ISO_3166_MIXED = 0x0B
    STANAG_1059_MIXED = 0x0C
    GENC_TWO_LETTER = 0x0D
    GENC_THREE_LETTER = 0x0E
    GENC_NUMERIC = 0x0F
    GENC_MIXED = 0x10

class ObjectCountryCodingMethod(enum.Enum):
    ISO_3166_TWO_LETTER = 0x01
    ISO_3166_THREE_LETTER = 0x02
    ISO_3166_NUMERIC = 0x03
    FIPS_104_TWO_LETTER = 0x04
    FIPS_104_FOUR_LETTER = 0x05
    STANAG_1059_TWO_LETTER = 0x06
    STANAG_1059_THREE_LETTER = 0x07
    OMITTED_VALUE_08 = 0x08
    OMITTED_VALUE_09 = 0x09
    OMITTED_VALUE_0A = 0x0A
    OMITTED_VALUE_0B = 0x0B
    OMITTED_VALUE_0C = 0x0C
    GENC_TWO_LETTER = 0x0D
    GENC_THREE_LETTER = 0x0E
    GENC_NUMERIC = 0x0F
    GENC_ADMIN_SUB = 0x40

# ---------------------------------------------------------------------------
# ST 0102.12 Security Metadata LS
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class SecurityLs:
    security_classification: Union[SecurityClassification, int, None] = ...
    classifying_country_coding_method: Union[ClassifyingCountryCodingMethod, int, None] = ...
    classifying_country: Optional[str] = ...
    object_country_coding_method: Union[ObjectCountryCodingMethod, int, None] = ...
    object_country_codes: Optional[str] = ...
    version: Optional[int] = ...
    sci_shi_info: Optional[str] = ...
    caveats: Optional[str] = ...
    releasing_instructions: Optional[str] = ...
    classified_by: Optional[str] = ...
    derived_from: Optional[str] = ...
    classification_reason: Optional[str] = ...
    declassification_date: Optional[str] = ...
    classification_marking_system: Optional[str] = ...
    classification_comments: Optional[str] = ...
    classifying_country_coding_method_version_date: Optional[str] = ...
    object_country_coding_method_version_date: Optional[str] = ...
    unknown: Tuple[Tuple[int, bytes], ...] = ...
    field_errors: Tuple[KlvFieldError, ...] = ...
    def with_(self, **changes: object) -> SecurityLs: ...

# Spec-compat alias.
Klv0102 = SecurityLs

def decode_security(buf: _BytesLike, *, strict: bool = ...) -> SecurityLs: ...
def encode_security(record: SecurityLs) -> bytes: ...

# ---------------------------------------------------------------------------
# ST 0903.6 §10.2 VTargetPack
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class VTargetPack:
    target_id: int
    centroid_pixel: Optional[int] = ...
    bbox_top_left_pixel: Optional[int] = ...
    bbox_bottom_right_pixel: Optional[int] = ...
    priority: Optional[int] = ...
    confidence_level: Optional[int] = ...
    history: Optional[int] = ...
    percentage_of_target_pixels: Optional[int] = ...
    target_color: Optional[Tuple[int, int, int]] = ...
    target_intensity: Optional[int] = ...
    centroid_lat_offset: Optional[float] = ...
    centroid_lon_offset: Optional[float] = ...
    centroid_hae: Optional[float] = ...
    bbox_top_left_lat_offset: Optional[float] = ...
    bbox_top_left_lon_offset: Optional[float] = ...
    bbox_bottom_right_lat_offset: Optional[float] = ...
    bbox_bottom_right_lon_offset: Optional[float] = ...
    target_location: Optional[bytes] = ...
    geospatial_contour_series: Optional[bytes] = ...
    centroid_pix_row: Optional[int] = ...
    centroid_pix_col: Optional[int] = ...
    algorithm_id: Optional[int] = ...
    detection_status: Optional[int] = ...
    vmask: Optional[bytes] = ...
    vtracker: Optional[bytes] = ...
    vchip: Optional[bytes] = ...
    vchip_series: Optional[bytes] = ...
    vobject_series: Optional[bytes] = ...
    unknown: Tuple[Tuple[int, bytes], ...] = ...
    field_errors: Tuple[KlvFieldError, ...] = ...
    def __post_init__(self) -> None: ...

# ---------------------------------------------------------------------------
# ST 0903.6 VMTI Local Set
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class VmtiLs:
    checksum: Optional[int] = ...
    precision_time_stamp: Optional[int] = ...
    vmti_system_name: Optional[str] = ...
    version_number: Optional[int] = ...
    total_targets_in_frame: Optional[int] = ...
    num_targets_reported: Optional[int] = ...
    frame_width: Optional[int] = ...
    frame_height: Optional[int] = ...
    source_sensor: Optional[str] = ...
    horizontal_fov: Optional[float] = ...
    vertical_fov: Optional[float] = ...
    miis_id: Optional[bytes] = ...
    targets: Tuple[VTargetPack, ...] = ...
    algorithm_series: Optional[bytes] = ...
    ontology_series: Optional[bytes] = ...
    unknown: Tuple[Tuple[int, bytes], ...] = ...
    field_errors: Tuple[KlvFieldError, ...] = ...
    def with_(self, **changes: object) -> VmtiLs: ...

# Spec-compat alias.
Klv0903 = VmtiLs

def decode_vmti(buf: _BytesLike, *, strict: bool = ...) -> VmtiLs: ...
def encode_vmti(record: VmtiLs) -> bytes: ...
def encode_vmti_standalone(record: VmtiLs) -> bytes: ...

# ---------------------------------------------------------------------------
# ST 0601 composite read-only views
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class GeoPoint:
    lat_deg: float
    lon_deg: float
    alt_m: float

@dataclass(frozen=True, slots=True)
class Attitude:
    heading_deg: float
    pitch_deg: float
    roll_deg: float

@dataclass(frozen=True, slots=True)
class FieldOfView:
    horizontal_deg: float
    vertical_deg: float

@dataclass(frozen=True, slots=True)
class Corners:
    p1: Tuple[float, float]
    p2: Tuple[float, float]
    p3: Tuple[float, float]
    p4: Tuple[float, float]

# ---------------------------------------------------------------------------
# ST 0601 UAS Datalink Local Set
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class UasDatalinkLs:
    universal_label: bytes = ...
    declared_version: int = ...
    mission_id: Optional[str] = ...
    platform_tail_number: Optional[str] = ...
    platform_designation: Optional[str] = ...
    image_source_sensor: Optional[str] = ...
    image_coordinate_system: Optional[str] = ...
    platform_call_sign: Optional[str] = ...
    uas_ls_version: Optional[int] = ...
    timestamp_us: Optional[int] = ...
    platform_heading_deg: Optional[float] = ...
    platform_pitch_deg: Optional[float] = ...
    platform_roll_deg: Optional[float] = ...
    platform_true_airspeed: Optional[float] = ...
    platform_indicated_airspeed: Optional[float] = ...
    platform_pitch_full_deg: Optional[float] = ...
    platform_roll_full_deg: Optional[float] = ...
    platform_angle_of_attack_deg: Optional[float] = ...
    sensor_lat_deg: Optional[float] = ...
    sensor_lon_deg: Optional[float] = ...
    sensor_alt_m: Optional[float] = ...
    sensor_ellipsoid_height_m: Optional[float] = ...
    sensor_hfov_deg: Optional[float] = ...
    sensor_vfov_deg: Optional[float] = ...
    sensor_rel_az_deg: Optional[float] = ...
    sensor_rel_el_deg: Optional[float] = ...
    sensor_rel_roll_deg: Optional[float] = ...
    slant_range_m: Optional[float] = ...
    target_width_m: Optional[float] = ...
    frame_center_lat_deg: Optional[float] = ...
    frame_center_lon_deg: Optional[float] = ...
    frame_center_elev_m: Optional[float] = ...
    frame_center_ellipsoid_height_m: Optional[float] = ...
    corner_lat_offset_p1_deg: Optional[float] = ...
    corner_lon_offset_p1_deg: Optional[float] = ...
    corner_lat_offset_p2_deg: Optional[float] = ...
    corner_lon_offset_p2_deg: Optional[float] = ...
    corner_lat_offset_p3_deg: Optional[float] = ...
    corner_lon_offset_p3_deg: Optional[float] = ...
    corner_lat_offset_p4_deg: Optional[float] = ...
    corner_lon_offset_p4_deg: Optional[float] = ...
    corner_lat_p1_deg: Optional[float] = ...
    corner_lon_p1_deg: Optional[float] = ...
    corner_lat_p2_deg: Optional[float] = ...
    corner_lon_p2_deg: Optional[float] = ...
    corner_lat_p3_deg: Optional[float] = ...
    corner_lon_p3_deg: Optional[float] = ...
    corner_lat_p4_deg: Optional[float] = ...
    corner_lon_p4_deg: Optional[float] = ...
    generic_flag_data: Optional[int] = ...
    security_local_set: Optional[bytes] = ...
    vmti: Optional[bytes] = ...
    unknown: Tuple[Tuple[int, bytes], ...] = ...
    field_errors: Tuple[KlvFieldError, ...] = ...
    def __post_init__(self) -> None: ...
    def with_(self, **changes: object) -> UasDatalinkLs: ...
    def sensor_position(self) -> Optional[GeoPoint]: ...
    def sensor_attitude(self) -> Optional[Attitude]: ...
    def sensor_fov(self) -> Optional[FieldOfView]: ...
    def platform_attitude(self) -> Optional[Attitude]: ...
    def frame_center(self) -> Optional[GeoPoint]: ...
    def corners(self) -> Optional[Corners]: ...

# Spec-compat alias.
Klv0601 = UasDatalinkLs

def decode_uas_datalink(
    buf: _BytesLike, *, strict: bool = ..., compliance: bool = ...
) -> UasDatalinkLs: ...
def encode_uas_datalink(record: UasDatalinkLs) -> bytes: ...
def encode_uas_datalink_strict_compliance(record: UasDatalinkLs) -> bytes: ...
def patch_uas_datalink(
    raw: bytes, edits: Union[UasDatalinkLs, dict[str, object]]
) -> bytes: ...

# ---------------------------------------------------------------------------
# Universal Label dispatcher
# ---------------------------------------------------------------------------

def parse_klv_universal(
    buf: bytes,
) -> Optional[Union[UasDatalinkLs, SecurityLs, PrecisionTimeStampPack, VmtiLs]]: ...

__all__ = [
    "KlvFieldErrorKind",
    "KlvFieldError",
    "ST_0601_UL",
    "SECURITY_LS_UL",
    "PRECISION_TIMESTAMP_PACK_UL",
    "VMTI_LS_UL",
    "is_st0601_family",
    "TimeStatus",
    "PrecisionTimeStampPack",
    "Klv0605",
    "decode_precision_timestamp",
    "encode_precision_timestamp",
    "SecurityClassification",
    "ClassifyingCountryCodingMethod",
    "ObjectCountryCodingMethod",
    "SecurityLs",
    "Klv0102",
    "decode_security",
    "encode_security",
    "VTargetPack",
    "VmtiLs",
    "Klv0903",
    "decode_vmti",
    "encode_vmti",
    "encode_vmti_standalone",
    "GeoPoint",
    "Attitude",
    "FieldOfView",
    "Corners",
    "UasDatalinkLs",
    "Klv0601",
    "decode_uas_datalink",
    "encode_uas_datalink",
    "encode_uas_datalink_strict_compliance",
    "patch_uas_datalink",
    "parse_klv_universal",
]
