//! Fixture-driven subtitle demux tests. Each test loads a fixture
//! generated by the `subtitles/regen.sh` regenerator and asserts
//! classification + Sample-event emission.

use std::path::PathBuf;
use std::process::Command;

use srt_core::mpegts::demux::{DemuxEvent, Demuxer, SamplePayload, StreamKind, SubtitleCodec};

fn load(name: &str) -> Vec<u8> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/subtitles")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("read fixture {}: {}", path.display(), e))
}

/// Drain every event from the demuxer into a Vec for matching.
fn collect_events(bytes: &[u8]) -> Vec<DemuxEvent> {
    let mut demux = Demuxer::new();
    demux.feed(bytes).unwrap();
    demux.flush();
    let mut events = Vec::new();
    while let Some(e) = demux.next_event() {
        events.push(e);
    }
    events
}

fn ffprobe_available() -> bool {
    Command::new("ffprobe")
        .arg("-version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

#[test]
fn dvb_subtitling_eng_classifies_as_dvb_subtitling() {
    let bytes = load("dvb_subtitling_eng.ts");
    let events = collect_events(&bytes);
    assert!(
        events.iter().any(|e| matches!(
            e,
            DemuxEvent::Sample {
                payload: SamplePayload::Subtitle {
                    codec: SubtitleCodec::DvbSubtitling,
                    ..
                },
                ..
            }
        )),
        "expected DvbSubtitling Sample event, got {events:?}"
    );
}

#[test]
fn dvb_subtitling_multi_lang_yields_two_streams() {
    let bytes = load("dvb_subtitling_multi_lang.ts");
    let events = collect_events(&bytes);
    let pm = events
        .iter()
        .find_map(|e| match e {
            DemuxEvent::ProgramMap(pm) => Some(pm),
            _ => None,
        })
        .expect("ProgramMap event");
    let sub_count = pm
        .streams
        .iter()
        .filter(|s| matches!(s.kind, StreamKind::Subtitle(SubtitleCodec::DvbSubtitling)))
        .count();
    assert_eq!(
        sub_count, 2,
        "expected two DvbSubtitling streams in ProgramMap, got {sub_count}"
    );
}

#[test]
fn dvb_teletext_eng_classifies_as_dvb_teletext() {
    let bytes = load("dvb_teletext_eng.ts");
    let events = collect_events(&bytes);
    assert!(
        events.iter().any(|e| matches!(
            e,
            DemuxEvent::Sample {
                payload: SamplePayload::Subtitle {
                    codec: SubtitleCodec::DvbTeletext,
                    ..
                },
                ..
            }
        )),
        "expected DvbTeletext Sample event, got {events:?}"
    );
}

#[test]
fn webvtt_simple_classifies_as_webvtt_in_ts() {
    let bytes = load("webvtt_in_ts_simple.ts");
    let events = collect_events(&bytes);
    let payload = events
        .iter()
        .find_map(|e| match e {
            DemuxEvent::Sample {
                payload:
                    SamplePayload::Subtitle {
                        codec: SubtitleCodec::WebVttInTs,
                        payload,
                    },
                ..
            } => Some(payload.clone()),
            _ => None,
        })
        .expect("WebVTT Sample event");
    assert!(
        payload.windows(6).any(|w| w == b"WEBVTT"),
        "expected WEBVTT signature in payload, got {} bytes",
        payload.len()
    );
}

#[test]
fn webvtt_multi_cue_yields_multiple_sample_events() {
    let bytes = load("webvtt_in_ts_multi_cue.ts");
    let events = collect_events(&bytes);
    let cues = events
        .iter()
        .filter(|e| {
            matches!(
                e,
                DemuxEvent::Sample {
                    payload: SamplePayload::Subtitle {
                        codec: SubtitleCodec::WebVttInTs,
                        ..
                    },
                    ..
                }
            )
        })
        .count();
    assert!(cues >= 5, "expected >= 5 WebVTT Sample events, got {cues}");
}

#[test]
fn cea708_standalone_classifies_as_cea708_standalone() {
    let bytes = load("cea708_standalone.ts");
    let events = collect_events(&bytes);
    let cea_samples = events
        .iter()
        .filter(|e| {
            matches!(
                e,
                DemuxEvent::Sample {
                    payload: SamplePayload::Subtitle {
                        codec: SubtitleCodec::Cea708Standalone,
                        ..
                    },
                    ..
                }
            )
        })
        .count();
    assert!(
        cea_samples >= 1,
        "expected >= 1 Cea708Standalone Sample event, got {cea_samples}"
    );
}

#[test]
fn subtitle_with_klv_same_program_yields_both_kinds() {
    let bytes = load("subtitle_with_klv_same_program.ts");
    let events = collect_events(&bytes);
    let has_subtitle = events.iter().any(|e| {
        matches!(
            e,
            DemuxEvent::Sample {
                payload: SamplePayload::Subtitle { .. },
                ..
            }
        )
    });
    let has_klv = events
        .iter()
        .any(|e| matches!(e, DemuxEvent::Metadata { .. }));
    assert!(has_subtitle, "expected subtitle Sample event");
    assert!(has_klv, "expected KLV Metadata event");
}

#[test]
fn webvtt_multi_program_with_klv_yields_two_program_maps() {
    let bytes = load("webvtt_multi_program_with_klv.ts");
    let events = collect_events(&bytes);
    let pms: Vec<_> = events
        .iter()
        .filter_map(|e| match e {
            DemuxEvent::ProgramMap(pm) => Some(pm),
            _ => None,
        })
        .collect();
    assert_eq!(
        pms.len(),
        2,
        "expected 2 ProgramMap events, got {}",
        pms.len()
    );
}

#[test]
#[ignore = "ffprobe-only — runs locally, gated on ffprobe presence"]
fn dvb_subtitling_ffprobe_agrees() {
    if !ffprobe_available() {
        eprintln!("skipping: ffprobe not on PATH");
        return;
    }
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/subtitles/dvb_subtitling_eng.ts");
    let out = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-show_entries",
            "stream=codec_name,codec_type",
            "-of",
            "csv=p=0",
        ])
        .arg(&path)
        .output()
        .expect("run ffprobe");
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(stdout.contains("dvb_subtitle"), "ffprobe output: {stdout}");
}

#[test]
#[ignore = "ffprobe-only"]
fn dvb_teletext_ffprobe_agrees() {
    if !ffprobe_available() {
        eprintln!("skipping: ffprobe not on PATH");
        return;
    }
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/subtitles/dvb_teletext_eng.ts");
    let out = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-show_entries",
            "stream=codec_name",
            "-of",
            "csv=p=0",
        ])
        .arg(&path)
        .output()
        .expect("run ffprobe");
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(stdout.contains("dvb_teletext"), "ffprobe output: {stdout}");
}

#[test]
#[ignore = "ffprobe-only"]
fn webvtt_in_ts_ffprobe_agrees() {
    if !ffprobe_available() {
        eprintln!("skipping: ffprobe not on PATH");
        return;
    }
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/subtitles/webvtt_in_ts_simple.ts");
    let out = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-show_entries",
            "stream=codec_name",
            "-of",
            "csv=p=0",
        ])
        .arg(&path)
        .output()
        .expect("run ffprobe");
    let stdout = String::from_utf8_lossy(&out.stdout);
    // ffmpeg's labels for WebVTT-in-TS have drifted across releases —
    // some builds report "webvtt", others fall back to the generic
    // "bin_data" since the WebVTT-in-MPEG-TS path (per Apple HLS) is
    // not on every ffmpeg's well-known-codec list. We accept any of
    // the plausible labels; the round-trip mux+demux test already
    // proves the codec is classified correctly inside our crate.
    assert!(
        stdout.contains("webvtt") || stdout.contains("subtitle") || stdout.contains("bin_data"),
        "ffprobe output: {stdout}"
    );
}
