//! Phase 3 Wave F Task 24 — server-side TLS integration tests.
//!
//! Exercises `RtspServerBuilder::tls_cert(...)` with a self-signed cert
//! generated by `rcgen` (see `tests/fixtures/tls_certs.rs`). Covers both
//! the bind+start smoke path and a full `rtsps://` handshake + OPTIONS
//! round-trip: the client trusts the cert via
//! `RtspClientBuilder::tls_root_certs` (forwarded through
//! `connect_with_roots`), and the server serves the request over the
//! encrypted channel via the `serve_requests` TLS session loop.

#![cfg(feature = "tls")]

use tst_core::mpegts::mux::{MuxerConfig, MuxerProgramConfigBuilder, VideoCodec};
use tst_rtp::RtspServerBuilder;

use crate::fixtures::tls_certs::SelfSignedCert;

fn make_muxer_cfg() -> MuxerConfig {
    let mut prog = MuxerProgramConfigBuilder::new(1, 0x1000);
    prog.add_video(0x1011, VideoCodec::H264);
    let mut b = MuxerConfig::builder();
    b.add_program(prog.build());
    b.build().expect("MuxerConfig builds")
}

/// Server with TLS cert configured starts cleanly and binds to a port.
/// This is the smoke-level confirmation that `RtspServerBuilder::tls_cert`
/// and the `rtsps://` listener bind path work end-to-end without a live
/// client driving a handshake.
#[test]
fn tls_server_binds_and_starts() {
    let certs = SelfSignedCert::generate();
    let mut b = RtspServerBuilder::new("rtsps://127.0.0.1:0").expect("URL parse");
    b.tls_cert(certs.cert_path.clone(), certs.key_path.clone());
    let server = b.build().expect("server build");
    let _mount = server
        .add_mount("/live", make_muxer_cfg())
        .expect("add_mount");
    server.start().expect("server start");
    let addr = server
        .local_addr()
        .expect("local_addr populated after start");
    assert_eq!(addr.ip().to_string(), "127.0.0.1");
    assert_ne!(addr.port(), 0, "kernel-picked port must be non-zero");
    server.stop().ok();
}

/// Full `rtsps://` handshake against the in-process server with a
/// self-signed cert trusted via a custom rustls root store, then an
/// OPTIONS round-trip over the encrypted channel.
///
/// Exercises the client-side custom-root wiring
/// (`RtspClientBuilder::tls_root_certs` → `connect_with_roots` →
/// `TlsStream::connect`) AND the server-side TLS session loop
/// (`handle_connection_tls` → `serve_requests`). Before the session loop
/// landed, the server completed the handshake then dropped the
/// connection, so this OPTIONS read returned `Io(UnexpectedEof)`.
#[test]
fn rtsps_handshake_succeeds_with_trusted_root() {
    let certs = SelfSignedCert::generate();
    let mut b = RtspServerBuilder::new("rtsps://127.0.0.1:0").expect("URL parse");
    b.tls_cert(certs.cert_path.clone(), certs.key_path.clone());
    let server = b.build().expect("server build");
    let _mount = server
        .add_mount("/live", make_muxer_cfg())
        .expect("add_mount");
    server.start().expect("server start");
    let port = server.local_addr().expect("local_addr").port();
    let url = format!("rtsps://127.0.0.1:{port}/live");

    // Build a RootCertStore from the test cert PEM. Once
    // `RtspClient::connect_with` forwards a `Option<RootCertStore>` from
    // the builder, the line below will wire through; today it's still
    // discarded.
    let mut roots = rustls::RootCertStore::empty();
    for cert in rustls_pemfile::certs(&mut certs.root_pem.as_bytes()) {
        let cert = cert.expect("PEM cert parse");
        roots.add(cert).expect("add to root store");
    }
    let mut cb = tst_rtp::RtspClientBuilder::new(&url).expect("client builder");
    cb = cb.tls_root_certs(roots);
    let mut client = cb.connect().expect("rtsps connect");
    client.options().expect("OPTIONS over TLS");
    server.stop().ok();
}

/// A TLS-handshake FAILURE must not leak an `active_sessions` slot.
///
/// The accept loop reserves the slot atomically BEFORE the TLS handshake
/// (so a connection burst can't bypass the cap), then moves the
/// `SessionSlot` guard into the spawned task. When the handshake fails —
/// here, by sending plaintext at an `rtsps://` server — the session loop
/// never runs, so the old in-`handle_connection` `fetch_sub` would never
/// fire and the slot would leak permanently, eventually wedging the server
/// at its cap forever. The RAII guard's `Drop` releases the slot on this
/// path too, so the counter must return to 0 after the handshakes fail.
#[test]
fn tls_handshake_failure_does_not_leak_session_slot() {
    use std::io::Write;
    use std::net::TcpStream;
    use std::time::{Duration, Instant};

    let certs = SelfSignedCert::generate();
    let mut b = RtspServerBuilder::new("rtsps://127.0.0.1:0").expect("URL parse");
    b.tls_cert(certs.cert_path.clone(), certs.key_path.clone());
    // Small cap so a leak would be obvious (and would wedge the server).
    b.max_sessions(2);
    let server = b.build().expect("server build");
    let _mount = server
        .add_mount("/live", make_muxer_cfg())
        .expect("add_mount");
    server.start().expect("server start");
    let addr = server.local_addr().expect("local_addr");

    // Drive a burst of plaintext connections at the TLS port — each one
    // fails the handshake (the server's `cfg.accept` rejects non-TLS bytes).
    for _ in 0..16 {
        if let Ok(mut s) = TcpStream::connect(addr) {
            // Send obviously-non-TLS bytes so the handshake fails fast.
            let _ = s.write_all(b"OPTIONS rtsp://127.0.0.1/live RTSP/1.0\r\n\r\n");
            // Drop the stream — the server side observes a handshake error.
        }
    }

    // The counter must drain back to 0 (no leaked slots) within a bounded
    // window. If the guard didn't cover the handshake-fail path this would
    // stay pinned at the number of failed handshakes (≥ the cap).
    let deadline = Instant::now() + Duration::from_secs(3);
    let mut final_count = usize::MAX;
    while Instant::now() < deadline {
        final_count = server.stats().active_sessions;
        if final_count == 0 {
            break;
        }
        std::thread::sleep(Duration::from_millis(20));
    }
    assert_eq!(
        final_count, 0,
        "active_sessions leaked after TLS handshake failures (stuck at {final_count})"
    );

    server.stop().ok();
}
