//! Phase 3 Wave F Task 24 — server-side TLS integration tests.
//!
//! Exercises `RtspServerBuilder::tls_cert(...)` with a self-signed cert
//! generated by `rcgen` (see `tests/fixtures/tls_certs.rs`). The
//! end-to-end handshake test is gated behind `#[ignore]` because the
//! Phase 2 client's `RtspClient::connect` path always passes
//! `root_certs = None` to `tls::TlsStream::connect` (it uses the OS
//! native trust store), and `RtspClientBuilder::tls_root_certs` is
//! stored on the builder but not wired through to the client today.
//! Wiring the custom root store through to the live client is a
//! separate follow-up — see DONE memo for Task 24.
//!
//! What we CAN test today: that the server-side TLS path compiles and
//! that bind + `start()` against `rtsps://127.0.0.1:0` with a valid
//! cert + key succeeds. That confirms the cert load + acceptor setup
//! land cleanly even if we can't drive a live handshake to completion.

#![cfg(feature = "tls")]

mod fixtures;

use tst_core::mpegts::mux::{MuxerConfig, MuxerProgramConfigBuilder, VideoCodec};
use tst_rtp::RtspServerBuilder;

use fixtures::tls_certs::SelfSignedCert;

fn make_muxer_cfg() -> MuxerConfig {
    let mut prog = MuxerProgramConfigBuilder::new(1, 0x1000);
    prog.add_video(0x1011, VideoCodec::H264);
    let mut b = MuxerConfig::builder();
    b.add_program(prog.build());
    b.build().expect("MuxerConfig builds")
}

/// Server with TLS cert configured starts cleanly and binds to a port.
/// This is the smoke-level confirmation that `RtspServerBuilder::tls_cert`
/// and the `rtsps://` listener bind path work end-to-end without a live
/// client driving a handshake.
#[test]
fn tls_server_binds_and_starts() {
    let certs = SelfSignedCert::generate();
    let mut b = RtspServerBuilder::new("rtsps://127.0.0.1:0").expect("URL parse");
    b.tls_cert(certs.cert_path.clone(), certs.key_path.clone());
    let server = b.build().expect("server build");
    let _mount = server
        .add_mount("/live", make_muxer_cfg())
        .expect("add_mount");
    server.start().expect("server start");
    let addr = server
        .local_addr()
        .expect("local_addr populated after start");
    assert_eq!(addr.ip().to_string(), "127.0.0.1");
    assert_ne!(addr.port(), 0, "kernel-picked port must be non-zero");
    server.stop().ok();
}

/// Full `rtsps://` handshake against the in-process server with a
/// self-signed cert trusted via a custom rustls root store.
///
/// Currently `#[ignore]`d: the Phase 2 client's
/// `RtspClient::connect_with` hardcodes `root_certs = None` when
/// constructing the `TlsStream`, and `RtspClientBuilder::tls_root_certs`
/// stores the override but the builder's `connect()` does not forward
/// it. Un-ignore once the client-side wiring lands (one-line change in
/// `crates/tst-rtp/src/rtsp/client/mod.rs::connect_with` to thread a
/// `root_certs: Option<RootCertStore>` arg through from the builder).
#[test]
#[ignore = "client-side custom root-store wiring not yet present; RtspClientBuilder::tls_root_certs is stored but unused"]
fn rtsps_handshake_succeeds_with_trusted_root() {
    let certs = SelfSignedCert::generate();
    let mut b = RtspServerBuilder::new("rtsps://127.0.0.1:0").expect("URL parse");
    b.tls_cert(certs.cert_path.clone(), certs.key_path.clone());
    let server = b.build().expect("server build");
    let _mount = server
        .add_mount("/live", make_muxer_cfg())
        .expect("add_mount");
    server.start().expect("server start");
    let port = server.local_addr().expect("local_addr").port();
    let url = format!("rtsps://127.0.0.1:{port}/live");

    // Build a RootCertStore from the test cert PEM. Once
    // `RtspClient::connect_with` forwards a `Option<RootCertStore>` from
    // the builder, the line below will wire through; today it's still
    // discarded.
    let mut roots = rustls::RootCertStore::empty();
    for cert in rustls_pemfile::certs(&mut certs.root_pem.as_bytes()) {
        let cert = cert.expect("PEM cert parse");
        roots.add(cert).expect("add to root store");
    }
    let mut cb = tst_rtp::RtspClientBuilder::new(&url).expect("client builder");
    cb = cb.tls_root_certs(roots);
    let mut client = cb.connect().expect("rtsps connect");
    client.options().expect("OPTIONS over TLS");
    server.stop().ok();
}
